Repository vercel/vercel, pull requests merged in 2018-04, with the labels that each got.

#1205 Support for globally distributed deployments
  .circleci/config.yml
  errors/deploy-invalid-dc.md
  errors/scale-invalid-dc.md
  errors/scale-ls.md
  package.json
  src/now.js
  src/providers/sh/commands/alias.js
  src/providers/sh/commands/certs.js
  src/providers/sh/commands/deploy.js
  src/providers/sh/commands/domains.js
  src/providers/sh/commands/inspect.js
  src/providers/sh/commands/list.js
  src/providers/sh/commands/logs.js
  src/providers/sh/commands/remove.js
  src/providers/sh/commands/scale.js
  src/providers/sh/index.js
  src/providers/sh/util/alias.js
  src/providers/sh/util/arg-common.js
  src/providers/sh/util/build-logger.js
  src/providers/sh/util/certs.js
  src/providers/sh/util/dcs.js
  src/providers/sh/util/domains/is-valid-domain.js
  src/providers/sh/util/error.js
  src/providers/sh/util/events.js
  src/providers/sh/util/get-context-name.js
  src/providers/sh/util/index.js
  src/providers/sh/util/is-elf.js
  src/providers/sh/util/logs.js
  src/providers/sh/util/re-alias.js
  src/providers/sh/util/scale.js
  src/providers/sh/util/sort-deployments.js
  src/util/output/elapsed.js
  src/util/output/index.js
  src/util/output/stamp.js
  src/util/output/wait.js
  test/helpers/remove.js
  test/integration.js
  webpack.config.js
  yarn.lock
Labels: 🌪 major

#1228 Properly handle event polling
  src/providers/sh/util/events.js
Labels: 💅 patch

#1257 Improved integration tests
  test/helpers/remove.js
  test/integration.js
Labels: 💅 patch

#1259 Re-added dependencies required for download
  package.json
  yarn.lock
Labels: 💅 patch

#1260 Ensure listing single deployments work
  src/providers/sh/commands/deploy.js
  src/providers/sh/commands/list.js
  src/util/output/index.js
Labels: patch

#1263 Make `now ls` work as expected
  src/providers/sh/commands/list.js
Labels: patch

#1275 Replaced the update checker
  package.json
  src/now.js
  yarn.lock
Labels: high priority, patch

#1281 Don't render update message on non-TTY
  src/now.js
Labels: patch

#1303 Added missing dependencies
  download/webpack.config.js
  package.json
  yarn.lock
Labels: patch
