Repository vercel/vercel, pull requests merged in 2018-02, with the labels that each got.

#1124 Perfected OSS confirmation prompt
  src/providers/sh/commands/deploy.js
  src/providers/sh/util/index.js
Labels: version-patch

#1126 Corrected whitelisting mechanism for `now.json`
  src/providers/sh/util/get-files.js
  test/_fixtures/files-in-package-ignore/.npmignore
  test/_fixtures/files-in-package-ignore/build/a/should-be-included.js
  test/_fixtures/files-overrides-gitignore/test.json
  test/_fixtures/now-json-docker-dockerignore-override/.dockerignore
  test/_fixtures/now-json-docker-dockerignore-override/.gitignore
  test/_fixtures/now-json-docker-dockerignore-override/Dockerfile
  test/_fixtures/now-json-docker-dockerignore-override/a.js
  test/_fixtures/now-json-docker-dockerignore-override/b.js
  test/_fixtures/now-json-docker-dockerignore-override/build/a/c.js
  test/_fixtures/now-json-docker-dockerignore-override/c.js
  test/_fixtures/now-json-docker-dockerignore-override/now.json
  test/_fixtures/now-json-docker-gitignore-override/.gitignore
  test/_fixtures/now-json-docker-gitignore-override/Dockerfile
  test/_fixtures/now-json-docker-gitignore-override/a.js
  test/_fixtures/now-json-docker-gitignore-override/b.js
  test/_fixtures/now-json-docker-gitignore-override/build/a/c.js
  test/_fixtures/now-json-docker-gitignore-override/now.json
  test/_fixtures/now-json-npm-gitignore-override/.gitignore
  test/_fixtures/now-json-npm-gitignore-override/a.js
  test/_fixtures/now-json-npm-gitignore-override/b.js
  test/_fixtures/now-json-npm-gitignore-override/build/a/c.js
  test/_fixtures/now-json-npm-gitignore-override/now.json
  test/_fixtures/now-json-npm-gitignore-override/package.json
  test/_fixtures/now-json-npm-npmignore-override/.gitignore
  test/_fixtures/now-json-npm-npmignore-override/.npmignore
  test/_fixtures/now-json-npm-npmignore-override/a.js
  test/_fixtures/now-json-npm-npmignore-override/b.js
  test/_fixtures/now-json-npm-npmignore-override/build/a/c.js
  test/_fixtures/now-json-npm-npmignore-override/c.js
  test/_fixtures/now-json-npm-npmignore-override/now.json
  test/_fixtures/now-json-npm-npmignore-override/package.json
  test/_fixtures/now-json-static-gitignore-override/.gitignore
  test/_fixtures/now-json-static-gitignore-override/a.js
  test/_fixtures/now-json-static-gitignore-override/b.js
  test/_fixtures/now-json-static-gitignore-override/build/a/c.js
  test/_fixtures/now-json-static-gitignore-override/now.json
  test/_fixtures/now-json-static-gitignore-override/package.json
  test/index.js
Labels: version-patch

#1143 Removed undefined variable reference
  src/providers/sh/commands/deploy.js
Labels: 💅 patch

#1139 Made `now <file>` work
  src/providers/sh/commands/deploy.js
  src/providers/sh/util/index.js
  yarn.lock
Labels: 💫 minor

#1144 Don't upload meta files for static deployments
  src/providers/sh/util/get-files.js
  test/index.js
  yarn.lock
Labels: 💅 patch

#1146 Add new `output` helper functions
  package.json
  src/providers/sh/commands/deploy.js
  src/providers/sh/util/agent.js
  src/providers/sh/util/build-logger.js
  src/providers/sh/util/get-files.js
  src/providers/sh/util/index.js
  src/util/output/index.js
  test/index.js
Labels: 💅 patch

#1150 Added missing variable references
  src/providers/sh/util/index.js
Labels: 💅 patch

#1151 Ensure `chalk` is being used properly
  src/providers/sh/util/index.js
Labels: 💅 patch

#1148 Added support multiple path arguments
  link/package-lock.json
  package.json
  readme.md
  src/providers/sh/commands/deploy.js
  src/providers/sh/util/build-logger.js
  src/providers/sh/util/get-files.js
  src/providers/sh/util/index.js
  src/util/get-user.js
Labels: 💫 minor
