Repository vercel/vercel, pull requests merged in 2019-04, with the labels that each got.

#2048 [now dev] Add support for `.env` file to define Now secrets
  package.json
  src/commands/dev/lib/dev-builder.ts
  src/commands/dev/lib/dev-server.ts
  src/commands/dev/lib/types.ts
  src/util/errors-ts.ts
  yarn.lock
Labels: now dev

#2095 resolves parameters in headers location
  src/commands/dev/lib/dev-router.ts
Labels: now dev

#2102 Make npm not prefer offline
  src/commands/dev/lib/builder-cache.ts
Labels: enhancement

#2131 Print full validation error message
  src/commands/deploy/latest.js
  src/commands/deploy/legacy.js
Labels: enhancement

#2132 Stop indicating whether CDN is enabled
  src/commands/domains/inspect.ts
  src/commands/domains/ls.ts
  src/types.ts
Labels: enhancement

#2133 Add a note about the CDN always being enabled
  src/commands/domains/inspect.ts
  src/commands/domains/ls.ts
Labels: enhancement

#2159 [now dev] Use empty version string for `@now/static`
  src/commands/dev/lib/builder-cache.ts
Labels: now dev

#2164 [now dev] Add `host` property to the invoke payload
  src/commands/dev/lib/dev-server.ts
  src/commands/dev/lib/types.ts
Labels: now dev

#2153 Added file watcher to `now dev`
  @types/promisepipe/index.d.ts
  package.json
  src/commands/dev/lib/builder-cache.ts
  src/commands/dev/lib/dev-builder.ts
  src/commands/dev/lib/dev-router.ts
  src/commands/dev/lib/dev-server.ts
  src/commands/dev/lib/nsfw-module.ts
  src/commands/dev/lib/static-builder.ts
  src/commands/dev/lib/types.ts
  yarn.lock
Labels: now dev

#2174 [now dev] Pass `filesChanges` and `filesRemoved` array to builder's `build()`
  src/commands/dev/lib/dev-builder.ts
  src/commands/dev/lib/dev-server.ts
  src/commands/dev/lib/nsfw-module.ts
  src/commands/dev/lib/types.ts
Labels: enhancement

#2177 [now dev] Default the `Content-Type` to "application/octet-stream"
  src/commands/dev/lib/dev-server.ts
  src/commands/dev/lib/mime-type.ts
  src/commands/dev/lib/types.ts
Labels: now dev

#2184 [now dev] Don't trigger a rebuild if an asset was deleted
  src/commands/dev/lib/dev-builder.ts
  src/commands/dev/lib/dev-server.ts
  src/commands/dev/lib/types.ts
Labels: now dev

#2185 [now dev] Reuse the same `workPath` for subsequent builds
  src/commands/dev/lib/dev-builder.ts
  src/commands/dev/lib/types.ts
Labels: now dev

#2189 Now CLI gets a fixed alias
  test/integration.js
Labels: work in progress

#2195 Match only the important part while routing
  src/commands/dev/lib/dev-router.ts
Labels: enhancement

#2198 Prevent exit if client closes proxy connection
  src/commands/dev/lib/dev-server.ts
Labels: enhancement

#2199 Better name for `continuous` property
  src/commands/dev/lib/dev-server.ts
  src/commands/dev/lib/types.ts
Labels: enhancement

#2200 Initial build should set `requestPath` to `null`
  src/commands/dev/lib/dev-builder.ts
  src/commands/dev/lib/dev-server.ts
  src/commands/dev/lib/types.ts
Labels: enhancement

#2227 [now dev] Invoke builders in a forked child process
  package.json
  src/commands/dev/lib/builder-cache.ts
  src/commands/dev/lib/builder.js
  src/commands/dev/lib/dev-builder.ts
  src/commands/dev/lib/dev-server.ts
  src/commands/dev/lib/types.ts
  yarn.lock
Labels: now dev

#2230 [now dev] Force `@now/static` to run in-memory
  src/commands/dev/lib/builder-cache.ts
  src/commands/dev/lib/dev-builder.ts
  src/commands/dev/lib/types.ts
Labels: now dev

#2240 Support Windows when downloading file watcher
  src/commands/dev/lib/nsfw-module.ts
Labels: enhancement

#2242 Bumped `@zeit/nsfw` to latest
  package.json
  yarn.lock
Labels: enhancement

#2244 [now dev] WIP Better logging while building and error recovery
  src/commands/dev/lib/builder.js
  src/commands/dev/lib/dev-builder.ts
  src/commands/dev/lib/dev-server.ts
Labels: enhancement, now dev

#2249 Only print stopping server if already printed URL
  src/commands/dev/lib/dev-server.ts
Labels: enhancement

#2250 Print missing line when stopping server
  src/commands/dev/lib/dev-server.ts
Labels: enhancement

#2251 Do not check for @now/static Builder updates
  src/commands/dev/lib/dev-builder.ts
  src/commands/dev/lib/dev-server.ts
Labels: enhancement

#2258 Revert "Add a logout test case"
  test/integration.js
Labels: enhancement

#2261 Fixed error for `.env` and `.env.build`
  errors/missing-env-file.md
  src/commands/dev/dev.ts
  src/commands/dev/lib/dev-server.ts
  src/util/errors-ts.ts
Labels: enhancement

#2262 Make the message for when the server is running shorter
  src/commands/dev/lib/dev-server.ts
  test/dev-server.unit.js
Labels: enhancement

#2266 Do not print installing builders for no builds
  src/commands/dev/lib/builder-cache.ts
  test/dev-server.unit.js
Labels: enhancement

#2267 Correctly log when setting up Builders
  src/commands/dev/dev.ts
  src/commands/dev/lib/dev-builder.ts
  src/commands/dev/lib/dev-server.ts
  src/util/output/create-output.ts
Labels: enhancement

#2268 Enable `cleanUrls` for entirely static projects
  src/commands/dev/lib/dev-server.ts
Labels: enhancement

#2269 [now dev] Show builder logs, even after build completes
  src/commands/dev/lib/dev-builder.ts
  src/commands/dev/lib/dev-server.ts
Labels: now dev

#2233 [now-dev] Fix .nowignore to match production
  src/commands/dev/lib/dev-builder.ts
  src/commands/dev/lib/dev-server.ts
  src/commands/dev/lib/glob.ts
  src/util/get-files.ts
Labels: bug, now dev

#2270 [now-dev] Lazy yarn installer
  @types/which-promise/index.d.ts
  src/commands/dev/lib/dev-builder.ts
  src/commands/dev/lib/dev-server.ts
  src/commands/dev/lib/yarn-installer.ts
Labels: now dev

#2272 [now dev] Install builders with `yarn` instead of `npm`
  src/commands/dev/lib/builder-cache.ts
  src/commands/dev/lib/dev-server.ts
  src/commands/dev/lib/yarn-installer.ts
  test/dev-server.unit.js
Labels: now dev
