Repository vercel/vercel, pull requests merged in 2019-08, with the labels that each got.

#2729 Add automerge config
  .kodiak.toml
Labels: automerge

#2726 Add `accept: application/json` header to API HTTP requests
  src/util/index.js
Labels: automerge

#2727 Print HTTP status code upon API JSON parse errors
  src/util/index.js
Labels: automerge

#2731 Update `serve-handler` to v6.1.1
  package.json
  test/dev-server.unit.js
  yarn.lock
Labels: automerge

#2735 [now dev] Remove leftover `console.error()` call
  src/util/dev/server.ts
Labels: automerge

#2736 Bump `@now/build-utils` to 0.9.12
  package.json
  yarn.lock
Labels: automerge

#2737 Update `clipboardy` to v2.1.0
  package.json
  yarn.lock
Labels: automerge

#2750 [now projects] Add subcommand alias for `now project`
  src/commands/index.js
Labels: automerge

#2755 Use the correct URL in the `auth.json` and `config.json` files
  src/util/config/get-default.js
Labels: automerge

#2753 [now dev] Use canary builders for the canary version
  src/util/dev/server.ts
  test/dev/integration.js
Labels: automerge, zero config

#2761 Fix "occured" -> "occurred" typos
  src/commands/deploy/latest.js
  src/util/dev/server.ts
Labels: automerge

#2763 [now scale] Fix default `max: auto` value in `--help` output
  src/commands/scale.js
Labels: automerge

#2762 [now rm] Use the proper `client` so that the process does not hang
  src/commands/remove.js
  test/integration.js
Labels: automerge

#2768 Remove leftover `console.log()` in integration tests
  test/integration.js
Labels: automerge

#2767 Display rate limit errors message from API response
  src/util/handle-error.ts
Labels: automerge

#2776 Sleep 2 seconds after the `now rm` integration test
  test/integration.js
Labels: automerge

#2747 Add more alias support
  src/util/alias/extract-domain.ts
  src/util/alias/is-wildcard-alias.ts
  src/util/certs/create-cert-for-alias.ts
  src/util/certs/get-wildcard-cns-for-alias.ts
  src/util/domains/setup-domain.ts
  test/integration.js
Labels: automerge

#2777 Remove a couple unused `import`
  src/util/handle-error.ts
Labels: automerge

#2779 [now domain] Handle thrown API errors when purchasing domain fails
  src/commands/domains/buy.ts
Labels: automerge

#2874 [tests] Change run script from bash to node
  .circleci/run.sh
  package.json
  packages/now-cli/test/dev/integration.js
  packages/now-python/yarn.lock
  run.js
Labels: automerge

#2876 [tests] Fix unit tests & coverage step
  .circleci/config.yml
Labels: automerge

#2873 [now-static-build] Support ejected create-react-app
  packages/now-static-build/src/frameworks.ts
  packages/now-static-build/test/fixtures/26-ejected-cra/.gitignore
  packages/now-static-build/test/fixtures/26-ejected-cra/README.md
  packages/now-static-build/test/fixtures/26-ejected-cra/config/env.js
  packages/now-static-build/test/fixtures/26-ejected-cra/config/jest/cssTransform.js
  packages/now-static-build/test/fixtures/26-ejected-cra/config/jest/fileTransform.js
  packages/now-static-build/test/fixtures/26-ejected-cra/config/modules.js
  packages/now-static-build/test/fixtures/26-ejected-cra/config/paths.js
  packages/now-static-build/test/fixtures/26-ejected-cra/config/pnpTs.js
  packages/now-static-build/test/fixtures/26-ejected-cra/config/webpack.config.js
  packages/now-static-build/test/fixtures/26-ejected-cra/config/webpackDevServer.config.js
  packages/now-static-build/test/fixtures/26-ejected-cra/now.json
  packages/now-static-build/test/fixtures/26-ejected-cra/package.json
  packages/now-static-build/test/fixtures/26-ejected-cra/public/favicon.ico
  packages/now-static-build/test/fixtures/26-ejected-cra/public/index.html
  packages/now-static-build/test/fixtures/26-ejected-cra/public/manifest.json
  packages/now-static-build/test/fixtures/26-ejected-cra/public/testing-output-dir.txt
  packages/now-static-build/test/fixtures/26-ejected-cra/scripts/build.js
  packages/now-static-build/test/fixtures/26-ejected-cra/scripts/start.js
  packages/now-static-build/test/fixtures/26-ejected-cra/src/App.css
  packages/now-static-build/test/fixtures/26-ejected-cra/src/App.js
  packages/now-static-build/test/fixtures/26-ejected-cra/src/index.css
  packages/now-static-build/test/fixtures/26-ejected-cra/src/index.js
  packages/now-static-build/test/fixtures/26-ejected-cra/src/logo.svg
  packages/now-static-build/test/fixtures/26-ejected-cra/src/serviceWorker.js
  packages/now-static-build/test/fixtures/26-ejected-cra/yarn.lock
Labels: @now/static-build, automerge

#2780 [now dev] Update `yarn` to v1.17.3
  packages/now-cli/src/util/dev/yarn-installer.ts
  packages/now-cli/test/dev/integration.js
Labels: automerge, now-dev

#2870 [now-cli] Make sure to have event action as string
  packages/now-cli/src/index.js
Labels: automerge, now-cli

#2871 [now-cli] Validate builds and routes for `now dev`
  packages/now-cli/package.json
  packages/now-cli/src/commands/dev/dev.ts
  packages/now-cli/src/util/dev/server.ts
  packages/now-cli/src/util/dev/validate.ts
  packages/now-cli/test/dev/fixtures/invalid-builds/index.html
  packages/now-cli/test/dev/fixtures/invalid-builds/now.json
  packages/now-cli/test/dev/fixtures/invalid-routes/index.html
  packages/now-cli/test/dev/fixtures/invalid-routes/now.json
  packages/now-cli/test/dev/integration.js
  run.js
  yarn.lock
Labels: automerge, now-cli, now-dev

#2884 [now-static-build] Use `debug()` from build-utils
  packages/now-static-build/src/index.ts
Labels: @now/static-build, automerge

#2883 [now-ruby] Use `debug()` from build-utils
  packages/now-ruby/index.ts
  packages/now-ruby/install-ruby.ts
Labels: @now/ruby, automerge

#2885 [now-go] Use `debug()` from build-utils
  packages/now-go/go-helpers.ts
  packages/now-go/index.ts
  packages/now-go/package.json
  yarn.lock
Labels: @now/go, automerge

#2881 [now-next] Use `debug()` from build-utils
  packages/now-next/src/index.ts
Labels: @now/next, automerge

#2890 [tests] Ignore fixtures in GitHub Languages & fix yarn.lock
  .gitattributes
  yarn.lock
Labels: automerge

#2891 Add GH Actions Publish Workflow
  .github/workflows/publish.yml
Labels: automerge

#2787 [now alias] Improve alias support
  packages/now-cli/src/commands/alias/set.ts
  packages/now-cli/src/commands/deploy/latest.js
  packages/now-cli/src/util/alias/extract-domain.ts
  packages/now-cli/src/util/alias/is-wildcard-alias.ts
  packages/now-cli/src/util/certs/create-cert-for-alias.ts
  packages/now-cli/src/util/certs/get-wildcard-cns-for-alias.ts
  packages/now-cli/src/util/domains/setup-domain.ts
  packages/now-cli/test/integration.js
Labels: automerge

#2894 [now-next] Do not add initial files to lambda
  packages/now-next/src/index.ts
Labels: @now/next, automerge

#2895 [now-build-utils] Add `mutable` option for backwards compatibility
  packages/now-build-utils/src/file-ref.ts
Labels: @now/build-utils, automerge, important

#2902 [now-cli] Update `now alias` warning for `--prod`
  packages/now-cli/src/util/alias/get-inferred-targets.ts
Labels: automerge

#2898 [now-cli] Change success message after login
  packages/now-cli/src/commands/login.js
  packages/now-cli/test/integration.js
Labels: automerge, now-cli

#2903 [now-cli] Validate inputs for alias, list and remove
  packages/now-cli/src/commands/alias/rm.js
  packages/now-cli/src/commands/alias/set.ts
  packages/now-cli/src/commands/list.js
  packages/now-cli/src/commands/remove.js
  packages/now-cli/src/util/is-valid-name.ts
  packages/now-cli/test/integration.js
  packages/now-cli/test/unit.js
Labels: automerge, now-cli

#2892 [now-next] Optimize lambda creation
  .circleci/config.yml
  .github/workflows/publish.yml
  package.json
  packages/now-next/global.d.ts
  packages/now-next/package.json
  packages/now-next/src/index.ts
  packages/now-next/src/utils.ts
  packages/now-next/tsconfig.json
  packages/now-node-bridge/package.json
  packages/now-node-bridge/src/bridge.ts
  packages/now-node/package.json
  packages/now-ruby/package.json
  packages/now-ruby/tsconfig.json
  packages/now-static-build/package.json
  yarn.lock
Labels: @now/next, automerge

#2905 [now-cli] Allow to fetch more certificates with paging
  packages/now-cli/src/commands/certs/index.js
  packages/now-cli/src/commands/certs/ls.js
  packages/now-cli/src/util/certs/get-certs.ts
  packages/now-cli/test/integration.js
Labels: automerge, now-cli

#2907 [now-cli] Remove deprecated `@now/php` builder from bundled builders tarball
  packages/now-cli/package.json
  yarn.lock
Labels: automerge, now-cli

#2909 [now-cli] fix login test
  packages/now-cli/test/integration.js
Labels: automerge

#2913 [now-cli] Use a Map for the valid sub-commands
  packages/now-cli/src/commands/index.js
  packages/now-cli/src/commands/index.ts
  packages/now-cli/src/index.js
  packages/now-cli/test/integration.js
Labels: automerge, bug

#2908 [now-cli] Implement `continue: true` with `dest`
  packages/now-cli/src/util/dev/router.ts
  packages/now-cli/src/util/dev/server.ts
  packages/now-cli/src/util/dev/types.ts
  packages/now-cli/test/dev-router.unit.js
Labels: automerge

#2910 [tests] Remove fixtures files for integration tests
  .gitignore
  packages/now-cli/test/fixtures/integration/.gitkeep
  packages/now-cli/test/fixtures/integration/build-env-arg/Dockerfile
  packages/now-cli/test/fixtures/integration/build-env-arg/now.json
  packages/now-cli/test/fixtures/integration/build-env/Dockerfile
  packages/now-cli/test/fixtures/integration/build-env/now.json
  packages/now-cli/test/fixtures/integration/builds-no-list/now.json
  packages/now-cli/test/fixtures/integration/builds-wrong/index.html
  packages/now-cli/test/fixtures/integration/builds-wrong/now.json
  packages/now-cli/test/fixtures/integration/builds/index.html
  packages/now-cli/test/fixtures/integration/builds/now.json
  packages/now-cli/test/fixtures/integration/config-alias-property/index.html
  packages/now-cli/test/fixtures/integration/config-alias-property/now.json
  packages/now-cli/test/fixtures/integration/config-scope-property-email/index.html
  packages/now-cli/test/fixtures/integration/config-scope-property-email/now.json
  packages/now-cli/test/fixtures/integration/config-scope-property-username/index.html
  packages/now-cli/test/fixtures/integration/config-scope-property-username/now.json
  packages/now-cli/test/fixtures/integration/dockerfile/Dockerfile
  packages/now-cli/test/fixtures/integration/dockerfile/index.js
  packages/now-cli/test/fixtures/integration/dockerfile/now.json
  packages/now-cli/test/fixtures/integration/dockerfile/package.json
  packages/now-cli/test/fixtures/integration/failing-build/package.json
  packages/now-cli/test/fixtures/integration/node/index.js
  packages/now-cli/test/fixtures/integration/node/now.json
  packages/now-cli/test/fixtures/integration/node/package.json
  packages/now-cli/test/fixtures/integration/now-dev-fail-dev-script/package.json
  packages/now-cli/test/fixtures/integration/now-revert-alias-1/index.json
  packages/now-cli/test/fixtures/integration/now-revert-alias-1/now.json
  packages/now-cli/test/fixtures/integration/now-revert-alias-2/index.json
  packages/now-cli/test/fixtures/integration/now-revert-alias-2/now.json
  packages/now-cli/test/fixtures/integration/now-static-build/Dockerfile
  packages/now-cli/test/fixtures/integration/now-static-build/now.json
  packages/now-cli/test/fixtures/integration/single-dotfile/.testing
  packages/now-cli/test/fixtures/integration/static-deployment/index.txt
  packages/now-cli/test/fixtures/integration/static-multiple-files/first.png
  packages/now-cli/test/fixtures/integration/static-multiple-files/now.json
  packages/now-cli/test/fixtures/integration/static-multiple-files/second.png
  packages/now-cli/test/fixtures/integration/static-single-file/first.png
  packages/now-cli/test/fixtures/integration/static-single-file/now.json
  packages/now-cli/test/fixtures/integration/v1-warning-link/now.json
  packages/now-cli/test/fixtures/integration/v1-warning-link/package.json
Labels: automerge

#2886 [now-cli] Update readme and links
  README.md
  packages/now-cli/README.md
  packages/now-cli/package.json
Labels: automerge, now-cli

#2914 [tests] Unify linting and autoformatting
  .eslintignore
  .eslintrc.json
  .prettierrc
  package.json
  packages/now-build-utils/src/detect-builders.ts
  packages/now-build-utils/src/detect-routes.ts
  packages/now-build-utils/test/test.js
  packages/now-cgi/index.js
  packages/now-cli/.eslintignore
  packages/now-cli/.eslintrc.js
  packages/now-cli/package.json
  packages/now-cli/src/commands/deploy/legacy.ts
  packages/now-cli/src/util/input/list.js
  packages/now-cli/src/util/pkg.ts
  packages/now-client/package.json
  packages/now-go/index.ts
  packages/now-go/test/test.js
  packages/now-next/global.d.ts
  packages/now-next/src/index.ts
  packages/now-next/test/integration/index.test.js
  packages/now-next/test/test.js
  packages/now-next/test/unit/build.test.js
  packages/now-next/test/unit/utils.test.js
  packages/now-node-bridge/.eslintrc
  packages/now-node-bridge/src/bridge.ts
  packages/now-node/src/example-import.ts
  packages/now-node/src/index.ts
  packages/now-node/src/typescript.ts
  packages/now-node/test/helpers.test.js
  packages/now-node/test/test.js
  packages/now-python/test/test.js
  packages/now-routing-utils/src/index.ts
  packages/now-ruby/index.ts
  packages/now-ruby/test/test.js
  packages/now-static-build/test/test.js
  run.js
  test/integration/now-node/airtable/index.js
  test/integration/now-node/aws-sdk/index.js
  test/integration/now-node/axios/index.js
  test/integration/now-node/index.test.js
  test/integration/now-node/mongoose/index.js
  test/lib/run-build-lambda.js
  yarn.lock
Labels: automerge

#2877 [now-cli] Use XDG standard instead of writing to home directory
  packages/now-cli/package.json
  packages/now-cli/src/util/config/global-path.ts
  yarn.lock
Labels: automerge, now-cli

#2915 [now-cli] Improve check for update command
  packages/now-cli/src/util/get-update-command.ts
Labels: automerge, now-cli

#2920 [tests] Unify `.editorconfig`
  .editorconfig
  packages/now-cgi/.editorconfig
  packages/now-cgi/.gitignore
  packages/now-cgi/index.js
Labels: automerge

#2919 [now-next] Use patched version of yazl and trace API pages separate
  packages/now-next/global.d.ts
  packages/now-next/package.json
  packages/now-next/src/index.ts
  packages/now-next/src/utils.ts
  packages/now-next/tsconfig.json
  yarn.lock
Labels: @now/next, automerge

#2911 [now-go] Fix `analyze.go` fails to parse source file with comments
  packages/now-go/test/fixtures/15-analyze-with-comments/index.go
  packages/now-go/test/fixtures/15-analyze-with-comments/multiple.go
  packages/now-go/test/fixtures/15-analyze-with-comments/now.json
  packages/now-go/util/analyze.go
Labels: @now/go, automerge

#2927 [now-node] Cleanup debug output
  packages/now-node/src/index.ts
Labels: @now/node, automerge

#2922 [now-cli] Output `--json` to stdout for `now alias ls <url>`
  packages/now-cli/src/commands/alias/ls.js
Labels: automerge, now-cli
