Repository vercel/vercel, pull requests merged in 2023-10, with the labels that each got.

#10632 [static-build] Add Astro 3.x fixture
  .changeset/old-countries-cheat.md
  packages/static-build/test/fixtures/77-astro-3/.gitignore
  packages/static-build/test/fixtures/77-astro-3/astro.config.mjs
  packages/static-build/test/fixtures/77-astro-3/package-lock.json
  packages/static-build/test/fixtures/77-astro-3/package.json
  packages/static-build/test/fixtures/77-astro-3/probes.json
  packages/static-build/test/fixtures/77-astro-3/src/components/Card.astro
  packages/static-build/test/fixtures/77-astro-3/src/env.d.ts
  packages/static-build/test/fixtures/77-astro-3/src/layouts/Layout.astro
  packages/static-build/test/fixtures/77-astro-3/src/pages/index.astro
  packages/static-build/test/fixtures/77-astro-3/tsconfig.json
Labels: area: tests, area: static-build, pr: automerge

#10634 [static-build] Add Astro 2.x fixture
  .changeset/weak-meals-admire.md
  packages/static-build/test/fixtures/76-astro-2/.gitignore
  packages/static-build/test/fixtures/76-astro-2/astro.config.mjs
  packages/static-build/test/fixtures/76-astro-2/package-lock.json
  packages/static-build/test/fixtures/76-astro-2/package.json
  packages/static-build/test/fixtures/76-astro-2/probes.json
  packages/static-build/test/fixtures/76-astro-2/src/components/Card.astro
  packages/static-build/test/fixtures/76-astro-2/src/env.d.ts
  packages/static-build/test/fixtures/76-astro-2/src/layouts/Layout.astro
  packages/static-build/test/fixtures/76-astro-2/src/pages/index.astro
  packages/static-build/test/fixtures/76-astro-2/tsconfig.json
Labels: area: tests, area: static-build, pr: automerge

#10633 Revert "[next][node][redwood][remix] Update @vercel/nft"
  .changeset/strange-weeks-fry.md
  packages/next/package.json
  packages/node/package.json
  packages/redwood/package.json
  packages/remix/package.json
  pnpm-lock.yaml
Labels: pr: automerge

#10631 [next] Correct output file tracing and limit calculation
  .changeset/bright-dolls-drop.md
  packages/next/src/constants.ts
  packages/next/src/index.ts
  packages/next/src/server-build.ts
  packages/next/src/utils.ts
  packages/next/test/integration/integration-2.test.js
  packages/next/test/unit/fixtures/01-normalize-paths/index.test.js
  packages/next/test/unit/fixtures/01-normalize-paths/yarn.lock
  packages/next/test/unit/fixtures/02-edge-function-basepath/index.test.js
  packages/next/test/unit/fixtures/02-edge-function-basepath/yarn.lock
  packages/next/test/unit/fixtures/03-with-api-routes/yarn.lock
  packages/next/test/unit/fixtures/04-edge-function-i18n/index.test.js
Labels: pr: automerge

#10644 [next][node][redwood][remix] Update @vercel/nft 0.24.2
  .changeset/wicked-geese-cheer.md
  packages/next/package.json
  packages/node/package.json
  packages/redwood/package.json
  packages/remix/package.json
  pnpm-lock.yaml
Labels: pr: automerge

#10646 next: bump minimal version for bundled server usage
  .changeset/poor-moles-teach.md
  packages/next/src/server-build.ts
Labels: area: next, pr: automerge

#10645 [static-build] Add Svelte 5 fixture
  .changeset/quiet-rockets-drop.md
  packages/static-build/test/fixtures/79-svelte-5/.gitignore
  packages/static-build/test/fixtures/79-svelte-5/.npmrc
  packages/static-build/test/fixtures/79-svelte-5/package-lock.json
  packages/static-build/test/fixtures/79-svelte-5/package.json
  packages/static-build/test/fixtures/79-svelte-5/probes.json
  packages/static-build/test/fixtures/79-svelte-5/src/app.d.ts
  packages/static-build/test/fixtures/79-svelte-5/src/app.html
  packages/static-build/test/fixtures/79-svelte-5/src/lib/index.js
  packages/static-build/test/fixtures/79-svelte-5/src/routes/+page.svelte
  packages/static-build/test/fixtures/79-svelte-5/svelte.config.js
  packages/static-build/test/fixtures/79-svelte-5/tsconfig.json
  packages/static-build/test/fixtures/79-svelte-5/vite.config.ts
Labels: area: build-utils, area: tests, pr: automerge

#10642 [next] fix test missing `yarn.lock` file
  .changeset/big-schools-deliver.md
  packages/next/test/unit/fixtures/04-edge-function-i18n/yarn.lock
Labels: area: tests, pr: automerge

#10651 Revert "[next] Correct output file tracing and limit calculation (#10631)"
  .changeset/early-masks-press.md
  packages/next/src/constants.ts
  packages/next/src/index.ts
  packages/next/src/server-build.ts
  packages/next/src/utils.ts
  packages/next/test/integration/integration-2.test.js
  packages/next/test/unit/fixtures/01-normalize-paths/index.test.js
  packages/next/test/unit/fixtures/01-normalize-paths/yarn.lock
  packages/next/test/unit/fixtures/02-edge-function-basepath/index.test.js
  packages/next/test/unit/fixtures/02-edge-function-basepath/yarn.lock
  packages/next/test/unit/fixtures/03-with-api-routes/yarn.lock
  packages/next/test/unit/fixtures/04-edge-function-i18n/index.test.js
Labels: area: next, pr: automerge

#10662 [cli] Remove unused options to testFixtureStdio test helper
  .changeset/plenty-hairs-dance.md
  packages/cli/test/dev/utils.js
Labels: area: cli, area: tests, pr: automerge

#10663 [cli] Remove unused test helpers
  .changeset/dry-brooms-give.md
  packages/cli/package.json
  packages/cli/test/helpers/get-url.js
  packages/cli/test/helpers/parse-list.js
  pnpm-lock.yaml
Labels: area: cli, area: tests, pr: automerge

#10667 Add `type-check` and unify tsconfig
  .changeset/khaki-rings-wait.md
  .github/workflows/test-lint.yml
  package.json
  packages/build-utils/package.json
  packages/build-utils/test/unit.read-config-file.test.ts
  packages/build-utils/tsconfig.json
  packages/cli/package.json
  packages/cli/scripts/compile-templates.mjs
  packages/cli/src/commands/build/index.ts
  packages/cli/tsconfig.json
  packages/client/package.json
  packages/client/tsconfig.json
  packages/edge/package.json
  packages/edge/tsconfig.json
  packages/error-utils/package.json
  packages/error-utils/tsconfig.json
  packages/frameworks/package.json
  packages/frameworks/tsconfig.json
  packages/fs-detectors/package.json
  packages/fs-detectors/tsconfig.json
  packages/gatsby-plugin-vercel-builder/package.json
  packages/gatsby-plugin-vercel-builder/tsconfig.json
  packages/go/package.json
  packages/go/tsconfig.json
  packages/hydrogen/package.json
  packages/hydrogen/tsconfig.json
  packages/next/package.json
  packages/next/tsconfig.json
  packages/node/package.json
  packages/node/tsconfig.json
  packages/python/package.json
  packages/python/tsconfig.json
  packages/redwood/package.json
  packages/redwood/tsconfig.json
  packages/remix/package.json
  packages/remix/tsconfig.json
  packages/routing-utils/package.json
  packages/routing-utils/tsconfig.json
  packages/ruby/package.json
  packages/ruby/tsconfig.json
  packages/static-build/package.json
  packages/static-build/tsconfig.json
  packages/static-config/package.json
  packages/static-config/tsconfig.json
  pnpm-lock.yaml
  tsconfig.base.json
  turbo.json
  utils/build.mjs
Labels: pr: automerge

#10659 [static-build] add umi-4 fixture
  .changeset/hot-pigs-trade.md
  packages/static-build/test/fixtures/umi-v4/.gitignore
  packages/static-build/test/fixtures/umi-v4/.npmrc
  packages/static-build/test/fixtures/umi-v4/.umirc.ts
  packages/static-build/test/fixtures/umi-v4/package-lock.json
  packages/static-build/test/fixtures/umi-v4/package.json
  packages/static-build/test/fixtures/umi-v4/probes.json
  packages/static-build/test/fixtures/umi-v4/src/layouts/index.less
  packages/static-build/test/fixtures/umi-v4/src/layouts/index.tsx
  packages/static-build/test/fixtures/umi-v4/src/pages/docs.tsx
  packages/static-build/test/fixtures/umi-v4/src/pages/index.tsx
  packages/static-build/test/fixtures/umi-v4/tsconfig.json
  packages/static-build/test/fixtures/umi-v4/typings.d.ts
Labels: area: tests, area: static-build, pr: automerge

#10680 Run workflows using Node 16
  .changeset/olive-tools-agree.md
  .github/workflows/cron-update-gatsby-fixtures.yml
  .github/workflows/update-remix-run-dev.yml
Labels: pr: automerge

#10682 [static-build] Add basic Middleman v4 fixture
  .changeset/strange-masks-vanish.md
  packages/static-build/test/fixtures/middleman-v4/.gitignore
  packages/static-build/test/fixtures/middleman-v4/Gemfile
  packages/static-build/test/fixtures/middleman-v4/Gemfile.lock
  packages/static-build/test/fixtures/middleman-v4/config.rb
  packages/static-build/test/fixtures/middleman-v4/probes.json
  packages/static-build/test/fixtures/middleman-v4/source/images/.keep
  packages/static-build/test/fixtures/middleman-v4/source/index.html.erb
  packages/static-build/test/fixtures/middleman-v4/source/javascripts/site.js
  packages/static-build/test/fixtures/middleman-v4/source/layouts/layout.erb
  packages/static-build/test/fixtures/middleman-v4/source/pages/hello.html.erb
  packages/static-build/test/fixtures/middleman-v4/source/stylesheets/site.css.scss
Labels: area: tests, area: static-build, pr: automerge

#10684 [static-build] hexo-v6 fixture
  .changeset/twelve-jars-care.md
  packages/static-build/test/fixtures/hexo-v6/.github/dependabot.yml
  packages/static-build/test/fixtures/hexo-v6/.gitignore
  packages/static-build/test/fixtures/hexo-v6/_config.landscape.yml
  packages/static-build/test/fixtures/hexo-v6/_config.yml
  packages/static-build/test/fixtures/hexo-v6/package.json
  packages/static-build/test/fixtures/hexo-v6/probes.json
  packages/static-build/test/fixtures/hexo-v6/scaffolds/draft.md
  packages/static-build/test/fixtures/hexo-v6/scaffolds/page.md
  packages/static-build/test/fixtures/hexo-v6/scaffolds/post.md
  packages/static-build/test/fixtures/hexo-v6/source/_posts/hello-world.md
  packages/static-build/test/fixtures/hexo-v6/themes/.gitkeep
Labels: pr: automerge

#10675 [static-build] vite-v4
  .changeset/gentle-elephants-rule.md
  packages/static-build/test/fixtures/vite-v4/.gitignore
  packages/static-build/test/fixtures/vite-v4/index.html
  packages/static-build/test/fixtures/vite-v4/package-lock.json
  packages/static-build/test/fixtures/vite-v4/package.json
  packages/static-build/test/fixtures/vite-v4/probes.json
Labels: pr: automerge

#10691 [ci] update codeowners
  .changeset/honest-plums-reflect.md
  .github/CODEOWNERS
Labels: area: tests, pr: automerge

#10686 [static-build] storybook-v7
  .changeset/weak-days-divide.md
  packages/static-build/test/fixtures/storybook-v7/.gitignore
  packages/static-build/test/fixtures/storybook-v7/.storybook/main.ts
  packages/static-build/test/fixtures/storybook-v7/.storybook/preview.ts
  packages/static-build/test/fixtures/storybook-v7/README.md
  packages/static-build/test/fixtures/storybook-v7/app/favicon.ico
  packages/static-build/test/fixtures/storybook-v7/app/globals.css
  packages/static-build/test/fixtures/storybook-v7/app/layout.tsx
  packages/static-build/test/fixtures/storybook-v7/app/page.module.css
  packages/static-build/test/fixtures/storybook-v7/app/page.tsx
  packages/static-build/test/fixtures/storybook-v7/next.config.js
  packages/static-build/test/fixtures/storybook-v7/package-lock.json
  packages/static-build/test/fixtures/storybook-v7/package.json
  packages/static-build/test/fixtures/storybook-v7/probes.json
  packages/static-build/test/fixtures/storybook-v7/public/next.svg
  packages/static-build/test/fixtures/storybook-v7/public/vercel.svg
  packages/static-build/test/fixtures/storybook-v7/stories/Button.stories.ts
  packages/static-build/test/fixtures/storybook-v7/stories/Button.tsx
  packages/static-build/test/fixtures/storybook-v7/stories/Configure.mdx
  packages/static-build/test/fixtures/storybook-v7/stories/Header.stories.ts
  packages/static-build/test/fixtures/storybook-v7/stories/Header.tsx
  packages/static-build/test/fixtures/storybook-v7/stories/Page.stories.ts
  packages/static-build/test/fixtures/storybook-v7/stories/Page.tsx
  packages/static-build/test/fixtures/storybook-v7/stories/assets/accessibility.png
  packages/static-build/test/fixtures/storybook-v7/stories/assets/accessibility.svg
  packages/static-build/test/fixtures/storybook-v7/stories/assets/addon-library.png
  packages/static-build/test/fixtures/storybook-v7/stories/assets/assets.png
  packages/static-build/test/fixtures/storybook-v7/stories/assets/context.png
  packages/static-build/test/fixtures/storybook-v7/stories/assets/discord.svg
  packages/static-build/test/fixtures/storybook-v7/stories/assets/docs.png
  packages/static-build/test/fixtures/storybook-v7/stories/assets/figma-plugin.png
  packages/static-build/test/fixtures/storybook-v7/stories/assets/github.svg
  packages/static-build/test/fixtures/storybook-v7/stories/assets/share.png
  packages/static-build/test/fixtures/storybook-v7/stories/assets/styling.png
  packages/static-build/test/fixtures/storybook-v7/stories/assets/testing.png
  packages/static-build/test/fixtures/storybook-v7/stories/assets/theming.png
  packages/static-build/test/fixtures/storybook-v7/stories/assets/tutorials.svg
  packages/static-build/test/fixtures/storybook-v7/stories/assets/youtube.svg
  packages/static-build/test/fixtures/storybook-v7/stories/button.css
  packages/static-build/test/fixtures/storybook-v7/stories/header.css
  packages/static-build/test/fixtures/storybook-v7/stories/page.css
  packages/static-build/test/fixtures/storybook-v7/tsconfig.json
  packages/static-build/test/fixtures/storybook-v7/vercel.json
Labels: pr: automerge

#10690 [static-build] blitz-v2
  .changeset/polite-hornets-tie.md
  packages/static-build/test/fixtures/blitz-v2/.editorconfig
  packages/static-build/test/fixtures/blitz-v2/.env
  packages/static-build/test/fixtures/blitz-v2/.env.test
  packages/static-build/test/fixtures/blitz-v2/.gitignore
  packages/static-build/test/fixtures/blitz-v2/.husky/pre-commit
  packages/static-build/test/fixtures/blitz-v2/.npmrc
  packages/static-build/test/fixtures/blitz-v2/.prettierignore
  packages/static-build/test/fixtures/blitz-v2/README.md
  packages/static-build/test/fixtures/blitz-v2/next-env.d.ts
  packages/static-build/test/fixtures/blitz-v2/next.config.js
  packages/static-build/test/fixtures/blitz-v2/package-lock.json
  packages/static-build/test/fixtures/blitz-v2/package.json
  packages/static-build/test/fixtures/blitz-v2/probes.json
  packages/static-build/test/fixtures/blitz-v2/public/favicon.ico
  packages/static-build/test/fixtures/blitz-v2/public/logo.png
  packages/static-build/test/fixtures/blitz-v2/src/blitz-client.ts
  packages/static-build/test/fixtures/blitz-v2/src/core/layouts/Layout.tsx
  packages/static-build/test/fixtures/blitz-v2/src/pages/404.tsx
  packages/static-build/test/fixtures/blitz-v2/src/pages/_app.tsx
  packages/static-build/test/fixtures/blitz-v2/src/pages/_document.tsx
  packages/static-build/test/fixtures/blitz-v2/src/pages/index.tsx
  packages/static-build/test/fixtures/blitz-v2/src/styles/Home.module.css
  packages/static-build/test/fixtures/blitz-v2/src/styles/globals.css
  packages/static-build/test/fixtures/blitz-v2/test/setup.ts
  packages/static-build/test/fixtures/blitz-v2/tsconfig.json
  packages/static-build/test/fixtures/blitz-v2/vitest.config.ts
Labels: pr: automerge

#10688 [static-build] hydrogen-v2023
  .changeset/quick-pigs-sleep.md
  packages/static-build/test/fixtures/hydrogen-v2023/.gitignore
  packages/static-build/test/fixtures/hydrogen-v2023/.graphqlrc.yml
  packages/static-build/test/fixtures/hydrogen-v2023/README.md
  packages/static-build/test/fixtures/hydrogen-v2023/app/components/Aside.jsx
  packages/static-build/test/fixtures/hydrogen-v2023/app/components/Cart.jsx
  packages/static-build/test/fixtures/hydrogen-v2023/app/components/Footer.jsx
  packages/static-build/test/fixtures/hydrogen-v2023/app/components/Header.jsx
  packages/static-build/test/fixtures/hydrogen-v2023/app/components/Layout.jsx
  packages/static-build/test/fixtures/hydrogen-v2023/app/components/Search.jsx
  packages/static-build/test/fixtures/hydrogen-v2023/app/entry.client.jsx
  packages/static-build/test/fixtures/hydrogen-v2023/app/entry.server.jsx
  packages/static-build/test/fixtures/hydrogen-v2023/app/root.jsx
  packages/static-build/test/fixtures/hydrogen-v2023/app/routes/$.jsx
  packages/static-build/test/fixtures/hydrogen-v2023/app/routes/[robots.txt].jsx
  packages/static-build/test/fixtures/hydrogen-v2023/app/routes/[sitemap.xml].jsx
  packages/static-build/test/fixtures/hydrogen-v2023/app/routes/_index.jsx
  packages/static-build/test/fixtures/hydrogen-v2023/app/routes/account.$.jsx
  packages/static-build/test/fixtures/hydrogen-v2023/app/routes/account.addresses.jsx
  packages/static-build/test/fixtures/hydrogen-v2023/app/routes/account.jsx
  packages/static-build/test/fixtures/hydrogen-v2023/app/routes/account.orders.$id.jsx
  packages/static-build/test/fixtures/hydrogen-v2023/app/routes/account.orders._index.jsx
  packages/static-build/test/fixtures/hydrogen-v2023/app/routes/account.profile.jsx
  packages/static-build/test/fixtures/hydrogen-v2023/app/routes/account_.activate.$id.$activationToken.jsx
  packages/static-build/test/fixtures/hydrogen-v2023/app/routes/account_.login.jsx
  packages/static-build/test/fixtures/hydrogen-v2023/app/routes/account_.logout.jsx
  packages/static-build/test/fixtures/hydrogen-v2023/app/routes/account_.recover.jsx
  packages/static-build/test/fixtures/hydrogen-v2023/app/routes/account_.register.jsx
  packages/static-build/test/fixtures/hydrogen-v2023/app/routes/account_.reset.$id.$resetToken.jsx
  packages/static-build/test/fixtures/hydrogen-v2023/app/routes/api.predictive-search.jsx
  packages/static-build/test/fixtures/hydrogen-v2023/app/routes/blogs.$blogHandle.$articleHandle.jsx
  packages/static-build/test/fixtures/hydrogen-v2023/app/routes/blogs.$blogHandle._index.jsx
  packages/static-build/test/fixtures/hydrogen-v2023/app/routes/blogs._index.jsx
  packages/static-build/test/fixtures/hydrogen-v2023/app/routes/cart.$lines.jsx
  packages/static-build/test/fixtures/hydrogen-v2023/app/routes/cart.jsx
  packages/static-build/test/fixtures/hydrogen-v2023/app/routes/collections.$handle.jsx
  packages/static-build/test/fixtures/hydrogen-v2023/app/routes/collections._index.jsx
  packages/static-build/test/fixtures/hydrogen-v2023/app/routes/discount.$code.jsx
  packages/static-build/test/fixtures/hydrogen-v2023/app/routes/pages.$handle.jsx
  packages/static-build/test/fixtures/hydrogen-v2023/app/routes/policies.$handle.jsx
  packages/static-build/test/fixtures/hydrogen-v2023/app/routes/policies._index.jsx
  packages/static-build/test/fixtures/hydrogen-v2023/app/routes/products.$handle.jsx
  packages/static-build/test/fixtures/hydrogen-v2023/app/routes/search.jsx
  packages/static-build/test/fixtures/hydrogen-v2023/app/styles/app.css
  packages/static-build/test/fixtures/hydrogen-v2023/app/styles/reset.css
  packages/static-build/test/fixtures/hydrogen-v2023/app/utils.js
  packages/static-build/test/fixtures/hydrogen-v2023/jsconfig.json
  packages/static-build/test/fixtures/hydrogen-v2023/package-lock.json
  packages/static-build/test/fixtures/hydrogen-v2023/package.json
  packages/static-build/test/fixtures/hydrogen-v2023/probes.json
  packages/static-build/test/fixtures/hydrogen-v2023/public/favicon.svg
  packages/static-build/test/fixtures/hydrogen-v2023/remix.config.js
  packages/static-build/test/fixtures/hydrogen-v2023/server.js
Labels: pr: automerge

#10693 [static-build] scully-v2
  .changeset/six-items-compete.md
  packages/static-build/test/fixtures/scully-v2/.editorconfig
  packages/static-build/test/fixtures/scully-v2/.gitignore
  packages/static-build/test/fixtures/scully-v2/README.md
  packages/static-build/test/fixtures/scully-v2/angular.json
  packages/static-build/test/fixtures/scully-v2/package-lock.json
  packages/static-build/test/fixtures/scully-v2/package.json
  packages/static-build/test/fixtures/scully-v2/probes.json
  packages/static-build/test/fixtures/scully-v2/src/app/app-routing.module.ts
  packages/static-build/test/fixtures/scully-v2/src/app/app.component.css
  packages/static-build/test/fixtures/scully-v2/src/app/app.component.html
  packages/static-build/test/fixtures/scully-v2/src/app/app.component.spec.ts
  packages/static-build/test/fixtures/scully-v2/src/app/app.component.ts
  packages/static-build/test/fixtures/scully-v2/src/app/app.module.ts
  packages/static-build/test/fixtures/scully-v2/src/assets/.gitkeep
  packages/static-build/test/fixtures/scully-v2/src/favicon.ico
  packages/static-build/test/fixtures/scully-v2/src/index.html
  packages/static-build/test/fixtures/scully-v2/src/main.ts
  packages/static-build/test/fixtures/scully-v2/src/styles.css
  packages/static-build/test/fixtures/scully-v2/tsconfig.app.json
  packages/static-build/test/fixtures/scully-v2/tsconfig.json
  packages/static-build/test/fixtures/scully-v2/tsconfig.spec.json
  packages/static-build/test/fixtures/scully-v2/vercel.json
Labels: pr: automerge

#10700 Disable failing e2e test
  .changeset/spotty-geckos-remember.md
  packages/cli/test/integration-3.test.ts
Labels: area: tests, pr: automerge

#10694 [static-build] nuxt-v3
  .changeset/few-plums-joke.md
  packages/static-build/test/fixtures/nuxt-v3/.gitignore
  packages/static-build/test/fixtures/nuxt-v3/.npmrc
  packages/static-build/test/fixtures/nuxt-v3/README.md
  packages/static-build/test/fixtures/nuxt-v3/app.vue
  packages/static-build/test/fixtures/nuxt-v3/nuxt.config.ts
  packages/static-build/test/fixtures/nuxt-v3/package-lock.json
  packages/static-build/test/fixtures/nuxt-v3/package.json
  packages/static-build/test/fixtures/nuxt-v3/probes.json
  packages/static-build/test/fixtures/nuxt-v3/public/favicon.ico
  packages/static-build/test/fixtures/nuxt-v3/server/tsconfig.json
  packages/static-build/test/fixtures/nuxt-v3/tsconfig.json
Labels: pr: automerge

#10695 [static-build] stencil-v4
  .changeset/shaggy-squids-compare.md
  packages/static-build/test/fixtures/stencil-v4/.editorconfig
  packages/static-build/test/fixtures/stencil-v4/.gitignore
  packages/static-build/test/fixtures/stencil-v4/.prettierrc.json
  packages/static-build/test/fixtures/stencil-v4/LICENSE
  packages/static-build/test/fixtures/stencil-v4/package-lock.json
  packages/static-build/test/fixtures/stencil-v4/package.json
  packages/static-build/test/fixtures/stencil-v4/probes.json
  packages/static-build/test/fixtures/stencil-v4/readme.md
  packages/static-build/test/fixtures/stencil-v4/src/components.d.ts
  packages/static-build/test/fixtures/stencil-v4/src/components/my-component/my-component.css
  packages/static-build/test/fixtures/stencil-v4/src/components/my-component/my-component.e2e.ts
  packages/static-build/test/fixtures/stencil-v4/src/components/my-component/my-component.spec.ts
  packages/static-build/test/fixtures/stencil-v4/src/components/my-component/my-component.tsx
  packages/static-build/test/fixtures/stencil-v4/src/components/my-component/readme.md
  packages/static-build/test/fixtures/stencil-v4/src/index.html
  packages/static-build/test/fixtures/stencil-v4/src/index.ts
  packages/static-build/test/fixtures/stencil-v4/src/utils/utils.spec.ts
  packages/static-build/test/fixtures/stencil-v4/src/utils/utils.ts
  packages/static-build/test/fixtures/stencil-v4/stencil.config.ts
  packages/static-build/test/fixtures/stencil-v4/tsconfig.json
Labels: pr: automerge

#10696 [static-build] ember-v5
  .changeset/cyan-seas-pretend.md
  packages/static-build/test/fixtures/ember-v5/.editorconfig
  packages/static-build/test/fixtures/ember-v5/.ember-cli
  packages/static-build/test/fixtures/ember-v5/.github/workflows/ci.yml
  packages/static-build/test/fixtures/ember-v5/.gitignore
  packages/static-build/test/fixtures/ember-v5/.prettierignore
  packages/static-build/test/fixtures/ember-v5/.prettierrc.js
  packages/static-build/test/fixtures/ember-v5/.stylelintignore
  packages/static-build/test/fixtures/ember-v5/.stylelintrc.js
  packages/static-build/test/fixtures/ember-v5/.template-lintrc.js
  packages/static-build/test/fixtures/ember-v5/.watchmanconfig
  packages/static-build/test/fixtures/ember-v5/README.md
  packages/static-build/test/fixtures/ember-v5/app/app.js
  packages/static-build/test/fixtures/ember-v5/app/components/.gitkeep
  packages/static-build/test/fixtures/ember-v5/app/controllers/.gitkeep
  packages/static-build/test/fixtures/ember-v5/app/helpers/.gitkeep
  packages/static-build/test/fixtures/ember-v5/app/index.html
  packages/static-build/test/fixtures/ember-v5/app/models/.gitkeep
  packages/static-build/test/fixtures/ember-v5/app/router.js
  packages/static-build/test/fixtures/ember-v5/app/routes/.gitkeep
  packages/static-build/test/fixtures/ember-v5/app/styles/app.css
  packages/static-build/test/fixtures/ember-v5/app/templates/application.hbs
  packages/static-build/test/fixtures/ember-v5/config/ember-cli-update.json
  packages/static-build/test/fixtures/ember-v5/config/environment.js
  packages/static-build/test/fixtures/ember-v5/config/optional-features.json
  packages/static-build/test/fixtures/ember-v5/config/targets.js
  packages/static-build/test/fixtures/ember-v5/ember-cli-build.js
  packages/static-build/test/fixtures/ember-v5/package-lock.json
  packages/static-build/test/fixtures/ember-v5/package.json
  packages/static-build/test/fixtures/ember-v5/probes.json
  packages/static-build/test/fixtures/ember-v5/public/robots.txt
  packages/static-build/test/fixtures/ember-v5/testem.js
  packages/static-build/test/fixtures/ember-v5/tests/helpers/index.js
  packages/static-build/test/fixtures/ember-v5/tests/index.html
  packages/static-build/test/fixtures/ember-v5/tests/integration/.gitkeep
  packages/static-build/test/fixtures/ember-v5/tests/test-helper.js
  packages/static-build/test/fixtures/ember-v5/tests/unit/.gitkeep
Labels: pr: automerge

#10683 [static-build] add angular v16
  .changeset/sharp-garlics-cheer.md
  packages/static-build/test/fixtures/angular-v16/.editorconfig
  packages/static-build/test/fixtures/angular-v16/.gitignore
  packages/static-build/test/fixtures/angular-v16/README.md
  packages/static-build/test/fixtures/angular-v16/angular.json
  packages/static-build/test/fixtures/angular-v16/package-lock.json
  packages/static-build/test/fixtures/angular-v16/package.json
  packages/static-build/test/fixtures/angular-v16/probes.json
  packages/static-build/test/fixtures/angular-v16/src/app/app.component.css
  packages/static-build/test/fixtures/angular-v16/src/app/app.component.html
  packages/static-build/test/fixtures/angular-v16/src/app/app.component.spec.ts
  packages/static-build/test/fixtures/angular-v16/src/app/app.component.ts
  packages/static-build/test/fixtures/angular-v16/src/app/app.module.ts
  packages/static-build/test/fixtures/angular-v16/src/assets/.gitkeep
  packages/static-build/test/fixtures/angular-v16/src/favicon.ico
  packages/static-build/test/fixtures/angular-v16/src/index.html
  packages/static-build/test/fixtures/angular-v16/src/main.ts
  packages/static-build/test/fixtures/angular-v16/src/styles.css
  packages/static-build/test/fixtures/angular-v16/tsconfig.app.json
  packages/static-build/test/fixtures/angular-v16/tsconfig.json
  packages/static-build/test/fixtures/angular-v16/tsconfig.spec.json
Labels: pr: automerge

#10698 Remove svelte v5 fixture
  .changeset/funny-dogs-press.md
  packages/static-build/test/fixtures/svelte-v5/.gitignore
  packages/static-build/test/fixtures/svelte-v5/.npmrc
  packages/static-build/test/fixtures/svelte-v5/package-lock.json
  packages/static-build/test/fixtures/svelte-v5/package.json
  packages/static-build/test/fixtures/svelte-v5/probes.json
  packages/static-build/test/fixtures/svelte-v5/src/app.d.ts
  packages/static-build/test/fixtures/svelte-v5/src/app.html
  packages/static-build/test/fixtures/svelte-v5/src/lib/index.js
  packages/static-build/test/fixtures/svelte-v5/src/routes/+page.svelte
  packages/static-build/test/fixtures/svelte-v5/svelte.config.js
  packages/static-build/test/fixtures/svelte-v5/tsconfig.json
  packages/static-build/test/fixtures/svelte-v5/vite.config.ts
Labels: pr: automerge

#10699 [cli] Add lockfile mistakenly missed due to gitignore
  .changeset/violet-ducks-learn.md
  packages/cli/test/dev/fixtures/13-preact-node/.gitignore
  packages/cli/test/dev/fixtures/13-preact-node/package-lock.json
Labels: area: cli, area: tests, pr: automerge

#10495 [routing-utils] Adds support for `statusCode` property on `rewrites`
  .changeset/healthy-cats-lie.md
  packages/cli/src/util/dev/server.ts
  packages/cli/test/dev/fixtures/test-rewrites/vercel.json
  packages/cli/test/dev/integration-2.test.ts
  packages/routing-utils/src/schemas.ts
  packages/routing-utils/src/superstatic.ts
  packages/routing-utils/src/types.ts
  packages/routing-utils/test/superstatic.spec.ts
Labels: pr: automerge

#10697 [cli] update env var validation rule to allow name start with underscore
  .changeset/purple-toys-join.md
  packages/cli/src/util/dev/server.ts
  packages/cli/test/dev/fixtures/invalid-env-var-name/vercel.json
  packages/cli/test/dev/integration-2.test.ts
Labels: area: cli, pr: automerge

#10706 [static-build] update astro-v2 fixture
  .changeset/twelve-mice-check.md
  packages/static-build/test/fixtures/astro-v2/.gitignore
  packages/static-build/test/fixtures/astro-v2/package-lock.json
  packages/static-build/test/fixtures/astro-v2/package.json
Labels: pr: automerge

#10708 [next] fix `build` in appDir on windows
  .changeset/hungry-mangos-pump.md
  packages/next/src/index.ts
  packages/next/src/utils.ts
  packages/next/test/unit/utils.test.ts
Labels: area: next, pr: automerge

#10703 [cli] autoconfirm in CI to domain buys
  .changeset/lucky-baboons-divide.md
  packages/cli/src/commands/domains/buy.ts
  packages/cli/test/integration-3.test.ts
Labels: area: cli, area: tests, pr: automerge

#10720 [cli] Migrate 30-next-image-optimization fixture to use npm install
  .changeset/eleven-ads-look.md
  packages/cli/test/dev/fixtures/30-next-image-optimization/package-lock.json
Labels: area: cli, area: tests, pr: automerge

#10729 Add Zero Config Team to 'edge' codeowners
  .changeset/yellow-snails-burn.md
  .github/CODEOWNERS
Labels: pr: automerge

#10727 [static-build] remove old gatsby tests and merge into new gatsby-v2
  .changeset/modern-beans-fly.md
  packages/static-build/test/fixtures/10-gatsby-without-build-script/.gitignore
  packages/static-build/test/fixtures/10-gatsby-without-build-script/.prettierrc
  packages/static-build/test/fixtures/10-gatsby-without-build-script/LICENSE
  packages/static-build/test/fixtures/10-gatsby-without-build-script/README.md
  packages/static-build/test/fixtures/10-gatsby-without-build-script/gatsby-browser.js
  packages/static-build/test/fixtures/10-gatsby-without-build-script/gatsby-config.js
  packages/static-build/test/fixtures/10-gatsby-without-build-script/gatsby-node.js
  packages/static-build/test/fixtures/10-gatsby-without-build-script/gatsby-ssr.js
  packages/static-build/test/fixtures/10-gatsby-without-build-script/package.json
  packages/static-build/test/fixtures/10-gatsby-without-build-script/probes.json
  packages/static-build/test/fixtures/10-gatsby-without-build-script/src/components/header.js
  packages/static-build/test/fixtures/10-gatsby-without-build-script/src/components/image.js
  packages/static-build/test/fixtures/10-gatsby-without-build-script/src/components/layout.css
  packages/static-build/test/fixtures/10-gatsby-without-build-script/src/components/layout.js
  packages/static-build/test/fixtures/10-gatsby-without-build-script/src/components/seo.js
  packages/static-build/test/fixtures/10-gatsby-without-build-script/src/images/gatsby-astronaut.png
  packages/static-build/test/fixtures/10-gatsby-without-build-script/src/images/gatsby-icon.png
  packages/static-build/test/fixtures/10-gatsby-without-build-script/src/pages/404.js
  packages/static-build/test/fixtures/10-gatsby-without-build-script/src/pages/index.js
  packages/static-build/test/fixtures/10-gatsby-without-build-script/src/pages/page-2.js
  packages/static-build/test/fixtures/10-gatsby-without-build-script/yarn.lock
  packages/static-build/test/fixtures/10-gatsby/.gitignore
  packages/static-build/test/fixtures/10-gatsby/.prettierrc
  packages/static-build/test/fixtures/10-gatsby/LICENSE
  packages/static-build/test/fixtures/10-gatsby/README.md
  packages/static-build/test/fixtures/10-gatsby/gatsby-browser.js
  packages/static-build/test/fixtures/10-gatsby/gatsby-config.js
  packages/static-build/test/fixtures/10-gatsby/gatsby-node.js
  packages/static-build/test/fixtures/10-gatsby/gatsby-ssr.js
  packages/static-build/test/fixtures/10-gatsby/package-lock.json
  packages/static-build/test/fixtures/10-gatsby/package.json
  packages/static-build/test/fixtures/10-gatsby/probes.json
  packages/static-build/test/fixtures/10-gatsby/src/components/header.js
  packages/static-build/test/fixtures/10-gatsby/src/components/image.js
  packages/static-build/test/fixtures/10-gatsby/src/components/layout.css
  packages/static-build/test/fixtures/10-gatsby/src/components/layout.js
  packages/static-build/test/fixtures/10-gatsby/src/components/seo.js
  packages/static-build/test/fixtures/10-gatsby/src/images/gatsby-astronaut.png
  packages/static-build/test/fixtures/10-gatsby/src/images/gatsby-icon.png
  packages/static-build/test/fixtures/10-gatsby/src/pages/404.js
  packages/static-build/test/fixtures/10-gatsby/src/pages/index.js
  packages/static-build/test/fixtures/10-gatsby/src/pages/page-2.js
  packages/static-build/test/fixtures/gatsby-v2/probes.json
Labels: pr: automerge

#10740 Update to run Next.js integration with Node.js v18
  .changeset/shaggy-bears-visit.md
  .github/workflows/test.yml
  packages/next/package.json
  packages/next/test/fixtures/00-app-dir-edge/package.json
  packages/next/test/integration/integration-1.test.js
  packages/next/test/integration/integration-2.test.js
  packages/next/test/integration/legacy/integration-legacy.test.js
  turbo.json
  utils/chunk-tests.js
Labels: area: tests, pr: automerge

#10734 Fix RSC prefetch for index route with catch-all
  .changeset/lucky-dolphins-tease.md
  packages/next/src/server-build.ts
  packages/next/test/fixtures/00-app-dir-root-catch-all/app/[[...slug]]/page.js
  packages/next/test/fixtures/00-app-dir-root-catch-all/app/layout.js
  packages/next/test/fixtures/00-app-dir-root-catch-all/index.test.js
  packages/next/test/fixtures/00-app-dir-root-catch-all/package.json
  packages/next/test/fixtures/00-app-dir-root-catch-all/vercel.json
  packages/next/test/fixtures/00-app-dir/app/catch-all/[[...slug]]/page.js
  packages/next/test/fixtures/00-app-dir/vercel.json
Labels: pr: automerge

#10742 [python] Mock Python for tests running on machines without Python actually installed
  .changeset/early-ways-bow.md
  packages/python/test/unit.test.ts
Labels: area: tests, pr: automerge

#10754 [examples] Migrate Sanity to use npm over yarn
  .changeset/spotty-hats-promise.md
  examples/sanity/package-lock.json
  examples/sanity/yarn.lock
Labels: area: examples, area: tests, pr: automerge

#10756 [next] replace `next export` with `output: export` in tests
  .changeset/modern-walls-refuse.md
  packages/next/test/fixtures/00-trailing-slash-add-export/next.config.js
  packages/next/test/fixtures/00-trailing-slash-add-export/package.json
  packages/next/test/fixtures/10-export-cache-headers/next.config.js
  packages/next/test/fixtures/10-export-cache-headers/package.json
  packages/next/test/fixtures/11-export-clean-urls/next.config.js
  packages/next/test/fixtures/11-export-clean-urls/package.json
  packages/next/test/fixtures/13-export-custom-routes/next.config.js
  packages/next/test/fixtures/13-export-custom-routes/package.json
Labels: area: tests, pr: automerge

#10752 [examples][tests] Update fixture test names to be concretely named
  .changeset/many-eels-care.md
  examples/__tests__/integration/angular.test.ts
  examples/__tests__/integration/astro.test.ts
  examples/__tests__/integration/blitzjs.test.ts
  examples/__tests__/integration/brunch.test.ts
  examples/__tests__/integration/create-react-app.test.ts
  examples/__tests__/integration/docusaurus-2.test.ts
  examples/__tests__/integration/docusaurus.test.ts
  examples/__tests__/integration/dojo.test.ts
  examples/__tests__/integration/eleventy.test.ts
  examples/__tests__/integration/ember.test.ts
  examples/__tests__/integration/gatsby.test.ts
  examples/__tests__/integration/gridsome.test.ts
  examples/__tests__/integration/hexo.test.ts
  examples/__tests__/integration/hugo.test.ts
  examples/__tests__/integration/hydrogen-2.test.ts
  examples/__tests__/integration/hydrogen.test.ts
  examples/__tests__/integration/ionic-angular.test.ts
  examples/__tests__/integration/ionic-react.test.ts
  examples/__tests__/integration/jekyll.test.ts
  examples/__tests__/integration/middleman.test.ts
  examples/__tests__/integration/nextjs.test.ts
  examples/__tests__/integration/node_modules.test.ts
  examples/__tests__/integration/nuxtjs.test.ts
  examples/__tests__/integration/parcel.test.ts
  examples/__tests__/integration/polymer.test.ts
  examples/__tests__/integration/preact.test.ts
  examples/__tests__/integration/redwoodjs.test.ts
  examples/__tests__/integration/remix.test.ts
  examples/__tests__/integration/saber.test.ts
  examples/__tests__/integration/sanity.test.ts
  examples/__tests__/integration/sapper.test.ts
  examples/__tests__/integration/scully.test.ts
  examples/__tests__/integration/solidstart.test.ts
  examples/__tests__/integration/stencil.test.ts
  examples/__tests__/integration/storybook.test.ts
  examples/__tests__/integration/svelte.test.ts
  examples/__tests__/integration/sveltekit-1.test.ts
  examples/__tests__/integration/sveltekit.test.ts
  examples/__tests__/integration/umijs.test.ts
  examples/__tests__/integration/vite.test.ts
  examples/__tests__/integration/vitepress.test.ts
  examples/__tests__/integration/vue.test.ts
  examples/__tests__/integration/vuepress.test.ts
  examples/__tests__/integration/zola.test.ts
Labels: area: examples, area: tests, pr: automerge

#10751 [gatsby-plugin-vercel-builder] Fix nested SSR routes
  .changeset/happy-wolves-exist.md
  packages/gatsby-plugin-vercel-builder/jest.config.js
  packages/gatsby-plugin-vercel-builder/package.json
  packages/gatsby-plugin-vercel-builder/src/handlers/build.ts
  packages/gatsby-plugin-vercel-builder/src/helpers/functions.ts
  packages/gatsby-plugin-vercel-builder/templates/ssr-handler.js
  packages/gatsby-plugin-vercel-builder/templates/utils.ts
  packages/gatsby-plugin-vercel-builder/test/tsconfig.json
  packages/gatsby-plugin-vercel-builder/test/unit.get-page-name.test.ts
  packages/static-build/test/fixtures/gatsby-v5-pathPrefix/probes.json
  packages/static-build/test/fixtures/gatsby-v5-pathPrefix/src/pages/foo/bar/ssr.js
  packages/static-build/test/fixtures/gatsby-v5/probes.json
  packages/static-build/test/fixtures/gatsby-v5/src/pages/foo/bar/ssr.js
  pnpm-lock.yaml
Labels: pr: automerge

#10755 [examples] Update Saber to use npm registry
  .changeset/cold-cougars-press.md
  examples/saber/package-lock.json
  examples/saber/yarn.lock
Labels: area: examples, pr: automerge

#10766 [examples] Migrate hydrogen example from yarn.lock to package-lock.json
  .changeset/lazy-waves-sing.md
  examples/hydrogen/package-lock.json
  examples/hydrogen/yarn.lock
Labels: area: examples, pr: automerge

#10773 [cli] Debug log load user exceptions
  .changeset/angry-geckos-crash.md
  packages/cli/src/index.ts
Labels: area: cli, pr: automerge

#10779 Rework prefetch route handling
  .changeset/tricky-rules-sin.md
  packages/next/src/server-build.ts
  packages/next/src/utils.ts
  packages/next/test/fixtures/00-app-dir-root-catch-all/app/[[...slug]]/page.js
  packages/next/test/fixtures/00-app-dir-root-catch-all/app/nested/[[...slug]]/page.js
  packages/next/test/fixtures/00-app-dir-root-catch-all/vercel.json
  packages/next/test/integration/integration-1.test.js
  packages/next/test/integration/legacy/integration-legacy.test.js
  packages/next/test/unit/utils.test.ts
Labels: area: next, pr: automerge

#10764 [error-utils] use Node.js `util.types.isNativeError` for `isError` method
  .changeset/purple-crews-type.md
  packages/error-utils/src/index.ts
Labels: pr: automerge

#10789 [error-utils] fix jest coverage issue
  .changeset/mean-tips-provide.md
  packages/error-utils/tsconfig.json
Labels: pr: automerge
