Repository vercel/vercel, pull requests merged in 2023-05, with the labels that each got.

#9883 [fs-detectors] Add `disableRootMiddleware`, bypass `ignoreRuntimes` for root-level "middleware" files
  packages/frameworks/src/frameworks.ts
  packages/frameworks/src/types.ts
  packages/fs-detectors/src/detect-builders.ts
  packages/fs-detectors/test/unit.builds-and-routes-detector.test.ts
Labels: semver: patch, area: fs-detectors, pr: automerge

#9888 [remix] Suppress warnings when reading config
  packages/remix/src/utils.ts
Labels: semver: patch, area: remix, pr: automerge

#9894 [remix] Use `debug()` for warnings when reading config file
  packages/remix/src/utils.ts
Labels: semver: patch, area: remix, pr: automerge

#9898 [frameworks] Add `getOutputDirName` to Storybook definition
  packages/frameworks/src/frameworks.ts
Labels: area: frameworks, semver: patch, pr: automerge

#9899 [node] Explicitly set 'set-cookie' header
  packages/node/src/dev-server.mts
Labels: area: node, semver: patch, pr: automerge

#9900 [frameworks] validate getOutputDirName and other missing values on framework entries
  packages/frameworks/test/frameworks.unit.test.ts
Labels: area: frameworks, pr: automerge, semver: none

#9880 [cli] Add support for `HTTPS_PROXY` env var
  packages/cli/package.json
  packages/cli/src/index.ts
  packages/cli/src/util/client.ts
  packages/cli/src/util/deploy/process-deployment.ts
  packages/cli/src/util/index.ts
  packages/cli/test/mocks/client.ts
  packages/cli/test/unit/util/client.test.ts
  packages/client/src/check-deployment-status.ts
  packages/client/src/deploy.ts
  packages/client/src/types.ts
  packages/client/src/upload.ts
  pnpm-lock.yaml
Labels: area: cli, semver: minor, pr: automerge

#9907 [cli][node] upgrade `async-listen` to 3.0.0
  packages/cli/package.json
  packages/cli/src/util/dev/server.ts
  packages/cli/src/util/login/oauth.ts
  packages/cli/test/dev/integration-1.test.ts
  packages/cli/test/mocks/client.ts
  packages/cli/test/unit/util/client.test.ts
  packages/cli/test/unit/util/error.test.ts
  packages/node/package.json
  packages/node/src/dev-server.mts
  packages/node/src/serverless-functions/serverless-handler.mts
  pnpm-lock.yaml
Labels: area: node, area: cli, semver: patch

#9912 [cli] refactor help output around default and deploy commands
  packages/cli/src/args.ts
  packages/cli/src/commands/deploy/args.ts
  packages/cli/src/commands/init/index.ts
  packages/cli/src/commands/init/init.ts
  packages/cli/src/index.ts
  packages/cli/src/util/arg-common.ts
Labels: area: cli, semver: minor, pr: automerge

#9917 [cli] rename global options in help output
  packages/cli/src/args.ts
Labels: area: cli, semver: patch, pr: automerge

#9916 [tests] Add test for set-cookie with multiple cookies
  packages/node/test/dev-fixtures/multiple-cookies.ts
  packages/node/test/unit/dev.test.ts
Labels: area: tests, pr: automerge, semver: none

#9800 [cli] Add support for Vercel CLI Extensions
  packages/cli/package.json
  packages/cli/src/index.ts
  packages/cli/src/util/client.ts
  packages/cli/src/util/extension/exec.ts
  packages/cli/src/util/extension/proxy.ts
  packages/cli/test/fixtures/e2e/cli-extension-whoami/bin.js
  packages/cli/test/fixtures/e2e/cli-extension-whoami/package.json
  packages/cli/test/fixtures/e2e/cli-extension/package-lock.json
  packages/cli/test/fixtures/e2e/cli-extension/package.json
  packages/cli/test/integration-3.test.ts
  pnpm-lock.yaml
Labels: area: cli, semver: minor, pr: automerge

#9914 Use `changesets` instead of `lerna`
  .changeset/README.md
  .changeset/config.json
  .github/workflows/publish.yml
  .github/workflows/release.yml
  package.json
  pnpm-lock.yaml
  utils/changelog.js
  utils/changelog/filter.js
  utils/changelog/group.js
  utils/changelog/parse.js
  utils/publish.sh
  utils/update-canary-tag.js
  utils/update-legacy-name.js
Labels: area: tests, pr: automerge, semver: none

#9932 Create release PR as "Vercel Bot" and remove `CHANGELOG.md` files
  .github/workflows/release.yml
  package.json
Labels: area: tests, pr: automerge, semver: none

#9933 Use Svelte's changelog generator and don't delete `CHANGELOG.md`
  .changeset/config.json
  package.json
Labels: area: tests, pr: automerge, semver: none

#9934 Add `@svitejs/changesets-changelog-github-compact` to package.json
  package.json
  pnpm-lock.yaml
Labels: area: tests, semver: none

#9936 Add `id-token: write` permissions to enable npm publish provenance
  .github/workflows/release.yml
Labels: area: tests, pr: automerge, semver: none

#9938 [tests] make prettier ignore .changeset
  .prettierignore
Labels: area: tests, pr: automerge, semver: none

#9928 [cli] remove `vc rollback` beta label
  .changeset/moody-apples-raise.md
  packages/cli/src/args.ts
  packages/cli/src/index.ts
Labels: area: cli, semver: patch, pr: automerge

#9949 [cli] Sort keys in `vc env pull`
  .changeset/quiet-avocados-pretend.md
  packages/cli/src/commands/env/pull.ts
  packages/cli/test/mocks/project.ts
  packages/cli/test/unit/commands/env.test.ts
Labels: area: cli, semver: patch, pr: automerge

#9951 Update README
  README.md
  packages/cli/README.md
Labels: area: tests, pr: automerge, semver: none

#9958 Remove "Required PR Label" workflow
  .github/workflows/required-pr-label.yml
Labels: pr: automerge

#9969 fix deploy from local
  packages/node/build.js
  utils/pack.ts
Labels: pr: automerge, semver: none

#9959 fix release script
  utils/update-latest-release.js
Labels: pr: automerge

#9972 Add changeset for `@remix-run/dev` updater GH Action
  utils/update-remix-run-dev.js
Labels: pr: automerge

#9974 [next] Update handling for react prebundled flag
  .changeset/little-readers-flash.md
  packages/next/src/server-build.ts
  packages/next/src/server-launcher.ts
  packages/next/src/utils.ts
  packages/next/test/fixtures/00-app-dir/components/more-data.js
  packages/next/test/fixtures/00-app-dir/data-context.js
  packages/next/test/fixtures/00-app-dir/pages/blog-ssr/[slug].js
  packages/next/test/fixtures/00-app-dir/vercel.json
  packages/next/test/integration/integration-1.test.js
Labels: pr: automerge

#9976 Deprecate Node.js 14.x and 16.x with warning
  .changeset/shaggy-chefs-invent.md
  packages/build-utils/src/fs/node-version.ts
  packages/build-utils/test/pkg-engine-node-exact/package.json
  packages/build-utils/test/pkg-engine-node/package.json
  packages/build-utils/test/unit.test.ts
Labels: pr: automerge

#9975 ensure cleanup after the gatsby plugin runs
  .changeset/odd-elephants-reply.md
  packages/static-build/src/index.ts
  packages/static-build/src/utils/gatsby.ts
  packages/static-build/test/gatsby.test.ts
Labels: pr: automerge

#9989 [next] Ensure app functions are detected/separated properly
  .changeset/tiny-melons-bow.md
  packages/next/src/server-build.ts
  packages/next/test/fixtures/00-app-dir/app/(rootonly)/dashboard/hello/page.js
  packages/next/test/fixtures/00-app-dir/app/page.js
  packages/next/test/fixtures/00-app-dir/vercel.json
Labels: pr: automerge

#9990 add repo details for packages that are missing it
  .changeset/lemon-trees-glow.md
  packages/frameworks/package.json
  packages/gatsby-plugin-vercel-builder/package.json
Labels: pr: automerge

#8931 [cli] Add `vc link --repo` flag
  .changeset/fuzzy-tomatoes-develop.md
  packages/cli/src/commands/link/index.ts
  packages/cli/src/util/link/add-to-gitignore.ts
  packages/cli/src/util/link/repo.ts
  packages/cli/src/util/projects/link.ts
  packages/cli/test/unit/util/link/repo.test.ts
Labels: area: cli, semver: minor, pr: automerge

#9979 clarify next.js dupe api directory warning
  .changeset/slow-monkeys-taste.md
  packages/fs-detectors/src/detect-builders.ts
  packages/fs-detectors/test/unit.builds-and-routes-detector.test.ts
Labels: pr: automerge

#10003 Fix promoting CLI release to "latest" GH Release
  .github/workflows/release.yml
  utils/update-latest-release.js
Labels: pr: automerge

#10001 [examples] Update "vue" template to use Node 18
  examples/vue/package.json
  examples/vue/yarn.lock
Labels: area: frameworks, pr: automerge

#9807 [cli] Remove `--platform-version` global common arg
  .changeset/ninety-chefs-heal.md
  packages/cli/src/util/arg-common.ts
  packages/cli/test/integration-3.test.ts
Labels: area: cli, semver: major, pr: automerge

#9956 [cli] New `vc redeploy` command
  .changeset/orange-zebras-return.md
  internals/types/index.d.ts
  packages/cli/src/args.ts
  packages/cli/src/commands/deploy/index.ts
  packages/cli/src/commands/index.ts
  packages/cli/src/commands/redeploy.ts
  packages/cli/src/commands/rollback.ts
  packages/cli/src/index.ts
  packages/cli/src/util/deploy/get-deployment-by-id-or-url.ts
  packages/cli/src/util/deploy/print-deployment-status.ts
  packages/cli/src/util/get-deployment.ts
  packages/cli/src/util/rollback/request-rollback.ts
  packages/cli/test/fixtures/unit/commands/redeploy/simple-static/index.html
  packages/cli/test/mocks/project.ts
  packages/cli/test/unit/commands/env.test.ts
  packages/cli/test/unit/commands/redeploy.test.ts
  packages/cli/test/unit/commands/rollback.test.ts
  packages/client/src/index.ts
Labels: area: cli, area: client, semver: minor, pr: automerge

#10005 Remove `pnpm bootstrap` from contributing instructions
  .github/CONTRIBUTING.md
Labels: pr: automerge

#9892 [cli] Change `vc env pull` default output file to `.env.local`
  .changeset/neat-otters-happen.md
  errors/missing-env-file.md
  examples/sanity/.env.local.template
  packages/cli/src/commands/env/index.ts
  packages/cli/src/commands/env/pull.ts
  packages/cli/test/fixtures/unit/vercel-env-pull-delta-corrupt/.env.local
  packages/cli/test/fixtures/unit/vercel-env-pull-delta-no-changes/.env.local
  packages/cli/test/fixtures/unit/vercel-env-pull-delta-quotes/.env.local
  packages/cli/test/fixtures/unit/vercel-env-pull-delta/.env.local
  packages/cli/test/integration-1.test.ts
  packages/cli/test/unit/commands/env.test.ts
Labels: area: cli, semver: major, pr: automerge

#10002 Sync repo package versions
  examples/package.json
  internals/constants/package.json
  internals/get-package-json/package.json
  internals/tsconfig/package.json
  internals/types/package.json
  packages/cli/package.json
  packages/node/package.json
  pnpm-lock.yaml
Labels: pr: automerge

#9967 [cli] Fix `vercel git connect` command when passing a URL parameter
  .changeset/thick-colts-jam.md
  packages/cli/src/commands/git/connect.ts
  packages/cli/test/unit/commands/git.test.ts
Labels: pr: automerge

#10008 Update to latest version of `patrickedqvist/wait-for-vercel-preview`
  .github/workflows/test.yml
Labels: pr: automerge

#10009 [examples] Update `solid-js` template to use Node 18
  examples/solidstart/package.json
  examples/solidstart/yarn.lock
Labels: area: frameworks, pr: automerge

#9836 [cli] implement `vc deploy --prod --skip-domain`
  .changeset/late-mangos-sip.md
  packages/cli/src/commands/deploy/index.ts
  packages/cli/src/util/index.ts
  packages/cli/src/util/link/setup-and-link.ts
  packages/cli/test/fixtures/unit/commands/deploy/static/.gitignore
  packages/cli/test/fixtures/unit/commands/deploy/static/.vercel/project.json
  packages/cli/test/fixtures/unit/commands/deploy/static/index.html
  packages/cli/test/fixtures/unit/commands/deploy/static/style.css
  packages/cli/test/unit/commands/deploy.test.ts
  packages/client/src/types.ts
Labels: area: cli, semver: minor, pr: automerge

#10021 [cli] Add `expect` dev dependency to fix type error in `toOutput`
  packages/cli/package.json
  packages/cli/test/mocks/matchers/to-output.ts
  pnpm-lock.yaml
Labels: pr: automerge

#10022 Use `pnpm publish -r` to publish packages
  .github/workflows/release.yml
  package.json
Labels: pr: automerge

#10012 [examples] Update `preact` template to use Node 18
  examples/preact/package.json
  examples/preact/yarn.lock
Labels: area: frameworks

#9889 [next] Fix `functions` config with App Router
  .changeset/funny-garlics-refuse.md
  packages/next/src/utils.ts
  packages/next/test/fixtures/00-app-dir/vercel.json
  packages/next/test/integration/integration-1.test.js
Labels: semver: patch, area: next, pr: automerge

#10015 [next] Pass `pageExtensions` data to `apiLambdaGroups`
  .changeset/orange-ears-repeat.md
  packages/next/src/server-build.ts
  packages/next/src/utils.ts
Labels: semver: patch, area: next, pr: automerge

#10032 Revert "Use `pnpm publish -r` to publish packages (#10022)"
  .github/workflows/release.yml
  package.json
Labels: pr: automerge

#10031 [cli] Add `client.cwd` to unify all working directory related logic
  .changeset/thin-planets-unite.md
  packages/cli/src/commands/build.ts
  packages/cli/src/commands/env/index.ts
  packages/cli/src/commands/link/index.ts
  packages/cli/src/commands/promote/index.ts
  packages/cli/src/commands/rollback/index.ts
  packages/cli/src/index.ts
  packages/cli/src/util/client.ts
  packages/cli/test/mocks/client.ts
  packages/cli/test/unit/commands/build/index.test.ts
  packages/cli/test/unit/commands/deploy.test.ts
  packages/cli/test/unit/commands/env.test.ts
  packages/cli/test/unit/commands/git.test.ts
  packages/cli/test/unit/commands/link.test.ts
  packages/cli/test/unit/commands/list.test.ts
  packages/cli/test/unit/commands/promote.test.ts
  packages/cli/test/unit/commands/rollback.test.ts
  packages/cli/test/unit/util/deploy/create-git-meta.test.ts
Labels: pr: automerge

#10033 [cli] Fix `link` subcommand unit tests on Windows
  packages/cli/test/helpers/setup-unit-fixture.ts
  packages/cli/test/unit/commands/link.test.ts
Labels: pr: automerge

#10044 Use `pnpm publish -r` and `changeset tag` to publish packages
  .github/workflows/release.yml
  package.json
Labels: pr: automerge

#10013 [cli] Add repo linking support for `deploy` command
  .changeset/bright-ducks-matter.md
  internals/types/index.d.ts
  packages/cli/src/commands/deploy/index.ts
  packages/cli/src/commands/git/connect.ts
  packages/cli/src/commands/git/index.ts
  packages/cli/src/commands/list.ts
  packages/cli/src/util/deploy/create-deploy.ts
  packages/cli/src/util/deploy/process-deployment.ts
  packages/cli/src/util/index.ts
  packages/cli/src/util/link/repo.ts
  packages/cli/src/util/link/setup-and-link.ts
  packages/cli/src/util/projects/get-project-by-cwd-or-link.ts
  packages/cli/src/util/projects/link.ts
  packages/cli/src/util/validate-paths.ts
  packages/cli/test/fixtures/unit/commands/deploy/monorepo-static/.gitignore
  packages/cli/test/fixtures/unit/commands/deploy/monorepo-static/.vercel/repo.json
  packages/cli/test/fixtures/unit/commands/deploy/monorepo-static/app/index.html
  packages/cli/test/fixtures/unit/commands/deploy/monorepo-static/app/style.css
  packages/cli/test/fixtures/unit/monorepo-link/.gitignore
  packages/cli/test/fixtures/unit/monorepo-link/.vercel/repo.json
  packages/cli/test/integration-3.test.ts
  packages/cli/test/unit/commands/deploy.test.ts
  packages/cli/test/unit/util/projects/link.test.ts
Labels: pr: automerge
