Repository vercel/vercel, pull requests merged in 2023-07, with the labels that each got.

#10167 Revert "[build-utils] Allow file-ref sema to be controlled through env flag"
  .changeset/dry-hotels-worry.md
  packages/build-utils/src/file-fs-ref.ts
  packages/build-utils/src/file-ref.ts
Labels: pr: automerge

#10170 [cli] Added line return at end of help output
  .changeset/tame-ads-swim.md
  packages/cli/src/commands/help.ts
  packages/cli/test/unit/commands/__snapshots__/help.test.ts.snap
Labels: area: cli, semver: patch, pr: automerge

#10173 [tests] Fix `update-next.js` cron job to include changeset
  .changeset/auto-update-next.md
  utils/update-next.js
Labels: area: tests, pr: automerge

#10172 [cli] Allow additional project settings in `createProject()`
  .changeset/neat-apples-burn.md
  packages/cli/src/util/link/setup-and-link.ts
  packages/cli/src/util/projects/create-project.ts
  packages/cli/src/util/projects/update-project.ts
Labels: pr: automerge

#10181 Add Changesets "ignore" configuration
  .changeset/config.json
  .changeset/cool-stingrays-fry.md
Labels: pr: automerge

#10184 [node] fix decompress mismatching
  .changeset/fluffy-bikes-battle.md
  packages/node/src/serverless-functions/serverless-handler.mts
  packages/node/test/dev-fixtures/serverless-fetch.js
  packages/node/test/unit/dev.test.ts
Labels: pr: automerge

#10189 Revert "Add Changesets "ignore" configuration"
  .changeset/config.json
  .changeset/soft-apples-flow.md
Labels: pr: automerge

#10094 [cli] Run local Project detection during `vc link --repo`
  .changeset/popular-dots-nail.md
  packages/cli/src/commands/link/index.ts
  packages/cli/src/util/git/repo-info-to-url.ts
  packages/cli/src/util/link/repo.ts
  packages/cli/src/util/projects/detect-projects.ts
  packages/cli/test/unit/util/git/repo-info-to-url.test.ts
  packages/cli/test/unit/util/projects/detect-projects.test.ts
  packages/fs-detectors/test/fixtures/30-double-nested-workspaces/packages/backend/c/package.json
  packages/fs-detectors/test/fixtures/30-double-nested-workspaces/packages/backend/c/remix.config.js
  packages/fs-detectors/test/fixtures/30-double-nested-workspaces/packages/backend/d/package.json
  packages/fs-detectors/test/fixtures/30-double-nested-workspaces/packages/frontend/a/package.json
  packages/fs-detectors/test/fixtures/30-double-nested-workspaces/packages/frontend/b/package.json
Labels: pr: automerge

#10195 [fs-detectors] Add `detectFrameworks()`
  .changeset/good-clouds-repeat.md
  packages/fs-detectors/src/detect-framework.ts
  packages/fs-detectors/src/index.ts
  packages/fs-detectors/test/unit.framework-detector.test.ts
Labels: pr: automerge

#10205 [tests] Add huozhi to cron job for Next.js
  .changeset/five-tables-roll.md
  utils/update-next.js
Labels: area: tests, pr: automerge, semver: none

#10208 Update `supports-hyperlinks` to v3
  .changeset/short-squids-bathe.md
  packages/cli/package.json
  packages/cli/types/supports-hyperlinks/index.d.ts
  pnpm-lock.yaml
Labels: pr: automerge

#10210 [tests] Add lockfile to `51-puppeteer-build` test
  .changeset/twenty-dolphins-call.md
  packages/static-build/test/fixtures/51-puppeteer-build/build.js
  packages/static-build/test/fixtures/51-puppeteer-build/package.json
  packages/static-build/test/fixtures/51-puppeteer-build/vercel.json
  packages/static-build/test/fixtures/51-puppeteer-build/yarn.lock
Labels: area: tests, pr: automerge, semver: none

#10209 [build-utils] Push back `nodejs16.x` discontinue date to 2024-02-06
  .changeset/perfect-sheep-begin.md
  packages/build-utils/src/fs/node-version.ts
  packages/build-utils/test/unit.test.ts
Labels: area: build-utils, area: node, semver: patch, pr: automerge

#10203 [cli] Use `detectFrameworks()` during `vc link --repo`
  .changeset/weak-days-yawn.md
  packages/cli/src/util/link/repo.ts
  packages/cli/src/util/projects/detect-projects.ts
  packages/cli/test/unit/util/projects/detect-projects.test.ts
Labels: pr: automerge

#10223 [next] fix 404 page in edge runtime
  .changeset/rich-days-deliver.md
  packages/next/src/server-build.ts
  packages/next/src/utils.ts
  packages/next/test/fixtures/00-app-dir-edge-404/app/layout.js
  packages/next/test/fixtures/00-app-dir-edge-404/app/not-found.js
  packages/next/test/fixtures/00-app-dir-edge-404/app/not-found/not-found.js
  packages/next/test/fixtures/00-app-dir-edge-404/app/not-found/page.js
  packages/next/test/fixtures/00-app-dir-edge-404/app/page.js
  packages/next/test/fixtures/00-app-dir-edge-404/index.test.js
  packages/next/test/fixtures/00-app-dir-edge-404/next.config.js
  packages/next/test/fixtures/00-app-dir-edge-404/package.json
  packages/next/test/fixtures/00-app-dir-edge-404/vercel.json
Labels: area: next, pr: automerge

#10226 [cli] Update `proxy-agent` to v6.3.0
  .changeset/cool-feet-tan.md
  packages/cli/package.json
  pnpm-lock.yaml
Labels: pr: automerge

#10228 [frameworks][static-build] Add `ignorePackageJsonScript` configuration for Framework command settings
  .changeset/sixty-buttons-listen.md
  packages/cli/test/fixtures/unit/commands/build/storybook-with-middleware/.vercel/project.json
  packages/frameworks/src/frameworks.ts
  packages/frameworks/src/types.ts
  packages/frameworks/test/frameworks.unit.test.ts
  packages/static-build/src/index.ts
Labels: pr: automerge

#10225 [cli] Use `getNodeBinPaths()` in `vc dev`
  .changeset/late-bobcats-behave.md
  packages/cli/src/commands/dev/dev.ts
  packages/cli/src/util/dev/server.ts
  packages/cli/src/util/dev/types.ts
Labels: pr: automerge

#10243 [next] Fix pages and app router i18n handling
  .changeset/plenty-rings-dress.md
  packages/next/src/server-build.ts
  packages/next/src/utils.ts
  packages/next/test/fixtures/00-app-dir-i18n/app/api/hello-app/route.js
  packages/next/test/fixtures/00-app-dir-i18n/app/dynamic/[slug]/page.js
  packages/next/test/fixtures/00-app-dir-i18n/next.config.js
  packages/next/test/fixtures/00-app-dir-i18n/pages/another.js
  packages/next/test/fixtures/00-app-dir-i18n/pages/api/hello.js
  packages/next/test/fixtures/00-app-dir-i18n/pages/blog/[slug].js
  packages/next/test/fixtures/00-app-dir-i18n/probes.json
Labels: area: next, pr: automerge

#10249 [tests] fix `vary` header in next tests
  .changeset/cool-colts-carry.md
  packages/next/test/fixtures/00-app-dir-base-path/vercel.json
  packages/next/test/fixtures/00-app-dir-middleware/vercel.json
  packages/next/test/fixtures/00-app-dir-static/vercel.json
  packages/next/test/fixtures/00-app-dir-trailing-slash/vercel.json
  packages/next/test/fixtures/00-app-dir/vercel.json
  packages/next/test/fixtures/01-app-dir-static/vercel.json
Labels: area: tests, area: next, pr: automerge, semver: none

#10258 [next] Fix pages/404 gsp + i18n case
  .changeset/lovely-donuts-buy.md
  packages/next/src/index.ts
  packages/next/src/server-build.ts
  packages/next/test/fixtures/00-i18n-404-revalidate/pages/blog/[slug].js
Labels: area: next, pr: automerge

#10253 [examples] Remove "author" field from `hydrogen` template
  .changeset/spicy-kings-speak.md
  examples/hydrogen/package.json
Labels: pr: automerge

#10250 [cli] Add a "Global Options" section to help output
  .changeset/grumpy-actors-greet.md
  packages/cli/src/commands/help.ts
  packages/cli/test/unit/commands/__snapshots__/help.test.ts.snap
Labels: area: cli, semver: minor, pr: automerge

#9784 [remix] Install `@vercel/remix-run-dev` at build-time instead of using symlink
  .changeset/chatty-eyes-admire.md
  packages/remix/package.json
  packages/remix/src/build.ts
  packages/remix/src/prepare-cache.ts
  packages/remix/src/utils.ts
  packages/remix/test/fixtures/01-remix-basics/package.json
  packages/remix/test/fixtures/01-remix-basics/yarn.lock
  packages/remix/test/fixtures/03-with-pnpm/package.json
  packages/remix/test/fixtures/03-with-pnpm/pnpm-lock.yaml
  packages/remix/test/unit.resolve-semver-min-max.test.ts
  pnpm-lock.yaml
  utils/update-remix-run-dev.js
Labels: semver: minor, area: remix, pr: automerge

#10268 [cli] Migrate `remove` command to new structure
  .changeset/rare-badgers-teach.md
  packages/cli/src/commands/remove/command.ts
  packages/cli/src/commands/remove/index.ts
Labels: area: cli, semver: patch, pr: automerge

#10276 [cli] Migrate `bisect` command to new structure
  .changeset/angry-avocados-flow.md
  packages/cli/src/commands/bisect/command.ts
  packages/cli/src/commands/bisect/index.ts
Labels: area: cli, semver: patch, pr: automerge

#10284 [cli] Migrate `list` command to new structure
  .changeset/funny-insects-hide.md
  packages/cli/src/commands/list/command.ts
  packages/cli/src/commands/list/index.ts
Labels: area: cli, semver: patch, pr: automerge
