Repository vercel/vercel, pull requests merged in 2023-11, with the labels that each got.

#10799 Disable deployment SSO protection for tests
  .changeset/soft-shrimps-speak.md
  packages/cli/test/dev/utils.js
  packages/cli/test/integration-1.test.ts
  packages/cli/test/integration-2.test.ts
  packages/cli/test/integration-3.test.ts
  packages/client/src/utils/index.ts
  packages/client/tests/create-deployment.test.ts
  test/lib/deployment/now-deploy.js
Labels: pr: automerge

#10802 [build-utils] Add experimental flag to allow Node.js v20
  .changeset/little-mirrors-design.md
  packages/build-utils/src/fs/node-version.ts
  packages/build-utils/test/unit.test.ts
Labels: pr: automerge

#10767 [node] swap `undici.fetch` for `undici.request` in `serverless-handler.mts`
  .changeset/clean-cherries-sparkle.md
  packages/node/package.json
  packages/node/src/dev-server.mts
  packages/node/src/edge-functions/edge-handler.mts
  packages/node/src/serverless-functions/serverless-handler.mts
  packages/node/src/types.d.ts
  packages/node/test/unit/dev.test.ts
  pnpm-lock.yaml
Labels: pr: automerge

#10823 [next] Added more PPR tests
  .changeset/good-bobcats-dream.md
  packages/next/test/fixtures/00-app-dir-ppr-full/app/layout.jsx
  packages/next/test/fixtures/00-app-dir-ppr-full/app/loading/[slug]/page.jsx
  packages/next/test/fixtures/00-app-dir-ppr-full/app/loading/loading.jsx
  packages/next/test/fixtures/00-app-dir-ppr-full/components/dynamic.jsx
  packages/next/test/fixtures/00-app-dir-ppr-full/components/links.jsx
  packages/next/test/fixtures/00-app-dir-ppr-full/index.test.js
Labels: pr: automerge

#10830 chore: Update Remix example README
  examples/remix/README.md
Labels: area: examples, semver: patch, pr: automerge

#10822 [build-utils] Select Node.js version based on what's available in build-container
  .changeset/cuddly-squids-cough.md
  packages/build-utils/src/fs/node-version.ts
  packages/build-utils/src/fs/run-user-scripts.ts
  packages/build-utils/test/unit.test.ts
Labels: pr: automerge

#10820 Add .node-version file
  .node_version
  .nvmrc
Labels: pr: automerge

#10834 [build-utils] Remove Node v20 env var check
  .changeset/little-readers-explain.md
  packages/build-utils/src/fs/node-version.ts
  packages/build-utils/test/unit.test.ts
Labels: pr: automerge

#10858 [cli][tests] Work around Yarn + Corepack issue in tests
  .changeset/green-pianos-grow.md
  packages/cli/test/integration-1.test.ts
Labels: pr: automerge

#10855 [next] ensure function configs apply to route groups
  .changeset/eighty-sheep-beam.md
  .github/workflows/test.yml
  packages/next/src/server-build.ts
  packages/next/src/utils.ts
  packages/next/test/fixtures/00-app-dir-no-ppr/app/api/hello-again/with-group/(group)/route.js
  packages/next/test/fixtures/00-app-dir-no-ppr/app/dynamic-group/[slug]/(group)/page.js
  packages/next/test/integration/integration-1.test.js
Labels: pr: automerge

#10856 [go] Set Lambda runtime to "provided.al2"
  .changeset/thirty-birds-decide.md
  DEVELOPING_A_RUNTIME.md
  packages/go/src/index.ts
Labels: pr: automerge

#10864 Revert "[go] Set Lambda runtime to `provided.al2`"
  .changeset/thirty-birds-decide.md
  DEVELOPING_A_RUNTIME.md
  packages/go/src/index.ts
Labels: pr: automerge

#10859 [ruby] Enable `ruby3.2` runtime
  .changeset/grumpy-eagles-report.md
  packages/ruby/src/index.ts
  packages/ruby/src/install-ruby.ts
Labels: pr: automerge

#10873 Update placeholder for Nuxt to be correct command.
  .changeset/grumpy-wasps-protect.md
  packages/frameworks/src/frameworks.ts
Labels: area: frameworks, semver: patch

#10869 chore: update Nuxt example
  .changeset/three-weeks-care.md
  examples/nuxtjs/app.vue
  examples/nuxtjs/nuxt.config.ts
  examples/nuxtjs/package.json
  examples/nuxtjs/pnpm-lock.yaml
  examples/nuxtjs/public/favicon.ico
  examples/nuxtjs/server/tsconfig.json
  examples/nuxtjs/tsconfig.json
  examples/nuxtjs/yarn.lock
Labels: area: examples, semver: patch

#10881 [static-build] Add `yarn.lock` and force jsdom@22 to fix "umi-v2" test fixture
  .changeset/brave-flies-turn.md
  packages/static-build/test/fixtures/umi-v2/.gitignore
  packages/static-build/test/fixtures/umi-v2/package.json
  packages/static-build/test/fixtures/umi-v2/yarn.lock
Labels: pr: automerge

#10880 [go] Set Lambda runtime to "provided.al2" behind env var
  .changeset/thirty-birds-decide.md
  DEVELOPING_A_RUNTIME.md
  packages/go/src/index.ts
Labels: pr: automerge

#10819 [remix] Fix issue where `npm install` was not properly injecting forked compiler
  .changeset/fast-glasses-wonder.md
  packages/remix/src/build.ts
  packages/remix/src/utils.ts
Labels: pr: automerge

#10882 [tests] tidy and make select-org tests more realistic
  .changeset/five-garlics-know.md
  packages/cli/test/unit/util/input/select-org.test.ts
Labels: pr: automerge

#10884 [cli] Fix behavior for combination of northstar user + team scope provided to cli as an argument.
  .changeset/fuzzy-weeks-brake.md
  packages/cli/src/util/input/select-org.ts
  packages/cli/test/unit/util/input/select-org.test.ts
Labels: area: cli, semver: patch, pr: automerge
