Repository vercel/vercel, pull requests merged in 2023-09, with the labels that each got.

#10416 [next] fix 404 enoent for i18n
  .changeset/pink-carpets-perform.md
  packages/next/src/server-build.ts
Labels: pr: automerge

#10452 [cli] Remove `mri` workaround
  .changeset/metal-ties-shop.md
  packages/cli/src/commands/secrets.js
Labels: area: cli, pr: automerge

#10433 migrate dev command structure for help output
  .changeset/modern-avocados-double.md
  packages/cli/src/commands/dev/command.ts
  packages/cli/src/commands/dev/index.ts
  packages/cli/test/integration-1.test.ts
Labels: pr: automerge

#10427 [cli] Migrate `domains` to new command structure
  .changeset/five-bananas-joke.md
  packages/cli/src/commands/domains/command.ts
  packages/cli/src/commands/domains/index.ts
  packages/cli/src/commands/help.ts
Labels: pr: automerge

#10456 [next] Update page config test
  .changeset/pink-ladybugs-yell.md
  packages/next/test/fixtures/00-app-dir-segment-options/pages/api/hello.js
Labels: pr: automerge

#10411 chore(deps): upgrade semver dependency
  .changeset/gold-pumas-camp.md
  packages/build-utils/package.json
  packages/cli/package.json
  packages/fs-detectors/package.json
  packages/next/package.json
  packages/redwood/package.json
  packages/remix/package.json
  packages/ruby/package.json
  packages/static-build/package.json
  packages/static-build/test/fixtures/26-ejected-cra/package.json
  pnpm-lock.yaml
Labels: pr: automerge

#10460 [cli] N, not n.
  .changeset/calm-items-rhyme.md
  packages/cli/src/commands/project/command.ts
Labels: pr: automerge

#10434 [cli] migrate teams command
  .changeset/yellow-ears-cough.md
  packages/cli/src/commands/teams/command.ts
  packages/cli/src/commands/teams/index.ts
Labels: pr: automerge

#10430 Use `esbuild` for non-ncc'd packages
  .changeset/odd-olives-share.md
  internals/get-package-json/package.json
  internals/get-package-json/tsconfig.json
  package.json
  packages/build-utils/build.js
  packages/build-utils/build.mjs
  packages/build-utils/package.json
  packages/build-utils/tsconfig.json
  packages/client/package.json
  packages/client/tsconfig.json
  packages/error-utils/package.json
  packages/error-utils/tsconfig.json
  packages/frameworks/package.json
  packages/frameworks/tsconfig.json
  packages/fs-detectors/package.json
  packages/fs-detectors/tsconfig.json
  packages/hydrogen/build.js
  packages/hydrogen/package.json
  packages/hydrogen/tsconfig.json
  packages/remix/build.js
  packages/remix/package.json
  packages/remix/tsconfig.json
  packages/routing-utils/package.json
  packages/routing-utils/tsconfig.json
  packages/static-config/package.json
  packages/static-config/tsconfig.json
  pnpm-lock.yaml
  turbo.json
  utils/build.mjs
Labels: pr: automerge

#10461 [cli] Update secrets.js to more current styles
  .changeset/popular-impalas-rhyme.md
  packages/cli/src/commands/secrets/command.js
  packages/cli/src/commands/secrets/index.js
  packages/cli/src/util/exit.ts
  packages/cli/test/mocks/secrets.ts
  packages/cli/test/unit/commands/secrets.test.ts
Labels: area: cli, pr: automerge

#10458 [CLI] show instant preview url on `vc deploy` and `vc redeploy`
  .changeset/strong-drinks-confess.md
  packages/cli/src/commands/redeploy/index.ts
  packages/cli/src/util/deploy/get-preferred-preview-url.ts
  packages/cli/src/util/deploy/print-deployment-status.ts
  packages/cli/src/util/deploy/process-deployment.ts
  packages/cli/test/integration-2.test.ts
Labels: pr: automerge

#10466 [CLI] Fix team URL on `vercel help switch`
  .changeset/chilly-chefs-shake.md
  packages/cli/src/commands/teams/command.ts
Labels: pr: automerge

#10415 [next]: Fix RSC rewrite behavior
  .changeset/long-dingos-punch.md
  packages/next/src/server-build.ts
  packages/next/src/utils.ts
  packages/next/test/fixtures/00-app-dir-catchall-pages/app/[lang]/page.js
  packages/next/test/fixtures/00-app-dir-catchall-pages/probes.json
  packages/next/test/fixtures/00-app-dir/app/gsp/[text]/page.js
  packages/next/test/fixtures/00-app-dir/pages/[segmentA]/[segmentB]/[segmentC]/index.js
  packages/next/test/fixtures/00-app-dir/pages/docs/categories/foo.js
  packages/next/test/fixtures/00-app-dir/vercel.json
  test/lib/deployment/test-deployment.js
Labels: area: next, pr: automerge

#10467 [ci] Update codeowners
  .changeset/calm-kings-give.md
  .github/CODEOWNERS
Labels: area: tests, pr: automerge

#10465 [next] fix app dir edge functions with basePath
  .changeset/curvy-swans-tickle.md
  packages/next/src/index.ts
  packages/next/src/server-build.ts
  packages/next/src/utils.ts
  packages/next/test/integration/edge-app-dir-basepath/app/another/page.js
  packages/next/test/integration/edge-app-dir-basepath/app/dynamic/[slug]/page.js
  packages/next/test/integration/edge-app-dir-basepath/app/layout.js
  packages/next/test/integration/edge-app-dir-basepath/app/page.js
  packages/next/test/integration/edge-app-dir-basepath/app/test/page.js
  packages/next/test/integration/edge-app-dir-basepath/next.config.js
  packages/next/test/integration/edge-app-dir-basepath/package.json
  packages/next/test/integration/edge-app-dir-basepath/vercel.json
  packages/next/test/integration/integration-2.test.js
Labels: pr: automerge

#10473 [next] fix ENOENT on /404.html when `fallback: false` w/ `basePath`
  .changeset/nice-lies-sip.md
  packages/next/src/index.ts
  packages/next/test/fixtures/00-i18n-basepath-fallback-false-404/index.test.js
  packages/next/test/fixtures/00-i18n-basepath-fallback-false-404/next.config.js
  packages/next/test/fixtures/00-i18n-basepath-fallback-false-404/package.json
  packages/next/test/fixtures/00-i18n-basepath-fallback-false-404/pages/404.js
  packages/next/test/fixtures/00-i18n-basepath-fallback-false-404/pages/_app.js
  packages/next/test/fixtures/00-i18n-basepath-fallback-false-404/pages/another.js
  packages/next/test/fixtures/00-i18n-basepath-fallback-false-404/pages/api/blog/[slug].js
  packages/next/test/fixtures/00-i18n-basepath-fallback-false-404/pages/api/catchall/[...rest].js
  packages/next/test/fixtures/00-i18n-basepath-fallback-false-404/pages/api/hello.js
  packages/next/test/fixtures/00-i18n-basepath-fallback-false-404/pages/foo/[slug].js
  packages/next/test/fixtures/00-i18n-basepath-fallback-false-404/pages/hello.js
  packages/next/test/fixtures/00-i18n-basepath-fallback-false-404/pages/index.js
  packages/next/test/fixtures/00-i18n-basepath-fallback-false-404/probes.json
Labels: pr: automerge

#10474 fix .changeset/nice-lies-sip.md
  .changeset/nice-lies-sip.md
Labels: pr: automerge

#10462 [static-build] Use esbuild
  .changeset/moody-carrots-know.md
  packages/static-build/build.js
  packages/static-build/package.json
  packages/static-build/src/utils/gatsby.ts
  utils/build-builder.mjs
Labels: pr: automerge

#10468 [go] Update to esbuild script
  .changeset/dry-baboons-happen.md
  packages/go/analyze.go
  packages/go/build.js
  packages/go/package.json
  packages/go/src/go-helpers.ts
  packages/go/src/index.ts
  packages/go/test/index.test.ts
  packages/go/tsconfig.json
  pnpm-lock.yaml
Labels: pr: automerge

#10480 [hydrogen] Bundle, remove types and source maps
  .changeset/large-vans-jump.md
  packages/hydrogen/package.json
  packages/hydrogen/tsconfig.json
  pnpm-lock.yaml
Labels: pr: automerge

#10481 [build-utils] add `experimentalBypassFor` field to Prerender
  .changeset/three-bikes-explode.md
  packages/build-utils/src/prerender.ts
  packages/build-utils/src/types.ts
  packages/build-utils/test/unit.test.ts
Labels: pr: automerge

#10479 [remix] Bundle, remove types and source maps
  .changeset/fresh-turkeys-talk.md
  packages/hydrogen/package.json
  packages/remix/package.json
  packages/remix/src/prepare-cache.ts
  packages/remix/src/utils.ts
  packages/remix/tsconfig.json
  pnpm-lock.yaml
Labels: pr: automerge

#10471 [redwood] Use new esbuild script
  .changeset/few-moons-unite.md
  packages/redwood/build.js
  packages/redwood/package.json
Labels: pr: automerge

#10451 [node] upgrade edge-runtime
  .changeset/silver-tables-act.md
  packages/cli/package.json
  packages/edge/package.json
  packages/node/package.json
  pnpm-lock.yaml
Labels: area: node, pr: automerge

#10397 [examples] Update Astro starter
  .changeset/rare-comics-smell.md
  examples/astro/README.md
  examples/astro/astro.config.mjs
  examples/astro/package.json
  examples/astro/src/assets/logo.png
  examples/astro/src/env.d.ts
  examples/astro/src/pages/image.astro
Labels: area: examples, semver: patch, pr: automerge

#10487 [next] fix content-type for RSC prefetches
  .changeset/popular-donuts-jump.md
  packages/next/src/server-build.ts
  packages/next/src/utils.ts
  packages/next/test/fixtures/00-app-dir/vercel.json
Labels: pr: automerge

#10490 [examples] Use placeholder for API Key
  .changeset/fast-sheep-hunt.md
  examples/ionic-angular/src/index.html
Labels: area: examples, pr: automerge

#10492 [frameworks] Add `bun install` placeholder
  .changeset/sharp-bears-scream.md
  packages/frameworks/src/frameworks.ts
Labels: area: frameworks

#10485 next.js: add option to use bundled runtime
  .changeset/old-teachers-dress.md
  packages/next/src/server-build.ts
  packages/next/src/server-launcher.ts
  packages/next/src/utils.ts
  packages/next/test/fixtures/37-bundled-server/.gitignore
  packages/next/test/fixtures/37-bundled-server/app/app-route/route.js
  packages/next/test/fixtures/37-bundled-server/app/app/page.js
  packages/next/test/fixtures/37-bundled-server/app/layout.js
  packages/next/test/fixtures/37-bundled-server/index.test.js
  packages/next/test/fixtures/37-bundled-server/package.json
  packages/next/test/fixtures/37-bundled-server/pages/api/hello.js
  packages/next/test/fixtures/37-bundled-server/pages/index.js
  packages/next/test/fixtures/37-bundled-server/probes.json
  packages/next/test/fixtures/37-bundled-server/vercel.json
  packages/next/test/integration/integration-1.test.js
Labels: area: next, pr: automerge

#10504 [next] missed a prerender for experimentalBypassFor
  .changeset/breezy-phones-give.md
  packages/next/src/utils.ts
Labels: pr: automerge

#10513 Revert skipping datadog reports
  .changeset/silent-dragons-shop.md
  .github/workflows/test.yml
Labels: pr: automerge

#10515 Enable changesets experimental `updateInternalDependents: 'always'` config
  .changeset/config.json
  .changeset/tidy-vans-act.md
Labels: pr: automerge

#10516 Update bun changeset to bump static-build + CLI
  .changeset/config.json
  .changeset/odd-kids-scream.md
  .changeset/tidy-vans-act.md
Labels: pr: automerge

#10525 [remix] Fixes for Remix v2
  .changeset/weak-carrots-tickle.md
  packages/remix/defaults/server-node.mjs
  packages/remix/src/build.ts
  packages/remix/test/unit.resolve-semver-min-max.test.ts
Labels: pr: automerge

#10531 [next] fix feature flag detection
  .changeset/late-impalas-nail.md
  packages/next/src/server-build.ts
Labels: area: next, pr: automerge

#10527 Restore datadog checking with logs not exit codes
  .changeset/pink-drinks-obey.md
  .github/workflows/test.yml
  packages/cli/test/unit/commands/link.test.ts
  test/utils/determine-turbo-hit-or-miss/hit/sample.json
  test/utils/determine-turbo-hit-or-miss/index.test.js
  test/utils/determine-turbo-hit-or-miss/miss/sample.json
  utils/determine-turbo-hit-or-miss.js
Labels: area: tests, pr: automerge

#10530 [remix] Fix ESM mode for Edge runtime, add Remix v2 E2E test
  .changeset/smart-vans-promise.md
  packages/remix/defaults/server-edge.mjs
  packages/remix/test/fixtures/12-remix-v2/.gitignore
  packages/remix/test/fixtures/12-remix-v2/README.md
  packages/remix/test/fixtures/12-remix-v2/app/root.tsx
  packages/remix/test/fixtures/12-remix-v2/app/routes/_index.tsx
  packages/remix/test/fixtures/12-remix-v2/app/routes/edge.tsx
  packages/remix/test/fixtures/12-remix-v2/package.json
  packages/remix/test/fixtures/12-remix-v2/pnpm-lock.yaml
  packages/remix/test/fixtures/12-remix-v2/probes.json
  packages/remix/test/fixtures/12-remix-v2/public/favicon.ico
  packages/remix/test/fixtures/12-remix-v2/remix.config.js
  packages/remix/test/fixtures/12-remix-v2/remix.env.d.ts
  packages/remix/test/fixtures/12-remix-v2/tsconfig.json
Labels: area: remix, pr: automerge

#10532 [examples] Update "remix" template to v2
  .changeset/three-hats-peel.md
  examples/remix/.eslintrc.cjs
  examples/remix/.gitignore
  examples/remix/app/root.tsx
  examples/remix/app/routes/_index.tsx
  examples/remix/app/routes/edge.tsx
  examples/remix/package.json
  examples/remix/remix.config.js
  examples/remix/tsconfig.json
Labels: pr: automerge

#10543 [static-build] Mark `@vercel/static-config` and `ts-morph` as externals
  .changeset/gorgeous-mirrors-scream.md
  packages/static-build/package.json
  pnpm-lock.yaml
Labels: pr: automerge

#10544 [python] Fix docs URL in error message
  .changeset/rude-bulldogs-double.md
  packages/python/vc_init.py
Labels: pr: automerge

#10546 [gatsby-plugin-vercel-analytics] Remove "babel" compilation
  .changeset/light-candles-push.md
  packages/gatsby-plugin-vercel-analytics/.gitignore
  packages/gatsby-plugin-vercel-analytics/gatsby-browser.js
  packages/gatsby-plugin-vercel-analytics/package.json
  packages/gatsby-plugin-vercel-analytics/web-vitals.js
  pnpm-lock.yaml
Labels: pr: automerge

#10548 update code owners for nextjs example
  .changeset/thick-insects-walk.md
  .github/CODEOWNERS
Labels: area: tests, pr: automerge

#10535 [cli] Support northstar users
  .changeset/selfish-dancers-sort.md
  internals/types/index.d.ts
  packages/cli/src/args.ts
  packages/cli/src/commands/domains/command.ts
  packages/cli/src/commands/domains/move.ts
  packages/cli/src/commands/login/index.ts
  packages/cli/src/commands/logout/command.ts
  packages/cli/src/commands/project/command.ts
  packages/cli/src/commands/teams/list.ts
  packages/cli/src/commands/teams/switch.ts
  packages/cli/src/index.ts
  packages/cli/src/util/errors-ts.ts
  packages/cli/src/util/get-scope.ts
  packages/cli/src/util/input/select-org.ts
  packages/cli/src/util/login/update-current-team-after-login.ts
  packages/cli/src/util/output/table.ts
  packages/cli/test/integration-1.test.ts
  packages/cli/test/integration-2.test.ts
  packages/cli/test/integration-3.test.ts
  packages/cli/test/mocks/domains.ts
  packages/cli/test/mocks/team.ts
  packages/cli/test/mocks/user.ts
  packages/cli/test/northstar.test.ts
  packages/cli/test/unit/commands/domains.test.ts
  packages/cli/test/unit/commands/login.test.ts
  packages/cli/test/unit/commands/switch.test.ts
  packages/cli/test/unit/commands/teams.test.ts
  packages/cli/test/unit/util/get-scope.test.ts
  packages/cli/test/unit/util/input/select-org.test.ts
  packages/cli/test/unit/util/login/update-current-team-after-login.test.ts
Labels: pr: automerge

#10508 [gatsby-plugin-vercel-builder] Use "esbuild" to build package
  .changeset/hungry-scissors-cheer.md
  packages/gatsby-plugin-vercel-builder/.gitignore
  packages/gatsby-plugin-vercel-builder/gatsby-node.js
  packages/gatsby-plugin-vercel-builder/gatsby-node.ts
  packages/gatsby-plugin-vercel-builder/package.json
  packages/gatsby-plugin-vercel-builder/src/handlers/build.ts
  packages/gatsby-plugin-vercel-builder/src/handlers/utils.ts
  packages/gatsby-plugin-vercel-builder/src/helpers/functions.ts
  packages/gatsby-plugin-vercel-builder/templates/ssr-handler.js
  packages/gatsby-plugin-vercel-builder/tsconfig.base.json
  packages/gatsby-plugin-vercel-builder/tsconfig.gatsby.json
  packages/gatsby-plugin-vercel-builder/tsconfig.json
  packages/gatsby-plugin-vercel-builder/tsconfig.src.json
  packages/gatsby-plugin-vercel-builder/turbo.json
  pnpm-lock.yaml
Labels: pr: automerge

#10549 [cli][next][build-utils] Variants
  .changeset/nervous-apricots-heal.md
  packages/build-utils/src/types.ts
  packages/cli/src/commands/build/index.ts
  packages/next/src/index.ts
  packages/next/src/server-build.ts
  packages/next/src/utils.ts
Labels: area: build-utils, area: cli, semver: patch, area: next, pr: automerge

#10482 [next] Use "esbuild" to build package
  .changeset/silent-terms-occur.md
  packages/next/build.js
  packages/next/build.mjs
  packages/next/package.json
  packages/next/src/constants.ts
  packages/next/src/edge-function-source/constants.ts
  packages/next/src/edge-function-source/get-edge-function-source.ts
  packages/next/src/index.ts
  packages/next/src/pretty-bytes.ts
  packages/next/src/server-build.ts
  packages/next/src/utils.ts
  packages/next/test/tsconfig.json
  packages/next/test/unit/__snapshots__/utils.test.ts.snap
  packages/next/test/unit/middleware-routes.test.ts
  packages/next/test/unit/utils.test.ts
  packages/next/test/utils.ts
  pnpm-lock.yaml
  utils/build-builder.mjs
Labels: pr: automerge

#10500 [speed insights] Prepare for migration to new speed insights package
  .changeset/friendly-oranges-trade.md
  .changeset/silent-hotels-search.md
  packages/cli/src/commands/build/index.ts
  packages/cli/src/commands/env/pull.ts
  packages/cli/test/helpers/prepare.js
  packages/cli/test/integration-2.test.ts
  packages/cli/test/unit/commands/env.test.ts
Labels: pr: automerge

#10553 [node] Use "esbuild" to build package
  .changeset/lucky-ties-taste.md
  packages/node/@types/zeit__ncc/index.d.ts
  packages/node/build.js
  packages/node/build.mjs
  packages/node/package.json
  packages/node/src/index.ts
  packages/node/src/serverless-functions/helpers.ts
  packages/node/src/types.d.ts
  packages/node/src/typescript.ts
  packages/node/tsconfig.json
  pnpm-lock.yaml
  utils/build.mjs
Labels: pr: automerge

#10555 [cli] Use "esbuild"
  .changeset/angry-keys-compete.md
  packages/cli/package.json
  packages/cli/scripts/build.mjs
  packages/cli/scripts/build.ts
  packages/cli/scripts/compile-templates.js
  packages/cli/scripts/compile-templates.mjs
  packages/cli/src/util/build/import-builders.ts
  pnpm-lock.yaml
Labels: pr: automerge

#10559 Remove `@vercel/ncc` dependency from all packages
  .changeset/cuddly-cars-press.md
  package.json
  packages/build-utils/package.json
  packages/cli/package.json
  packages/cli/src/util/get-latest-version/get-latest-worker.js
  packages/go/package.json
  packages/node/package.json
  packages/node/src/edge-functions/edge-handler.mts
  packages/python/package.json
  packages/ruby/package.json
  packages/static-build/package.json
  pnpm-lock.yaml
Labels: pr: automerge

#10568 [next] Fix a couple issues with server-build template injecting
  .changeset/pretty-eagles-talk.md
  packages/next/src/server-build.ts
  packages/next/src/server-launcher.ts
  packages/next/test/fixtures/38-cold-boot-lab/.gitignore
  packages/next/test/fixtures/38-cold-boot-lab/app/favicon.ico
  packages/next/test/fixtures/38-cold-boot-lab/app/layout.js
  packages/next/test/fixtures/38-cold-boot-lab/app/page.js
  packages/next/test/fixtures/38-cold-boot-lab/index.test.js
  packages/next/test/fixtures/38-cold-boot-lab/package.json
  packages/next/test/fixtures/38-cold-boot-lab/pnpm-lock.yaml
Labels: pr: automerge

#10569 [ci] increase concurrency for e2e tests
  .changeset/large-weeks-boil.md
  utils/chunk-tests.js
Labels: pr: automerge

#10570 [ci] use `--output-logs=new-only` to only list tests that changed
  .changeset/very-happy-tests.md
  utils/chunk-tests.js
Labels: area: tests, pr: automerge

#10575 [cli] disable source map for prod build
  .changeset/disable-source-map.md
  packages/cli/tsconfig.json
Labels: area: cli, pr: automerge

#10577 [cli] remove unused source map pkg
  .changeset/beige-rockets-remember.md
  packages/cli/package.json
  packages/cli/src/index.ts
  packages/cli/types/zeit__source-map-support/index.d.ts
  pnpm-lock.yaml
Labels: area: cli, pr: automerge

#10579 Update broken documentation link
  .changeset/many-actors-juggle.md
  packages/go/src/go-helpers.ts
Labels: pr: automerge

#10551 [vc cert ls] remove error shallowing
  .changeset/pink-pigs-leave.md
  packages/cli/src/commands/certs/ls.ts
  packages/cli/test/unit/commands/certs.test.ts
Labels: pr: automerge

#10584 Revert "[ci] use `--output-logs=new-only` to only list tests that changed"
  .changeset/very-happy-tests.md
  utils/chunk-tests.js
Labels: area: tests, pr: automerge

#10583 [cli] Update bun detection and add tests for projects with both `bunlock.b` and `yarn.lock` files
  .changeset/plenty-seahorses-watch.md
  packages/build-utils/src/fs/run-user-scripts.ts
  packages/build-utils/test/fixtures/31-bun-v1-with-yarn-lock/.gitignore
  packages/build-utils/test/fixtures/31-bun-v1-with-yarn-lock/build.js
  packages/build-utils/test/fixtures/31-bun-v1-with-yarn-lock/bun.lockb
  packages/build-utils/test/fixtures/31-bun-v1-with-yarn-lock/package.json
  packages/build-utils/test/fixtures/31-bun-v1-with-yarn-lock/probes.json
  packages/build-utils/test/fixtures/31-bun-v1-with-yarn-lock/yarn.lock
  packages/build-utils/test/unit.test.ts
  packages/fs-detectors/test/fixtures/59-bun-with-binary-and-readable-lockfile/bun.lockb
  packages/fs-detectors/test/fixtures/59-bun-with-binary-and-readable-lockfile/package.json
  packages/fs-detectors/test/fixtures/59-bun-with-binary-and-readable-lockfile/yarn.lock
  packages/fs-detectors/test/unit.detect-package-managers.test.ts
Labels: pr: automerge

#10603 Fix incorrect comment
  .changeset/green-coins-appear.md
  packages/build-utils/src/fs/run-user-scripts.ts
Labels: pr: automerge

#10599 Fix internal-dependency-trace script by handling commands/secrets/index.js
  scripts/internal-dependency-trace/src/trace.js
Labels: pr: automerge

#10608 [next] fix next.js edge functions that use the instrumentation hook
  .changeset/bright-timers-remember.md
  packages/next/src/edge-function-source/get-edge-function-source.ts
  packages/next/test/fixtures/36-instrumentation-hook/app/api/edge/route.js
  packages/next/test/fixtures/36-instrumentation-hook/app/api/node/route.js
  packages/next/test/fixtures/36-instrumentation-hook/app/edge/page.jsx
  packages/next/test/fixtures/36-instrumentation-hook/app/layout.jsx
  packages/next/test/fixtures/36-instrumentation-hook/app/node/page.jsx
  packages/next/test/fixtures/36-instrumentation-hook/index.test.js
  packages/next/test/fixtures/36-instrumentation-hook/pages/index.js
Labels: area: next, pr: automerge

#10612 [cli] Restore setting of `currentTeam`
  .changeset/flat-dingos-trade.md
  packages/cli/src/commands/login/index.ts
Labels: area: cli, pr: automerge

#10620 [tests] improve gatsby fixtures in static-build
  .changeset/nine-horses-guess.md
  packages/static-build/test/fixtures/gatsby-v4-pnpm/gatsby-config.ts
  packages/static-build/test/fixtures/gatsby-v4-pnpm/package.json
  packages/static-build/test/fixtures/gatsby-v4-pnpm/pnpm-lock.yaml
  packages/static-build/test/fixtures/gatsby-v4-pnpm/probes.json
  packages/static-build/test/fixtures/gatsby-v4-pnpm/src/components/header.js
  packages/static-build/test/fixtures/gatsby-v4-pnpm/src/components/index.module.css
  packages/static-build/test/fixtures/gatsby-v4-pnpm/src/components/layout.css
  packages/static-build/test/fixtures/gatsby-v4-pnpm/src/components/layout.js
  packages/static-build/test/fixtures/gatsby-v4-pnpm/src/components/seo.js
  packages/static-build/test/fixtures/gatsby-v4-pnpm/src/images/example.png
  packages/static-build/test/fixtures/gatsby-v4-pnpm/src/images/gatsby-icon.png
  packages/static-build/test/fixtures/gatsby-v4-pnpm/src/pages/404.js
  packages/static-build/test/fixtures/gatsby-v4-pnpm/src/pages/index.js
  packages/static-build/test/fixtures/gatsby-v4-pnpm/src/pages/page-2.js
  packages/static-build/test/fixtures/gatsby-v4-pnpm/src/pages/using-ssr.js
  packages/static-build/test/fixtures/gatsby-v4-pnpm/src/pages/using-typescript.tsx
  packages/static-build/test/fixtures/gatsby-v4-pnpm/src/templates/using-dsg.js
  packages/static-build/test/fixtures/gatsby-v4/gatsby-config.js
  packages/static-build/test/fixtures/gatsby-v4/package-lock.json
  packages/static-build/test/fixtures/gatsby-v4/package.json
  packages/static-build/test/fixtures/gatsby-v4/probes.json
  packages/static-build/test/fixtures/gatsby-v4/src/components/header.js
  packages/static-build/test/fixtures/gatsby-v4/src/components/index.module.css
  packages/static-build/test/fixtures/gatsby-v4/src/components/layout.css
  packages/static-build/test/fixtures/gatsby-v4/src/components/layout.js
  packages/static-build/test/fixtures/gatsby-v4/src/components/seo.js
  packages/static-build/test/fixtures/gatsby-v4/src/images/example.png
  packages/static-build/test/fixtures/gatsby-v4/src/images/gatsby-icon.png
  packages/static-build/test/fixtures/gatsby-v4/src/pages/404.js
  packages/static-build/test/fixtures/gatsby-v4/src/pages/index.js
  packages/static-build/test/fixtures/gatsby-v4/src/pages/page-2.js
  packages/static-build/test/fixtures/gatsby-v4/src/pages/using-ssr.js
  packages/static-build/test/fixtures/gatsby-v4/src/pages/using-typescript.tsx
  packages/static-build/test/fixtures/gatsby-v4/src/templates/using-dsg.js
  packages/static-build/test/fixtures/gatsby-v5-pathPrefix/gatsby-config.js
  packages/static-build/test/fixtures/gatsby-v5-pathPrefix/package-lock.json
  packages/static-build/test/fixtures/gatsby-v5-pathPrefix/package.json
  packages/static-build/test/fixtures/gatsby-v5-pathPrefix/probes.json
  packages/static-build/test/fixtures/gatsby-v5-pathPrefix/src/images/icon.png
  packages/static-build/test/fixtures/gatsby-v5-pathPrefix/src/pages/404.js
  packages/static-build/test/fixtures/gatsby-v5-pathPrefix/src/pages/dsg.js
  packages/static-build/test/fixtures/gatsby-v5-pathPrefix/src/pages/index.js
  packages/static-build/test/fixtures/gatsby-v5-pathPrefix/src/pages/ssr.js
  packages/static-build/test/fixtures/gatsby-v5/gatsby-config.js
  packages/static-build/test/fixtures/gatsby-v5/package-lock.json
  packages/static-build/test/fixtures/gatsby-v5/package.json
  packages/static-build/test/fixtures/gatsby-v5/probes.json
  packages/static-build/test/fixtures/gatsby-v5/src/images/icon.png
  packages/static-build/test/fixtures/gatsby-v5/src/pages/404.js
  packages/static-build/test/fixtures/gatsby-v5/src/pages/dsg.js
  packages/static-build/test/fixtures/gatsby-v5/src/pages/index.js
  packages/static-build/test/fixtures/gatsby-v5/src/pages/ssr.js
Labels: pr: automerge
