Repository vercel/vercel, pull requests merged in 2023-06, with the labels that each got.

#10049 [cli] Ensure .npmrc does not contain use-node-version
  .changeset/quiet-lizards-fetch.md
  packages/build-utils/src/index.ts
  packages/build-utils/src/validate-npmrc.ts
  packages/build-utils/test/fixtures/29-npmrc/comment-use-node-version/.npmrc
  packages/build-utils/test/fixtures/29-npmrc/good/.npmrc
  packages/build-utils/test/fixtures/29-npmrc/has-use-node-version/.npmrc
  packages/build-utils/test/unit.validate-npmrc.test.ts
  packages/cli/src/commands/build.ts
  packages/cli/test/fixtures/unit/commands/build/npmrc-use-node-version/.npmrc
  packages/cli/test/unit/commands/build/index.test.ts
Labels: area: cli, semver: patch, pr: automerge

#10056 [cli] `vc build` ignore `.env*` & ignore files for `@vercel/static`
  .changeset/cool-flowers-press.md
  packages/cli/src/util/build/static-builder.ts
  packages/cli/test/fixtures/unit/commands/build/static-env/.env
  packages/cli/test/fixtures/unit/commands/build/static-env/.vercel/project.json
  packages/cli/test/fixtures/unit/commands/build/static-env/index.html
  packages/cli/test/unit/commands/build/index.test.ts
Labels: area: cli, area: client, semver: patch, pr: automerge

#10054 [cli] Add `client.fetchPaginated()` async iterator
  .changeset/ninety-pugs-melt.md
  internals/types/index.d.ts
  packages/cli/src/commands/bisect/index.ts
  packages/cli/src/util/client.ts
  packages/cli/src/util/link/repo.ts
Labels: pr: automerge

#10065 Enforce a changeset file to be present
  .github/workflows/test-lint.yml
Labels: pr: automerge

#10067 Add vercel.json setting overrides to storybook example for zero-config experience
  .changeset/tall-zebras-cover.md
  examples/storybook/vercel.json
Labels: area: examples, pr: automerge, semver: none

#9947 [node] Add isomorphic functions
  .changeset/young-rats-smoke.md
  packages/cli/src/util/extension/proxy.ts
  packages/cli/test/dev/integration-1.test.ts
  packages/node/package.json
  packages/node/src/edge-functions/edge-handler-template.js
  packages/node/src/edge-functions/edge-handler.mts
  packages/node/src/serverless-functions/helpers-web.ts
  packages/node/src/serverless-functions/serverless-handler.mts
  packages/node/src/utils.ts
  packages/node/test/dev-fixtures/serverless-web.js
  packages/node/test/unit/dev.test.ts
  pnpm-lock.yaml
Labels: area: node, semver: minor

#10079 Clear revert out of changelog
  .changeset/friendly-mangos-type.md
Labels: pr: automerge

#10077 handle undefined content type in `vc dev`
  .changeset/sour-lies-pay.md
  packages/node/src/serverless-functions/helpers.ts
Labels: pr: automerge

#10078 Revert "Revert "[cli] Add support for `vc pull` command with repo link""
  .changeset/polite-apricots-leave.md
  internals/types/index.d.ts
  packages/cli/src/commands/pull.ts
  packages/cli/src/util/link/ensure-link.ts
  packages/cli/src/util/link/repo.ts
  packages/cli/src/util/projects/project-settings.ts
  packages/cli/test/fixtures/unit/monorepo-link/dashboard/.gitkeep
  packages/cli/test/helpers/setup-unit-fixture.ts
  packages/cli/test/unit/commands/pull.test.ts
Labels: pr: automerge

#10075 [cli] Add support for `vc build` command with repo link
  .changeset/red-wolves-boil.md
  internals/types/index.d.ts
  packages/cli/src/commands/build.ts
  packages/cli/src/commands/pull.ts
  packages/cli/src/util/link/ensure-link.ts
  packages/cli/src/util/projects/link.ts
  packages/cli/src/util/projects/project-settings.ts
  packages/cli/test/fixtures/unit/monorepo-link/.gitignore
  packages/cli/test/fixtures/unit/monorepo-link/blog/package.json
  packages/cli/test/fixtures/unit/monorepo-link/dashboard/.gitkeep
  packages/cli/test/fixtures/unit/monorepo-link/dashboard/package.json
  packages/cli/test/fixtures/unit/monorepo-link/marketing/package.json
  packages/cli/test/unit/commands/build/index.test.ts
Labels: pr: automerge

#10082 [cli] Add support for `vc dev` command with repo link
  .changeset/mean-windows-cheer.md
  packages/cli/src/commands/dev/dev.ts
Labels: pr: automerge

#10084 [cli] Move readme copy logic to a helper function for `vc link`
  .changeset/perfect-gorillas-film.md
  packages/cli/src/util/link/repo.ts
  packages/cli/src/util/projects/link.ts
Labels: pr: automerge

#10085 [cli] vc env pull should add `.env*.local` to `.gitignore`
  .changeset/blue-rats-know.md
  packages/cli/src/commands/env/index.ts
  packages/cli/src/commands/env/pull.ts
  packages/cli/src/commands/pull.ts
  packages/cli/test/fixtures/unit/vercel-env-pull-with-gitignore/.gitignore
  packages/cli/test/fixtures/unit/vercel-env-pull-with-gitignore/.vercel/project.json
  packages/cli/test/unit/commands/env.test.ts
Labels: area: cli, semver: patch, pr: automerge

#10083 [cli] Add support for `vc deploy --prebuilt` command with repo link
  .changeset/mighty-grapes-whisper.md
  packages/cli/src/commands/deploy/index.ts
  packages/cli/test/fixtures/unit/build-output-api-failed-before-builds/.vercel/project.json
  packages/cli/test/fixtures/unit/build-output-api-failed-within-build/.vercel/project.json
  packages/cli/test/fixtures/unit/build-output-api-preview/.vercel/project.json
  packages/cli/test/fixtures/unit/build-output-api-production/.vercel/project.json
  packages/cli/test/unit/commands/deploy.test.ts
Labels: pr: automerge

#10093 [cli] Remove `findProjectFromPath()`
  .changeset/yellow-eels-stare.md
  packages/cli/src/util/link/repo.ts
  packages/cli/test/unit/util/link/repo.test.ts
Labels: pr: automerge

#10100 [fs-detectors] Use `LocalFileSystemDetector` instead of `FixtureFilesystem`
  .changeset/calm-apes-double.md
  packages/fs-detectors/package.json
  packages/fs-detectors/src/detectors/local-file-system-detector.ts
  packages/fs-detectors/test/unit.detect-monorepo-managers.test.ts
  packages/fs-detectors/test/unit.detect-package-managers.test.ts
  packages/fs-detectors/test/unit.detect-workspace-managers.test.ts
  packages/fs-detectors/test/unit.examples.test.ts
  packages/fs-detectors/test/unit.get-monorepo-default-settings.test.ts
  packages/fs-detectors/test/unit.get-project-paths.test.ts
  packages/fs-detectors/test/unit.get-workspaces-package-paths.test.ts
  packages/fs-detectors/test/unit.get-workspaces.test.ts
  packages/fs-detectors/test/unit.local-file-system-detector.test.ts
  packages/fs-detectors/test/utils/fixture-filesystem.ts
Labels: pr: automerge

#10106 [remix] Link to `https://vercel.com/help`
  .changeset/gorgeous-apricots-study.md
  packages/remix/src/build.ts
Labels: pr: automerge

#10103 [fs-detectors] Add `test-e2e` script
  .changeset/red-cups-build.md
  packages/fs-detectors/package.json
  packages/fs-detectors/test/fixtures/01-zero-config-api/probes.json
  packages/fs-detectors/test/fixtures/02-zero-config-api/probes.json
  packages/fs-detectors/test/integration.test.ts
Labels: pr: automerge

#10110 [cli] do not force auto-assign value on deployments
  .changeset/fluffy-socks-refuse.md
  packages/cli/src/commands/deploy/index.ts
  packages/cli/src/util/index.ts
Labels: pr: automerge

#10115 Remove `.changeset/curvy-stingrays-cheat.md`
  .changeset/curvy-stingrays-cheat.md
Labels: pr: automerge

#10051 [node][edge][cli] upgrade Edge Runtime
  .changeset/lucky-trainers-glow.md
  packages/cli/package.json
  packages/edge/package.json
  packages/node/package.json
  packages/node/src/edge-functions/edge-handler.mts
  pnpm-lock.yaml
Labels: area: node, semver: patch

#10112 [cli] Add debug logging for repo link root lookup
  .changeset/five-lions-switch.md
  packages/cli/src/util/link/repo.ts
  packages/cli/src/util/projects/link.ts
  packages/cli/test/unit/util/link/repo.test.ts
Labels: pr: automerge

#10114 [cli] Only show relevant Project matches in Project selector
  .changeset/nasty-hotels-visit.md
  packages/cli/src/util/projects/link.ts
Labels: pr: automerge

#10133 Delete lerna.json
  .changeset/delete-lerna-json.md
  lerna.json
Labels: pr: automerge

#10143 [cli] Respond with "Redirecting..." to match production behavior
  .changeset/polite-experts-jam.md
  packages/cli/src/util/dev/server.ts
  packages/cli/test/dev/integration-2.test.ts
  packages/cli/test/dev/integration-3.test.ts
  packages/cli/test/dev/integration-5.test.ts
Labels: pr: automerge

#10144 Delete `.changeset/beige-carrots-begin.md`
  .changeset/beige-carrots-begin.md
Labels: pr: automerge

#10135 require `--yes` flag to promote preview deployment
  .changeset/green-badgers-reflect.md
  packages/cli/src/commands/promote/index.ts
  packages/cli/src/commands/promote/request-promote.ts
  packages/cli/test/mocks/deployment.ts
  packages/cli/test/unit/commands/promote.test.ts
Labels: pr: automerge

#9846 [examples] Update `remix` template
  examples/remix/.eslintrc.js
  examples/remix/.gitignore
  examples/remix/app/root.tsx
  examples/remix/app/routes/_index.tsx
  examples/remix/app/routes/edge.tsx
  examples/remix/package.json
  examples/remix/pnpm-lock.yaml
  examples/remix/remix.config.js
Labels: area: examples, semver: patch

#10148 [frameworks] Update `saber.land` to `saber.egoist.dev`
  .changeset/shy-pumas-dress.md
  examples/saber/README.md
  examples/saber/pages/about.md
  packages/frameworks/src/frameworks.ts
Labels: pr: automerge

#10147 [next] Update payload flag
  .changeset/hip-otters-turn.md
  packages/next/src/index.ts
  packages/next/src/utils.ts
  packages/next/test/fixtures/22-ssg-v2-multi-payload/vercel.json
Labels: area: next, pr: automerge

#10150 [build-utils] Add `getNodeBinPaths()` function
  .changeset/perfect-wasps-wait.md
  .changeset/tough-singers-live.md
  packages/build-utils/src/fs/run-user-scripts.ts
  packages/build-utils/src/index.ts
  packages/build-utils/test/unit.get-node-bin-path.test.ts
  packages/build-utils/test/unit.get-node-bin-paths.test.ts
  packages/build-utils/test/unit.traverse-up-directories.test.ts
  packages/cli/src/util/link/repo.ts
  packages/cli/test/unit/util/link/repo.test.ts
  packages/next/src/index.ts
  packages/static-build/src/index.ts
Labels: pr: automerge

#10154 [cli] Optimize write build result for vc build
  .changeset/loud-teachers-hug.md
  packages/cli/src/util/build/write-build-result.ts
Labels: area: cli, pr: automerge

#10155 [next] Ensure RSC paths handle basePath
  .changeset/strong-coins-teach.md
  packages/next/.gitignore
  packages/next/src/server-build.ts
  packages/next/test/fixtures/00-app-dir-base-path/index.test.js
  packages/next/test/fixtures/00-app-dir-base-path/vercel.json
Labels: area: next, pr: automerge

#10157 [cli] Remove `preinstall` script
  .changeset/wet-spoons-boil.md
  packages/cli/package.json
  packages/cli/scripts/preinstall.js
Labels: pr: automerge

#10162 Removes a leftover `console.log` in the new `help` method
  packages/cli/src/commands/help.ts
Labels: pr: automerge
