Repository vercel/vercel, pull requests merged in 2023-12, with the labels that each got.

#10895 [cli] Revert "forbids globally installed @vercel/speed-insights and @vercel/analytics (#10848)"
  .changeset/many-files-decide.md
  packages/cli/src/commands/build/index.ts
  packages/cli/test/helpers/prepare.js
  packages/cli/test/integration-2.test.ts
Labels: pr: automerge

#10887 Add GitHub Runner Image Version to turbo-cache-key.json
  utils/gen.js
Labels: pr: automerge, semver: none

#10909 [ruby] Use Ruby 3.2 in test fixtures
  .changeset/lazy-hornets-remember.md
  packages/ruby/src/index.ts
  packages/ruby/test/fixtures/01-cowsay/Gemfile
  packages/ruby/test/fixtures/02-cowsay-vendored/Gemfile
  packages/ruby/test/fixtures/04-cowsay-vendored-nested/project/Gemfile
  packages/ruby/test/fixtures/05-sinatra/Gemfile
  packages/ruby/test/fixtures/05-sinatra/Gemfile.lock
  packages/ruby/test/test.js
Labels: pr: automerge

#10910 [ruby] Remove `VERCEL_ALLOW_RUBY32` env var check
  .changeset/bright-lamps-confess.md
  packages/ruby/src/install-ruby.ts
Labels: pr: automerge

#10919 [cli] add `--deprecated` option to `vc project ls` command
  .changeset/clever-rules-smile.md
  packages/build-utils/src/fs/node-version.ts
  packages/build-utils/src/index.ts
  packages/cli/src/commands/project/command.ts
  packages/cli/src/commands/project/index.ts
  packages/cli/src/commands/project/list.ts
  packages/cli/test/mocks/project.ts
  packages/cli/test/unit/commands/project.test.ts
Labels: semver: minor, pr: automerge

#10934 [tests] fix brittle next rewrite probe test
  .changeset/twelve-pots-whisper.md
  packages/next/test/fixtures/23-custom-routes-verbose/vercel.json
Labels: pr: automerge, semver: none

#10922 [remix] Reinstall dependencies during `prepareCache()`
  .changeset/neat-turkeys-relate.md
  packages/remix/src/build.ts
  packages/remix/src/prepare-cache.ts
Labels: pr: automerge

#10932 [cli] double page limit for vc project ls --deprecated
  .changeset/breezy-worms-play.md
  packages/cli/src/commands/project/list.ts
Labels: semver: patch, pr: automerge

#10938 [cli] Use new `deprecated` query param in projects api for `vc project ls --deprecated`
  .changeset/clever-peaches-allow.md
  packages/cli/src/commands/project/list.ts
Labels: semver: patch, pr: automerge

#10918 [build-utils] Add getPathForPackageManager
  .changeset/violet-deers-fail.md
  packages/build-utils/src/fs/run-user-scripts.ts
  packages/build-utils/src/index.ts
  packages/build-utils/test/unit.get-env-for-package-manager.test.ts
Labels: semver: minor, pr: automerge

#10950 [static-build] Update test fixture stencil-v4 to latest
  .changeset/afraid-camels-arrive.md
  packages/static-build/test/fixtures/stencil-v4/package-lock.json
  packages/static-build/test/fixtures/stencil-v4/package.json
Labels: area: static-build, pr: automerge

#10956 [cli] Fix `vc bisect` selecting too many deployments
  .changeset/real-bulldogs-nail.md
  packages/cli/src/commands/bisect/index.ts
Labels: pr: automerge

#10951 [static-build] Update storybook-v7 fixture to latest
  .changeset/gorgeous-colts-count.md
  packages/static-build/test/fixtures/storybook-v7/package-lock.json
  packages/static-build/test/fixtures/storybook-v7/package.json
Labels: area: static-build, pr: automerge

#10949 [examples] Update ionic-react to latest
  .changeset/clean-chairs-talk.md
  examples/ionic-react/yarn.lock
  packages/static-build/test/fixtures/ionic-react-v7/package-lock.json
  packages/static-build/test/fixtures/ionic-react-v7/package.json
Labels: area: static-build, pr: automerge

#10948 [examples] Update sveltekit1 fixture to latest 1.x
  .changeset/tricky-rocks-wash.md
  examples/sveltekit-1/package.json
  pnpm-lock.yaml
Labels: area: examples, pr: automerge

#10952 [static-build] Update astro-v3 to fixture to latest
  .changeset/wet-cherries-develop.md
  packages/static-build/test/fixtures/astro-v3/package-lock.json
  packages/static-build/test/fixtures/astro-v3/package.json
Labels: area: tests, area: static-build, pr: automerge

#10957 [static-build] update ember-v5 fixture to latest minor
  .changeset/mean-laws-appear.md
  packages/static-build/test/fixtures/ember-v5/.ember-cli
  packages/static-build/test/fixtures/ember-v5/.github/workflows/ci.yml
  packages/static-build/test/fixtures/ember-v5/README.md
  packages/static-build/test/fixtures/ember-v5/config/ember-cli-update.json
  packages/static-build/test/fixtures/ember-v5/package.json
Labels: area: tests, area: static-build, pr: automerge

#10953 [static-build] Add vite@5 test fixture
  .changeset/angry-shirts-jam.md
  packages/static-build/test/fixtures/vite-v5/.gitignore
  packages/static-build/test/fixtures/vite-v5/index.html
  packages/static-build/test/fixtures/vite-v5/package-lock.json
  packages/static-build/test/fixtures/vite-v5/package.json
  packages/static-build/test/fixtures/vite-v5/probes.json
Labels: area: tests, area: static-build, pr: automerge

#10955 fix: Doc links in auth files
  .changeset/few-ants-pump.md
  packages/cli/src/util/config/get-default.ts
Labels: pr: automerge

#10965 [cli] replace `--deprecated` with `--update-required` in `vc project ls`
  .changeset/sweet-cougars-judge.md
  packages/cli/src/commands/project/command.ts
  packages/cli/src/commands/project/index.ts
  packages/cli/src/commands/project/list.ts
  packages/cli/test/unit/commands/project.test.ts
Labels: area: cli, semver: major, pr: automerge

#10967 [build-utils] Extend Node v16 discontinue date to 2024-06-15
  .changeset/pretty-walls-train.md
  packages/build-utils/src/fs/node-version.ts
  packages/build-utils/test/unit.test.ts
Labels: pr: automerge

#10977 Update nuxt logo
  .changeset/little-forks-approve.md
  packages/frameworks/logos/nuxt.svg
Labels: pr: automerge

#10978 [next] App Pages Prerender Manifest Update
  .changeset/twelve-walls-provide.md
  packages/next/src/utils.ts
Labels: pr: automerge

#10980 Remove unneeded global directives
  .changeset/sharp-lies-study.md
  packages/next/src/utils.ts
  packages/node/test/dev-fixtures/edge-buffer.js
  packages/node/test/dev-fixtures/edge-websocket.js
  packages/node/test/dev-fixtures/serverless-web.js
Labels: pr: automerge

#10968 [go] Remove `VERCEL_USE_GO_PROVIDED_RUNTIME` env var check
  .changeset/fluffy-ghosts-kick.md
  packages/go/src/index.ts
Labels: pr: automerge

#10969 [static-build] Add Angular 17 fixture
  .changeset/tiny-beans-warn.md
  packages/static-build/test/fixtures/angular-v17/.editorconfig
  packages/static-build/test/fixtures/angular-v17/.gitignore
  packages/static-build/test/fixtures/angular-v17/README.md
  packages/static-build/test/fixtures/angular-v17/angular.json
  packages/static-build/test/fixtures/angular-v17/package-lock.json
  packages/static-build/test/fixtures/angular-v17/package.json
  packages/static-build/test/fixtures/angular-v17/probes.json
  packages/static-build/test/fixtures/angular-v17/src/app/app.component.css
  packages/static-build/test/fixtures/angular-v17/src/app/app.component.html
  packages/static-build/test/fixtures/angular-v17/src/app/app.component.ts
  packages/static-build/test/fixtures/angular-v17/src/app/app.config.ts
  packages/static-build/test/fixtures/angular-v17/src/app/app.routes.ts
  packages/static-build/test/fixtures/angular-v17/src/assets/.gitkeep
  packages/static-build/test/fixtures/angular-v17/src/favicon.ico
  packages/static-build/test/fixtures/angular-v17/src/index.html
  packages/static-build/test/fixtures/angular-v17/src/main.ts
  packages/static-build/test/fixtures/angular-v17/src/styles.css
  packages/static-build/test/fixtures/angular-v17/tsconfig.app.json
  packages/static-build/test/fixtures/angular-v17/tsconfig.json
  packages/static-build/test/fixtures/angular-v17/tsconfig.spec.json
Labels: area: tests, area: static-build, pr: automerge

#10915 [node] Await waitUntil promises to resolve before exiting
  .changeset/light-knives-wonder.md
  packages/build-utils/src/types.ts
  packages/cli/src/util/dev/server.ts
  packages/node/package.json
  packages/node/src/dev-server.mts
  packages/node/src/edge-functions/edge-handler.mts
  packages/node/src/index.ts
  packages/node/src/serverless-functions/serverless-handler.mts
  packages/node/test/dev-fixtures/edge-waituntil.js
  packages/node/test/unit/dev.test.ts
  pnpm-lock.yaml
Labels: pr: automerge

#10989 Revert #10980
  .changeset/tiny-ravens-pretend.md
  packages/node/test/dev-fixtures/edge-buffer.js
  packages/node/test/dev-fixtures/edge-websocket.js
  packages/node/test/dev-fixtures/serverless-web.js
Labels: pr: automerge

#10986 [static-build] update ionic/angular to latest v7
  .changeset/big-files-watch.md
  packages/static-build/test/fixtures/ionic-angular-v7/package-lock.json
  packages/static-build/test/fixtures/ionic-angular-v7/package.json
Labels: area: tests, area: static-build, pr: automerge

#10984 [examples] Fix `ERR_PNPM_OUTDATED_LOCKFILE` when deploying SvelteKit example
  .changeset/plenty-suits-hang.md
  examples/sveltekit-1/pnpm-lock.yaml
  package.json
  pnpm-lock.yaml
Labels: pr: automerge
