Repository vercel/vercel, pull requests merged in 2023-08, with the labels that each got.

#10283 [cli] Migrate `login` command to new structure
  .changeset/moody-socks-serve.md
  packages/cli/src/commands/login/command.ts
  packages/cli/src/commands/login/index.ts
Labels: area: cli, semver: patch, pr: automerge

#10279 [cli] Migrate `redeploy` command to new structure
  .changeset/twenty-bulldogs-share.md
  packages/cli/src/commands/redeploy/command.ts
  packages/cli/src/commands/redeploy/index.ts
Labels: area: cli, semver: patch, pr: automerge

#10286 [cli] Migrate `build` command to new structure
  .changeset/soft-planes-travel.md
  packages/cli/src/commands/build/command.ts
  packages/cli/src/commands/build/index.ts
Labels: area: cli, semver: patch, pr: automerge

#10281 [cli] Migrate `logs` command to new structure
  .changeset/mighty-goats-thank.md
  packages/cli/src/commands/logs/command.ts
  packages/cli/src/commands/logs/index.ts
Labels: area: cli, semver: patch, pr: automerge

#10280 [cli] Migrate `pull` command to new structure
  .changeset/nine-wolves-exist.md
  packages/cli/src/commands/pull/command.ts
  packages/cli/src/commands/pull/index.ts
Labels: area: cli, semver: patch, pr: automerge

#10282 [cli] Migrate `logout` command to new structure
  .changeset/olive-trees-do.md
  packages/cli/src/commands/logout/command.ts
  packages/cli/src/commands/logout/index.ts
Labels: area: cli, semver: patch, pr: automerge

#10266 [cli] Migrate `whoami` to new command structure
  .changeset/lazy-goats-march.md
  packages/cli/src/commands/whoami.ts
  packages/cli/src/commands/whoami/command.ts
  packages/cli/src/commands/whoami/index.ts
Labels: area: cli, semver: patch, pr: automerge

#10285 [cli] Migrate `link` command to new structure
  .changeset/witty-tips-occur.md
  packages/cli/src/commands/link/command.ts
  packages/cli/src/commands/link/index.ts
Labels: area: cli, semver: patch, pr: automerge

#10287 [cli] Update spacing on `--help` output
  .changeset/young-masks-shake.md
  packages/cli/src/commands/help.ts
  packages/cli/test/unit/commands/__snapshots__/help.test.ts.snap
Labels: area: cli, semver: patch, pr: automerge

#10288 fix: compress condition
  .changeset/tricky-months-bow.md
  packages/cli/test/dev/fixtures/43-compress-encoding/api/index.js
  packages/cli/test/dev/integration-4.test.ts
  packages/node/src/serverless-functions/serverless-handler.mts
Labels: area: node, area: dev, semver: patch, pr: automerge

#10291 [remix] Disable root workspace check in pnpm and yarn when adding deps
  .changeset/little-clouds-pump.md
  packages/remix/src/utils.ts
Labels: pr: automerge

#10292 [node] Move `@types/content-type` to dev dependency
  .changeset/clean-wasps-beg.md
  packages/node/package.json
  pnpm-lock.yaml
Labels: pr: automerge

#10309 Remove unused code
  .changeset/ten-beers-unite.md
  packages/cli/package.json
  packages/cli/src/util/credit-cards.js
  pnpm-lock.yaml
Labels: area: cli, pr: automerge

#10303 Handle calls for deployment aliases when mocking deployment API
  .changeset/spotty-windows-suffer.md
  packages/cli/test/mocks/deployment.ts
Labels: area: cli, semver: patch, pr: automerge

#10275 [next] Preserve sourceMappingURL comments in template literals
  .changeset/dry-cycles-eat.md
  packages/next/src/sourcemapped.ts
  packages/next/test/unit/sourcemapped.test.ts
Labels: area: next, pr: automerge

#10310 chore(ci): fix turbo logs to no longer group
  .changeset/new-carrots-heal.md
  .github/workflows/test.yml
Labels: area: tests, pr: automerge

#10304 Add basic tests for remove command
  .changeset/lovely-donuts-suffer.md
  packages/cli/test/unit/commands/remove.test.ts
Labels: area: cli, semver: patch, pr: automerge

#10297 Update discussion templates
  .changeset/famous-dolls-roll.md
  .github/DISCUSSION_TEMPLATE/general.yml
  .github/DISCUSSION_TEMPLATE/help.yml
  .github/DISCUSSION_TEMPLATE/ideas.yml
  .github/DISCUSSION_TEMPLATE/polls.yml
  .github/DISCUSSION_TEMPLATE/show-and-tell.yml
  .github/DISCUSSION_TEMPLATE/temporary.yml
Labels: area: docs, pr: automerge

#10315 [build-utils] Fix `getPrefixedEnvVars()` to handle `VERCEL_BRANCH_URL`
  .changeset/silver-items-retire.md
  packages/build-utils/src/get-prefixed-env-vars.ts
  packages/build-utils/test/unit.get-prefixed-env-vars.test.ts
Labels: area: build-utils, semver: patch, pr: automerge

#10311 [cli] Sanitize argv for `vc build`
  .changeset/great-dolls-sell.md
  packages/cli/src/commands/build/index.ts
  packages/cli/src/util/build/scrub-argv.ts
  packages/cli/test/unit/util/build/scrub-argv.test.ts
Labels: pr: automerge

#10320 [frameworks] Add "(v1)" suffix to "hydrogen" preset
  .changeset/sour-ghosts-repair.md
  packages/frameworks/src/frameworks.ts
Labels: pr: automerge

#10323 [cli] tidy up use of package name and logo
  .changeset/wet-ligers-listen.md
  packages/cli/src/args.ts
  packages/cli/src/commands/alias/index.ts
  packages/cli/src/commands/bisect/command.ts
  packages/cli/src/commands/build/command.ts
  packages/cli/src/commands/build/index.ts
  packages/cli/src/commands/certs/index.ts
  packages/cli/src/commands/dev/index.ts
  packages/cli/src/commands/dns/index.ts
  packages/cli/src/commands/domains/index.ts
  packages/cli/src/commands/env/index.ts
  packages/cli/src/commands/git/index.ts
  packages/cli/src/commands/init/index.ts
  packages/cli/src/commands/inspect/command.ts
  packages/cli/src/commands/link/command.ts
  packages/cli/src/commands/list/command.ts
  packages/cli/src/commands/login/command.ts
  packages/cli/src/commands/logout/command.ts
  packages/cli/src/commands/logs/command.ts
  packages/cli/src/commands/project/index.ts
  packages/cli/src/commands/promote/index.ts
  packages/cli/src/commands/promote/status.ts
  packages/cli/src/commands/pull/command.ts
  packages/cli/src/commands/redeploy/command.ts
  packages/cli/src/commands/remove/command.ts
  packages/cli/src/commands/rollback/index.ts
  packages/cli/src/commands/rollback/status.ts
  packages/cli/src/commands/secrets.js
  packages/cli/src/commands/teams/add.ts
  packages/cli/src/commands/teams/index.ts
  packages/cli/src/commands/teams/list.ts
  packages/cli/src/commands/whoami/command.ts
  packages/cli/src/util/get-update-command.ts
  packages/cli/src/util/output/logo.ts
  packages/cli/src/util/pkg-name.ts
  packages/cli/test/integration-3.test.ts
Labels: area: cli, pr: automerge

#10325 [fs-detectors] Fix "hydrogen-2" detection unit test
  .changeset/heavy-zoos-taste.md
  packages/fs-detectors/test/unit.examples.test.ts
Labels: area: tests, pr: automerge, semver: none

#10324 [frameworks] Use parenthesis on Docusaurus and SvelteKit "name" fields
  .changeset/swift-clouds-approve.md
  packages/frameworks/src/frameworks.ts
Labels: pr: automerge

#10255 [node] bump edge-runtime to 2.4.4
  .changeset/famous-timers-mix.md
  packages/node/package.json
  pnpm-lock.yaml
Labels: pr: automerge

#10328 Fixes for changeset from #10255
  .changeset/famous-timers-mix.md
  .changeset/nine-geckos-tease.md
Labels: pr: automerge

#10063 [examples] Update Storybook template
  .changeset/grumpy-toys-tell.md
  examples/storybook/README.md
  examples/storybook/app/api/hello/route.ts
  examples/storybook/next.config.js
  examples/storybook/package.json
Labels: area: examples, pr: automerge

#10337 [cli] Respect `--yes` flag for all prompts during `vc link --repo`
  .changeset/khaki-weeks-cry.md
  packages/cli/src/util/link/repo.ts
Labels: pr: automerge

#10340 [examples] Update "hydrogen-2" template readme
  .changeset/twelve-weeks-sparkle.md
  examples/hydrogen-2/README.md
Labels: pr: automerge

#10342 [cli] Use `vercel-php@0.6.0` in e2e test fixture
  .changeset/brown-monkeys-melt.md
  packages/cli/test/helpers/prepare.js
Labels: pr: automerge

#10338 [cli] fix tyops
  .changeset/short-boats-protect.md
  packages/cli/src/commands/help.ts
Labels: pr: automerge

#10355 [build-utils] Fix Node 14.x tests
  .changeset/brave-jokes-impress.md
  packages/build-utils/test/unit.test.ts
Labels: pr: automerge

#7326 [frameworks] Amend Hugo default `buildCommand` to exclude drafts enabled flag
  .changeset/fair-zebras-applaud.md
  packages/frameworks/src/frameworks.ts
Labels: area: frameworks, semver: patch, pr: automerge

#10358 v31.4.0
  .changeset/shaggy-apes-relate.md
Labels: pr: automerge

#10345 [frameworks][fs-detectors] Add "supersedes" prop to Framework interface
  .changeset/odd-kangaroos-fix.md
  packages/frameworks/src/frameworks.ts
  packages/frameworks/src/types.ts
  packages/frameworks/test/frameworks.unit.test.ts
  packages/fs-detectors/src/detect-framework.ts
  packages/fs-detectors/test/unit.framework-detector.test.ts
Labels: pr: automerge

#10364 [remix] Only add workspace check flag for Yarn v1
  .changeset/stupid-pumpkins-crash.md
  packages/remix/src/utils.ts
Labels: pr: automerge

#10365 Exclude Gatsby from default 404 error route
  .changeset/metal-ears-battle.md
  packages/fs-detectors/src/detect-builders.ts
  packages/gatsby-plugin-vercel-builder/src/index.ts
  packages/static-build/test/fixtures/gatsby-v5-pathPrefix/probes.json
  packages/static-build/test/fixtures/gatsby-v5-pathPrefix/src/pages/404.js
Labels: area: static-build, area: fs-detectors, pr: automerge, area: gatsby-plugin-vercel-builder

#10369 BREAKING CHANGE: Drop Node.js 14, bump minimum to Node.js 16
  .changeset/neat-rabbits-live.md
  api/tsconfig.json
  examples/hydrogen/tsconfig.json
  internals/tsconfig/tsconfig.json
  packages/build-utils/tsconfig.json
  packages/cli/package.json
  packages/cli/src/util/dev/router.ts
  packages/cli/tsconfig.json
  packages/client/package.json
  packages/client/tsconfig.json
  packages/edge/tsconfig.json
  packages/error-utils/tsconfig.json
  packages/frameworks/tsconfig.json
  packages/fs-detectors/tsconfig.json
  packages/gatsby-plugin-vercel-builder/tsconfig.base.json
  packages/go/tsconfig.json
  packages/hydrogen/tsconfig.json
  packages/next/tsconfig.json
  packages/node/tsconfig.json
  packages/python/tsconfig.json
  packages/redwood/tsconfig.json
  packages/remix/tsconfig.json
  packages/routing-utils/tsconfig.json
  packages/ruby/tsconfig.json
  packages/static-build/tsconfig.json
  packages/static-config/tsconfig.json
  utils/tsconfig.json
Labels: pr: automerge

#10378 [error-utils] fix `files` in package.json to use `dist`
  .changeset/fuzzy-yaks-judge.md
  internals/constants/package.json
  internals/get-package-json/package.json
  internals/types/package.json
  packages/error-utils/package.json
Labels: pr: automerge

#10380 [frameworks] move some `devDependencies` to `dependencies`
  .changeset/cyan-trains-sneeze.md
  packages/frameworks/package.json
  pnpm-lock.yaml
Labels: pr: automerge

#10382 [cli] Add `--git-branch` to pull command help output
  .changeset/dry-maps-draw.md
  packages/cli/src/commands/pull/command.ts
Labels: pr: automerge

#10379 [cli] Update `dns` commands to new structure
  .changeset/soft-ties-applaud.md
  packages/cli/src/commands/dns/command.ts
  packages/cli/src/commands/dns/index.ts
Labels: area: cli, pr: automerge

#10388 [next] fix RSC matching behavior & 404 status code on `fallback: false`
  .changeset/dirty-glasses-double.md
  packages/next/src/server-build.ts
  packages/next/src/utils.ts
  packages/next/test/fixtures/00-app-dir-catchall-pages/app/[lang]/[...all]/page.js
  packages/next/test/fixtures/00-app-dir-catchall-pages/app/[lang]/layout.js
  packages/next/test/fixtures/00-app-dir-catchall-pages/app/[lang]/page.js
  packages/next/test/fixtures/00-app-dir-catchall-pages/index.test.js
  packages/next/test/fixtures/00-app-dir-catchall-pages/next.config.js
  packages/next/test/fixtures/00-app-dir-catchall-pages/package.json
  packages/next/test/fixtures/00-app-dir-catchall-pages/pages/[lang]/about.js
  packages/next/test/fixtures/00-app-dir-catchall-pages/probes.json
  packages/next/test/fixtures/00-fallback-false-404/index.test.js
  packages/next/test/fixtures/00-fallback-false-404/next.config.js
  packages/next/test/fixtures/00-fallback-false-404/package.json
  packages/next/test/fixtures/00-fallback-false-404/pages/api/hello.js
  packages/next/test/fixtures/00-fallback-false-404/pages/blog/[slug].js
  packages/next/test/fixtures/00-fallback-false-404/probes.json
Labels: pr: automerge

#10389 [cli] Remove mri package
  .changeset/fair-cycles-pretend.md
  packages/cli/package.json
  packages/cli/src/commands/secrets.js
  packages/cli/src/commands/teams/list.ts
  packages/cli/src/util/get-prefixed-flags.ts
  pnpm-lock.yaml
Labels: pr: automerge

#10396 [cli] Improve error messages for JSON parse issues
  .changeset/good-rules-carry.md
  packages/cli/package.json
  packages/cli/src/commands/dev/index.ts
  packages/cli/src/commands/env/pull.ts
  packages/cli/src/util/build/corepack.ts
  packages/cli/src/util/dev/server.ts
  packages/cli/src/util/errors-ts.ts
  packages/cli/src/util/read-json-file.ts
  pnpm-lock.yaml
Labels: pr: automerge

#10395 [examples] fix redwood template and update examples to use at least node@16
  .changeset/stupid-paws-press.md
  examples/polymer/package.json
  examples/redwoodjs/package.json
  examples/remix/package.json
  examples/umijs/package.json
  examples/vuepress/package.json
Labels: pr: automerge

#10410 Keep `vercel@canary` up to date with `vercel@latest`
  .changeset/dry-masks-thank.md
  package.json
  utils/update-canary-tags.mjs
Labels: pr: automerge

#10417 fix: remove console.log
  .changeset/smooth-gifts-suffer.md
  packages/node/src/serverless-functions/serverless-handler.mts
Labels: area: node

#10425 migrate `promote` command structure for help output
  .changeset/small-points-type.md
  packages/cli/src/commands/help.ts
  packages/cli/src/commands/promote/command.ts
  packages/cli/src/commands/promote/index.ts
Labels: pr: automerge

#10426 migrate `rollback` command structure for help output
  .changeset/happy-rivers-rule.md
  packages/cli/src/commands/rollback/command.ts
  packages/cli/src/commands/rollback/index.ts
Labels: pr: automerge

#10431 migrate `git` command structure for help output
  .changeset/stupid-vans-leave.md
  packages/cli/src/commands/git/command.ts
  packages/cli/src/commands/git/index.ts
Labels: pr: automerge

#10428 migrate `init` command structure for help output
  .changeset/lucky-roses-pump.md
  packages/cli/src/commands/init/command.ts
  packages/cli/src/commands/init/index.ts
Labels: pr: automerge

#10432 [cli] Update `project` command to new structure
  .changeset/tidy-ducks-dream.md
  packages/cli/src/commands/project/command.ts
  packages/cli/src/commands/project/index.ts
Labels: pr: automerge

#10429 migrate `env` to command structure
  .changeset/eighty-rockets-help.md
  packages/cli/src/commands/env/command.ts
  packages/cli/src/commands/env/index.ts
Labels: pr: automerge
