Repository vercel/vercel, pull requests merged in 2024-03, with the labels that each got.

#11203 [examples] Bump Middleman and Jekyll dependencies to support ruby 3.x
  .changeset/angry-mirrors-care.md
  examples/jekyll/Gemfile
  examples/jekyll/Gemfile.lock
  examples/middleman/Gemfile
  examples/middleman/Gemfile.lock
Labels: pr: automerge

#11223 [tests] Update dependabot.yml to ignore major/patch
  .changeset/sweet-mice-knock.md
  .github/dependabot.yml
Labels: pr: automerge

#11217 [examples] Update Remix template to use Vite
  .changeset/soft-trainers-fold.md
  examples/remix/.gitignore
  examples/remix/app/root.tsx
  examples/remix/package.json
  examples/remix/remix.config.js
  examples/remix/remix.env.d.ts
  examples/remix/tsconfig.json
  examples/remix/vite.config.ts
Labels: pr: automerge

#11227 Revert "[examples] Update Remix template to use Vite (#11217)"
  .changeset/soft-trainers-fold.md
  examples/remix/.gitignore
  examples/remix/app/root.tsx
  examples/remix/package.json
  examples/remix/remix.config.js
  examples/remix/remix.env.d.ts
  examples/remix/tsconfig.json
  examples/remix/vite.config.ts
Labels: pr: automerge

#11229 [examples] Update Remix template to use Vite
  .changeset/soft-trainers-fold.md
  examples/remix/.gitignore
  examples/remix/app/root.tsx
  examples/remix/package.json
  examples/remix/remix.config.js
  examples/remix/remix.env.d.ts
  examples/remix/tsconfig.json
  examples/remix/vite.config.ts
Labels: pr: automerge

#11230 [cli] Fix failing test due to npm default change
  .changeset/smart-impalas-bow.md
  packages/cli/test/integration-3.test.ts
Labels: pr: automerge

#11213 [remix] Remove usage of `ensureResolvable()` in Vite builds
  .changeset/selfish-insects-hide.md
  packages/remix/src/build-vite.ts
  packages/remix/src/utils.ts
Labels: pr: automerge

#11247 [static-build] Remove Build Output API v1 tests
  .changeset/chilled-toes-allow.md
  packages/static-build/test/fixtures/61-build-output-directory/.gitignore
  packages/static-build/test/fixtures/61-build-output-directory/fake/config/routes.json
  packages/static-build/test/fixtures/61-build-output-directory/fake/functions/node/about/index.js
  packages/static-build/test/fixtures/61-build-output-directory/fake/functions/node/about/util.js
  packages/static-build/test/fixtures/61-build-output-directory/fake/functions/node/esm/index.mjs
  packages/static-build/test/fixtures/61-build-output-directory/fake/functions/node/esm/other.mjs
  packages/static-build/test/fixtures/61-build-output-directory/fake/functions/node/product/index.js
  packages/static-build/test/fixtures/61-build-output-directory/fake/functions/node/product/info/index.js
  packages/static-build/test/fixtures/61-build-output-directory/fake/functions/node/root/index.js
  packages/static-build/test/fixtures/61-build-output-directory/package.json
  packages/static-build/test/fixtures/61-build-output-directory/probes.json
  packages/static-build/test/fixtures/62-build-output-directory-with-public/.gitignore
  packages/static-build/test/fixtures/62-build-output-directory-with-public/fake/config/routes.json
  packages/static-build/test/fixtures/62-build-output-directory-with-public/fake/functions/node/about/index.js
  packages/static-build/test/fixtures/62-build-output-directory-with-public/fake/functions/node/about/util.js
  packages/static-build/test/fixtures/62-build-output-directory-with-public/fake/functions/node/esm/index.mjs
  packages/static-build/test/fixtures/62-build-output-directory-with-public/fake/functions/node/esm/other.mjs
  packages/static-build/test/fixtures/62-build-output-directory-with-public/fake/functions/node/product/index.js
  packages/static-build/test/fixtures/62-build-output-directory-with-public/fake/functions/node/product/info/index.js
  packages/static-build/test/fixtures/62-build-output-directory-with-public/fake/functions/node/root/index.js
  packages/static-build/test/fixtures/62-build-output-directory-with-public/package.json
  packages/static-build/test/fixtures/62-build-output-directory-with-public/vercel.json
  packages/static-build/test/fixtures/63-build-output-directory-with-static/.gitignore
  packages/static-build/test/fixtures/63-build-output-directory-with-static/fake/config/images.json
  packages/static-build/test/fixtures/63-build-output-directory-with-static/fake/config/routes.json
  packages/static-build/test/fixtures/63-build-output-directory-with-static/fake/static/hello.txt
  packages/static-build/test/fixtures/63-build-output-directory-with-static/fake/static/logo.png
  packages/static-build/test/fixtures/63-build-output-directory-with-static/package.json
  packages/static-build/test/fixtures/63-build-output-directory-with-static/probes.json
  packages/static-build/test/fixtures/65-build-output-directory-with-legacy-node-functions/.gitignore
  packages/static-build/test/fixtures/65-build-output-directory-with-legacy-node-functions/fake/config/functions.json
  packages/static-build/test/fixtures/65-build-output-directory-with-legacy-node-functions/fake/config/routes.json
  packages/static-build/test/fixtures/65-build-output-directory-with-legacy-node-functions/fake/functions/node/my-function/index.js
  packages/static-build/test/fixtures/65-build-output-directory-with-legacy-node-functions/fake/functions/node/my-function/sleep.js
  packages/static-build/test/fixtures/65-build-output-directory-with-legacy-node-functions/package.json
  packages/static-build/test/fixtures/65-build-output-directory-with-legacy-node-functions/probes.json
  packages/static-build/test/fixtures/66-build-output-directory-with-functions/.gitignore
  packages/static-build/test/fixtures/66-build-output-directory-with-functions/build.js
  packages/static-build/test/fixtures/66-build-output-directory-with-functions/fake/config/functions.json
  packages/static-build/test/fixtures/66-build-output-directory-with-functions/fake/config/routes.json
  packages/static-build/test/fixtures/66-build-output-directory-with-functions/fake/functions/sleeper/index.js
  packages/static-build/test/fixtures/66-build-output-directory-with-functions/fake/functions/sleeper/sleep.js
  packages/static-build/test/fixtures/66-build-output-directory-with-functions/go-source/main.go
  packages/static-build/test/fixtures/66-build-output-directory-with-functions/package.json
  packages/static-build/test/fixtures/66-build-output-directory-with-functions/probes.json
  packages/static-build/test/fixtures/74-build-output-directory-with-build-config/.gitignore
  packages/static-build/test/fixtures/74-build-output-directory-with-build-config/fake/config/build.json
  packages/static-build/test/fixtures/74-build-output-directory-with-build-config/fake/config/routes.json
  packages/static-build/test/fixtures/74-build-output-directory-with-build-config/fake/functions/node/about/index.js
  packages/static-build/test/fixtures/74-build-output-directory-with-build-config/fake/functions/node/about/util.js
  packages/static-build/test/fixtures/74-build-output-directory-with-build-config/fake/functions/node/esm/index.mjs
  packages/static-build/test/fixtures/74-build-output-directory-with-build-config/fake/functions/node/esm/other.mjs
  packages/static-build/test/fixtures/74-build-output-directory-with-build-config/fake/functions/node/product/index.js
  packages/static-build/test/fixtures/74-build-output-directory-with-build-config/fake/functions/node/product/info/index.js
  packages/static-build/test/fixtures/74-build-output-directory-with-build-config/fake/functions/node/root/index.js
  packages/static-build/test/fixtures/74-build-output-directory-with-build-config/package.json
  packages/static-build/test/fixtures/74-build-output-directory-with-build-config/probes.json
Labels: area: static-build, pr: automerge

#11121 [cli][build-utils] Rename variants to flags
  .changeset/fair-meals-clap.md
  packages/build-utils/src/types.ts
  packages/cli/src/commands/build/index.ts
  packages/cli/test/fixtures/unit/commands/build/with-flags/.vercel/project.json
  packages/cli/test/fixtures/unit/commands/build/with-flags/build.js
  packages/cli/test/fixtures/unit/commands/build/with-flags/config.json
  packages/cli/test/fixtures/unit/commands/build/with-flags/flags.json
  packages/cli/test/fixtures/unit/commands/build/with-flags/package.json
  packages/cli/test/unit/commands/build/index.test.ts
  packages/next/src/server-build.ts
  packages/next/src/utils.ts
Labels: area: build-utils, area: cli, area: next, pr: automerge

#11242 [build-utils] Remove `VERCEL_ENABLE_NPM_DEFAULT` env var check
  .changeset/selfish-flowers-explode.md
  packages/build-utils/src/fs/run-user-scripts.ts
  packages/build-utils/test/fixtures/40-no-lockfile/vercel.json
  packages/build-utils/test/unit.test.ts
Labels: pr: automerge, pending-merge

#11253 [tests] Specify testing tsconfig path for Jest
  .changeset/slimy-eyes-knock.md
  packages/cli/jest.config.js
  packages/frameworks/jest.config.js
  packages/go/jest.config.js
  packages/next/jest.config.js
  packages/node/jest.config.js
  packages/static-build/jest.config.js
  packages/static-config/jest.config.js
Labels: pr: automerge

#11256 [remix] Improve hueristics for detecting Remix + Vite
  .changeset/wicked-students-obey.md
  packages/remix/src/build.ts
  packages/remix/src/utils.ts
  packages/remix/test/fixtures-unit/by-build-command/package.json
  packages/remix/test/fixtures-unit/by-build-command/remix.config.js
  packages/remix/test/fixtures-unit/by-build-command/vite.config.ts
  packages/remix/test/fixtures-unit/by-vite-config-legacy/package.json
  packages/remix/test/fixtures-unit/by-vite-config-legacy/remix.config.js
  packages/remix/test/fixtures-unit/by-vite-config-legacy/vite.config.ts
  packages/remix/test/fixtures-unit/by-vite-config/package.json
  packages/remix/test/fixtures-unit/by-vite-config/remix.config.js
  packages/remix/test/fixtures-unit/by-vite-config/vite.config.ts
  packages/remix/test/fixtures-vite/01-no-preset/vercel.json
  packages/remix/test/fixtures-vite/02-interactive-remix-routing-v2/vercel.json
  packages/remix/test/unit.is-vite.test.ts
Labels: pr: automerge

#11212 [cli] Fix framework version detection in monorepos
  .changeset/rich-wombats-knock.md
  .eslintignore
  packages/cli/src/commands/build/index.ts
  packages/cli/test/fixtures/unit/commands/build/monorepo/.vercel/project.json
  packages/cli/test/fixtures/unit/commands/build/monorepo/apps/nextjs/.gitignore
  packages/cli/test/fixtures/unit/commands/build/monorepo/apps/nextjs/next.config.js
  packages/cli/test/fixtures/unit/commands/build/monorepo/apps/nextjs/package.json
  packages/cli/test/fixtures/unit/commands/build/monorepo/apps/nextjs/pages/index.jsx
  packages/cli/test/fixtures/unit/commands/build/monorepo/package-lock.json
  packages/cli/test/fixtures/unit/commands/build/monorepo/package.json
  packages/cli/test/unit/commands/build/index.test.ts
Labels: pr: automerge

#11272 Update CODEOWNERS to ensure Zero Config can always approve
  .changeset/bright-trees-smash.md
  .github/CODEOWNERS
Labels: pr: automerge

#11270 Fix README links
  .changeset/smooth-goats-double.md
  README.md
  examples/README.md
  examples/hydrogen-2/README.md
  examples/remix/README.md
  examples/sanity/README.md
Labels: pr: automerge

#11268 [cli] stops warning Next.js users about legacy Speed Insights
  .changeset/cold-carrots-kick.md
  packages/cli/src/commands/build/index.ts
  packages/cli/test/unit/commands/build/index.test.ts
Labels: area: cli, pr: automerge

#11259 [next] Ensure all static routes have static streaming lambda path
  .changeset/brave-parrots-walk.md
  packages/next/src/index.ts
  packages/next/src/server-build.ts
  packages/next/src/utils.ts
  packages/next/test/fixtures/00-app-dir-ppr-full/components/dynamic.jsx
  packages/next/test/fixtures/00-app-dir-ppr-full/index.test.js
Labels: pr: automerge

#11277 [cli] Don't send `projectSettings.nodeVersion` for unsupported versions
  .changeset/proud-kangaroos-sneeze.md
  .changeset/purple-brooms-brake.md
  packages/build-utils/src/index.ts
  packages/cli/src/commands/deploy/index.ts
  packages/cli/test/fixtures/unit/.gitignore
  packages/cli/test/fixtures/unit/commands/deploy/node-low-starting-range/.vercel/project.json
  packages/cli/test/fixtures/unit/commands/deploy/node-low-starting-range/api/index.js
  packages/cli/test/fixtures/unit/commands/deploy/node-low-starting-range/package.json
  packages/cli/test/fixtures/unit/commands/deploy/node-low-version/.vercel/project.json
  packages/cli/test/fixtures/unit/commands/deploy/node-low-version/api/index.js
  packages/cli/test/fixtures/unit/commands/deploy/node-low-version/package.json
  packages/cli/test/unit/commands/deploy.test.ts
Labels: pr: automerge

#11281 [remix] Disable `prepareCache()` npm install for Remix + Vite
  .changeset/five-bags-trade.md
  packages/remix/src/prepare-cache.ts
Labels: pr: automerge

#11287 Updated port number of localhost in README.md
  examples/remix/README.md
Labels: pr: automerge

#11257 [remix] Add SPA mode e2e tests
  .changeset/eleven-pants-attack.md
  packages/remix/test/fixtures-vite/03-spa-no-preset/.gitignore
  packages/remix/test/fixtures-vite/03-spa-no-preset/app/entry.client.tsx
  packages/remix/test/fixtures-vite/03-spa-no-preset/app/entry.server.tsx
  packages/remix/test/fixtures-vite/03-spa-no-preset/app/root.tsx
  packages/remix/test/fixtures-vite/03-spa-no-preset/app/routes/_index.tsx
  packages/remix/test/fixtures-vite/03-spa-no-preset/env.d.ts
  packages/remix/test/fixtures-vite/03-spa-no-preset/package-lock.json
  packages/remix/test/fixtures-vite/03-spa-no-preset/package.json
  packages/remix/test/fixtures-vite/03-spa-no-preset/probes.json
  packages/remix/test/fixtures-vite/03-spa-no-preset/public/favicon.ico
  packages/remix/test/fixtures-vite/03-spa-no-preset/tsconfig.json
  packages/remix/test/fixtures-vite/03-spa-no-preset/vite.config.ts
  packages/remix/test/fixtures-vite/04-spa-with-vercel-preset/.gitignore
  packages/remix/test/fixtures-vite/04-spa-with-vercel-preset/README.md
  packages/remix/test/fixtures-vite/04-spa-with-vercel-preset/app/entry.client.tsx
  packages/remix/test/fixtures-vite/04-spa-with-vercel-preset/app/entry.server.tsx
  packages/remix/test/fixtures-vite/04-spa-with-vercel-preset/app/root.tsx
  packages/remix/test/fixtures-vite/04-spa-with-vercel-preset/app/routes/_index.tsx
  packages/remix/test/fixtures-vite/04-spa-with-vercel-preset/env.d.ts
  packages/remix/test/fixtures-vite/04-spa-with-vercel-preset/package-lock.json
  packages/remix/test/fixtures-vite/04-spa-with-vercel-preset/package.json
  packages/remix/test/fixtures-vite/04-spa-with-vercel-preset/probes.json
  packages/remix/test/fixtures-vite/04-spa-with-vercel-preset/public/favicon.ico
  packages/remix/test/fixtures-vite/04-spa-with-vercel-preset/tsconfig.json
  packages/remix/test/fixtures-vite/04-spa-with-vercel-preset/vite.config.ts
Labels: pr: automerge

#11171 [tests] Add ionic-angular@7 fixtures to dependabot
  .changeset/curly-eyes-travel.md
  .github/dependabot.yml
Labels: pr: automerge

#11276 [cli][tests] Fix `getUpdateCommand` for local dev
  .changeset/sour-experts-dress.md
  packages/cli/src/util/get-update-command.ts
  packages/cli/test/unit/util/get-update-command.test.ts
Labels: pr: automerge

#11291 [tests] Add dependabot for Nuxt
  .changeset/tasty-bikes-push.md
  .github/dependabot.yml
Labels: pr: automerge

#11295 Update CODEOWNERS
  .changeset/spicy-icons-serve.md
  .github/CODEOWNERS
Labels: pr: automerge

#11307 [remix] Add `mjs` and `mts` extensions to vite detection
  .changeset/slimy-nails-rescue.md
  packages/remix/src/utils.ts
Labels: pr: automerge

#11167 [tests] add stencil@4 fixtures to dependabot
  .changeset/neat-tigers-pay.md
  .github/dependabot.yml
Labels: pr: automerge

#11029 [build-utils] Allow environment variables to be specified for `EdgeFunction`
  .changeset/tall-cups-laugh.md
  packages/build-utils/src/edge-function.ts
  packages/build-utils/src/lambda.ts
Labels: pr: automerge

#11284 chore: remove repetitive words
  .changeset/strange-garlics-count.md
  examples/hugo/themes/ananke/exampleSite/content/contact.md
  packages/cli/src/util/config/global-path.ts
  packages/cli/src/util/input/text.ts
  packages/cli/test/dev/fixtures/08-hugo/themes/ananke/exampleSite/content/contact.md
  packages/remix/src/utils.ts
  packages/static-build/test/fixtures/hugo-v0/themes/ananke/exampleSite/content/contact.md
Labels: pr: automerge

#11316 [cli] extract `isZeroConfigBuild` into utility function
  .changeset/selfish-houses-attack.md
  packages/cli/src/commands/deploy/index.ts
  packages/cli/src/util/is-zero-config-build.ts
  packages/cli/src/util/link/setup-and-link.ts
  packages/cli/test/unit/util/is-zero-config-build.test.ts
Labels: pr: automerge

#11333 IAM 1720 Added sunset warning to the secrets command
  .changeset/forty-gifts-film.md
  packages/cli/src/commands/secrets/command.js
  packages/cli/src/commands/secrets/index.js
Labels: pr: automerge

#11254 [next] add x-forwarded-port test
  .changeset/healthy-candles-arrive.md
  packages/next/test/fixtures/00-app-dir-ppr/app/api/app-headers/route.js
  packages/next/test/fixtures/00-app-dir-ppr/pages/api/pages-headers.js
  packages/next/test/fixtures/00-app-dir-ppr/vercel.json
Labels: pr: automerge

#11350 Revert "[cli] extract `isZeroConfigBuild` into utility function (#11316)"
  .changeset/good-islands-learn.md
  packages/cli/src/commands/deploy/index.ts
  packages/cli/src/util/is-zero-config-build.ts
  packages/cli/src/util/link/setup-and-link.ts
  packages/cli/test/unit/util/is-zero-config-build.test.ts
Labels: pr: automerge

#11343 Update CODEOWNERS
  .changeset/small-games-divide.md
  .github/CODEOWNERS
Labels: pr: automerge

#11309 [cli][client] Handle `--repo` linked in `vc deploy --prebuilt`
  .changeset/fluffy-berries-return.md
  packages/cli/src/commands/deploy/index.ts
  packages/cli/src/util/deploy/get-prebuilt-json.ts
  packages/cli/src/util/deploy/process-deployment.ts
  packages/cli/src/util/index.ts
  packages/client/src/types.ts
  packages/client/src/utils/index.ts
  packages/client/tests/fixtures/monorepo-boa/apps/blog/.gitignore
  packages/client/tests/fixtures/monorepo-boa/apps/blog/.vercel/output/functions/api/another.func/.vc-config.json
  packages/client/tests/fixtures/monorepo-boa/apps/blog/.vercel/output/functions/api/example.func/.vc-config.json
  packages/client/tests/fixtures/monorepo-boa/apps/blog/.vercel/output/static/baz.txt
  packages/client/tests/fixtures/monorepo-boa/apps/blog/.vercel/output/static/sub/qux.txt
  packages/client/tests/fixtures/monorepo-boa/apps/blog/foo.txt
  packages/client/tests/fixtures/monorepo-boa/apps/blog/sub/bar.txt
  packages/client/tests/fixtures/monorepo-boa/foo.txt
  packages/client/tests/fixtures/monorepo-boa/sub/bar.txt
  packages/client/tests/unit.utils.test.ts
Labels: pr: automerge
