Repository vercel/vercel, pull requests merged in 2024-02, with the labels that each got.

#11111 [build-utils] Update variants type
  .changeset/small-pets-yawn.md
  packages/build-utils/src/types.ts
Labels: area: build-utils, pr: automerge

#11115 [node][next][redwood][remix] bump `@vercel/nft@0.26.3`
  .changeset/dull-geckos-sing.md
  packages/next/package.json
  packages/node/package.json
  packages/redwood/package.json
  packages/remix/package.json
  pnpm-lock.yaml
Labels: area: node, area: redwood, area: next, area: remix, pr: automerge

#11090 [static-build] Add a new Astro@4 fixture
  .changeset/nasty-badgers-beg.md
  packages/static-build/test/fixtures/astro-v4/.gitignore
  packages/static-build/test/fixtures/astro-v4/.vercelignore
  packages/static-build/test/fixtures/astro-v4/astro.config.mjs
  packages/static-build/test/fixtures/astro-v4/package-lock.json
  packages/static-build/test/fixtures/astro-v4/package.json
  packages/static-build/test/fixtures/astro-v4/probes.json
  packages/static-build/test/fixtures/astro-v4/src/components/Card.astro
  packages/static-build/test/fixtures/astro-v4/src/env.d.ts
  packages/static-build/test/fixtures/astro-v4/src/layouts/Layout.astro
  packages/static-build/test/fixtures/astro-v4/src/pages/another-page.astro
  packages/static-build/test/fixtures/astro-v4/src/pages/index.astro
Labels: pr: automerge

#11131 [build-utils] change default package manager when no lockfile detected from `yarn` to `npm` (gated behind feature flag)
  .changeset/shy-bikes-whisper.md
  packages/build-utils/src/fs/run-user-scripts.ts
  packages/build-utils/test/fixtures/07-cross-install/api/yarn.lock
  packages/build-utils/test/fixtures/07-cross-install/lib/yarn.lock
  packages/build-utils/test/fixtures/08-yarn-npm/with-yarn/yarn.lock
  packages/build-utils/test/fixtures/40-no-lockfile/package.json
  packages/build-utils/test/fixtures/40-no-lockfile/probes.json
  packages/build-utils/test/fixtures/40-no-lockfile/vercel.json
  packages/build-utils/test/unit.test.ts
  packages/remix/test/fixtures/11-hydrogen-2-js/pnpm-lock.yaml
Labels: area: build-utils, pr: automerge

#11135 Revert "Default ruby to only currently supported version (3.2.0)"
  .changeset/fair-years-share.md
  packages/build-utils/test/integration.test.ts
  packages/static-build/src/index.ts
  packages/static-build/test/integration-setup.js
Labels: pr: automerge

#11137 Revert "Revert "Default ruby to only currently supported version (3.2.0)""
  .changeset/clean-pets-jog.md
  packages/build-utils/test/integration.test.ts
  packages/static-build/src/index.ts
  packages/static-build/test/integration-setup.js
Labels: pr: automerge

#11148 build: upgrade edge-runtime
  .changeset/hungry-coins-notice.md
  packages/cli/package.json
  packages/node/package.json
  packages/node/src/dev-server.mts
  packages/node/src/edge-functions/edge-handler.mts
  packages/node/src/serverless-functions/helpers-web.ts
  packages/node/src/serverless-functions/serverless-handler.mts
  packages/node/test/dev-fixtures/serverless-web.js
  packages/node/test/dev-fixtures/web-handlers-edge.js
  packages/node/test/dev-fixtures/web-handlers-node.js
  packages/node/test/unit/dev.test.ts
  pnpm-lock.yaml
Labels: pr: automerge

#11150 refactor: simplify content-length check
  .changeset/yellow-months-divide.md
  packages/node/src/edge-functions/edge-handler.mts
Labels: pr: automerge

#11152 [remix] Don't install Remix fork when not using split configuration
  .changeset/cool-buttons-suffer.md
  packages/remix/src/build.ts
Labels: pr: automerge

#11153 [remix] Add `serverBundles` post-build sanity check and fallback
  .changeset/nasty-cameras-rule.md
  packages/remix/src/build.ts
  packages/remix/test/fixtures/14-node-linker-hoisted/.gitignore
  packages/remix/test/fixtures/14-node-linker-hoisted/.npmrc
  packages/remix/test/fixtures/14-node-linker-hoisted/.prettierignore
  packages/remix/test/fixtures/14-node-linker-hoisted/.prettierrc
  packages/remix/test/fixtures/14-node-linker-hoisted/apps/remix/.eslintrc.commit.js
  packages/remix/test/fixtures/14-node-linker-hoisted/apps/remix/.eslintrc.js
  packages/remix/test/fixtures/14-node-linker-hoisted/apps/remix/.gitignore
  packages/remix/test/fixtures/14-node-linker-hoisted/apps/remix/app/root.tsx
  packages/remix/test/fixtures/14-node-linker-hoisted/apps/remix/app/routes/_index.tsx
  packages/remix/test/fixtures/14-node-linker-hoisted/apps/remix/package.json
  packages/remix/test/fixtures/14-node-linker-hoisted/apps/remix/public/favicon.ico
  packages/remix/test/fixtures/14-node-linker-hoisted/apps/remix/remix.config.js
  packages/remix/test/fixtures/14-node-linker-hoisted/apps/remix/remix.env.d.ts
  packages/remix/test/fixtures/14-node-linker-hoisted/apps/remix/tsconfig.json
  packages/remix/test/fixtures/14-node-linker-hoisted/apps/remix/vercel.json
  packages/remix/test/fixtures/14-node-linker-hoisted/package.json
  packages/remix/test/fixtures/14-node-linker-hoisted/pnpm-lock.yaml
  packages/remix/test/fixtures/14-node-linker-hoisted/pnpm-workspace.yaml
  packages/remix/test/fixtures/14-node-linker-hoisted/probes.json
  packages/remix/test/fixtures/14-node-linker-hoisted/tsconfig.json
  packages/remix/test/fixtures/14-node-linker-hoisted/turbo.json
  packages/remix/test/fixtures/14-node-linker-hoisted/vercel.json
Labels: pr: automerge

#11155 [node][next][redwood][remix] bump `@vercel/nft@0.26.4`
  .changeset/strange-deers-complain.md
  packages/next/package.json
  packages/node/package.json
  packages/redwood/package.json
  packages/remix/package.json
  pnpm-lock.yaml
Labels: area: node, area: redwood, area: next, area: remix, pr: automerge

#11151 Restore ruby fixtures post deploy
  .changeset/forty-frogs-eat.md
  packages/build-utils/test/integration.test.ts
  packages/static-build/test/fixtures/35-bundle-without/Gemfile
  packages/static-build/test/fixtures/jekyll-v3/Gemfile
  packages/static-build/test/fixtures/jekyll-v3/Gemfile.lock
  packages/static-build/test/integration-setup.js
Labels: pr: automerge

#11177 [next] Add flag for experimental grouping
  .changeset/serious-mirrors-teach.md
  packages/next/src/server-build.ts
  packages/next/src/utils.ts
Labels: pr: automerge

#11184 fix: missing experimental field
  .changeset/swift-jobs-protect.md
  packages/next/src/server-build.ts
Labels: pr: automerge

#11182 Add immutability modifiers to types
  .changeset/wicked-ligers-rhyme.md
  packages/next/src/index.ts
  packages/next/src/server-build.ts
  packages/next/src/utils.ts
Labels: pr: automerge

#11187 Update experimental bundle flag
  .changeset/kind-pears-attend.md
  packages/next/src/utils.ts
Labels: pr: automerge

#11192 Fix manifest with experimental flag
  .changeset/brave-beds-call.md
  packages/next/src/server-build.ts
Labels: pr: automerge

#11205 [remix] Ensure the symlink directory exists in `ensureSymlink()`
  .changeset/weak-countries-pull.md
  packages/remix/src/utils.ts
  packages/remix/test/unit.ensure-resolvable.test.ts
Labels: pr: automerge
