Repository vercel/vercel, pull requests merged in 2024-07, with the labels that each got.

#11776 [redwood] Support API endpoint configuration via `export const config`
  .changeset/warm-dodos-ring.md
  packages/redwood/package.json
  packages/redwood/src/index.ts
  pnpm-lock.yaml
Labels: pr: automerge

#11494 Update SvelteKit v1 devCommand
  .changeset/mighty-bees-tell.md
  packages/frameworks/src/frameworks.ts
Labels: pr: automerge, pending-merge

#11646 [tests] refactor dev utils to typescript
  .changeset/dull-ties-pull.md
  packages/cli/test/dev/integration-1.test.ts
  packages/cli/test/dev/integration-2.test.ts
  packages/cli/test/dev/integration-3.test.ts
  packages/cli/test/dev/integration-4.test.ts
  packages/cli/test/dev/integration-5.test.ts
  packages/cli/test/dev/utils.ts
  packages/cli/test/tsconfig.json
Labels: pr: automerge

#11800 [next] Fix route handlers operation type
  .changeset/real-snails-sneeze.md
  packages/next/src/server-build.ts
  packages/next/src/utils.ts
Labels: pr: automerge

#11807 [next] Add build callback handling
  .changeset/lucky-ladybugs-attack.md
  packages/build-utils/src/types.ts
  packages/next/src/index.ts
Labels: pr: automerge

#11809 [next] Bump fs-extra
  .changeset/afraid-gifts-grab.md
  packages/next/package.json
  pnpm-lock.yaml
Labels: pr: automerge

#11808 [next]: ensure route handlers aren't skipped when creating .rsc variants
  .changeset/blue-colts-grow.md
  packages/next/src/server-build.ts
  packages/next/test/fixtures/00-app-dir-no-ppr/app/dynamic/[category]/page.js
  packages/next/test/fixtures/00-app-dir-no-ppr/app/dynamic/route-handler/route.js
  packages/next/test/fixtures/00-app-dir-no-ppr/vercel.json
  packages/next/test/integration/integration-1.test.js
Labels: pr: automerge

#11812 [next] Fix re-tracing app router entries
  .changeset/empty-seals-tease.md
  packages/next/src/server-build.ts
Labels: pr: automerge

#11817 Update CODEOWNERS
  .github/CODEOWNERS
Labels: pr: automerge

#11603 reject mismatched corepack and detected package managers
  .changeset/lemon-bears-talk.md
  packages/build-utils/src/fs/run-user-scripts.ts
  packages/build-utils/test/unit.detect-package-manager.test.ts
  packages/build-utils/test/unit.get-env-for-package-manager.test.ts
  packages/build-utils/test/unit.get-path-for-package-manager.test.ts
  packages/build-utils/test/unit.get-path-override-for-package-manager.test.ts
  packages/build-utils/test/unit.run-npm-install.test.ts
Labels: pr: automerge

#11826 Use support team for dependabot PR reviews
  .changeset/fluffy-cats-sit.md
  .github/dependabot.yml
Labels: pr: automerge

#11829 Use automerge in dependabot PRs
  .changeset/silent-rivers-juggle.md
  .github/dependabot.yml
Labels: pr: automerge

#11831 [tests] hide spammy token message in CI
  .changeset/small-rings-joke.md
  test/lib/deployment/now-deploy.js
Labels: pr: automerge

#11833 Revert "[framework-fixtures]: Bump the core group across 1 directory with 6 updates"
  .changeset/angry-islands-end.md
  .changeset/cool-foxes-drop.md
  packages/static-build/test/fixtures/hydrogen-v2023/package-lock.json
  packages/static-build/test/fixtures/hydrogen-v2023/package.json
Labels: pr: automerge

#11832 [tests] tweak CI requirements
  .changeset/fresh-cooks-sparkle.md
  .github/workflows/release.yml
  .github/workflows/test-18.yml
  .github/workflows/test-lint.yml
  .github/workflows/test.yml
Labels: pr: automerge

#11835 [tests] update workflows to better fit requirements for typical and release PRs
  .changeset/curly-zoos-drive.md
  .github/workflows/label-feature-request.yml
  .github/workflows/label-support.yml
  .github/workflows/label-triaged.yml
  .github/workflows/release.yml
  .github/workflows/test-18.yml
  .github/workflows/test-lint.yml
  .github/workflows/test.yml
  packages/cli/test/integration-3.test.ts
Labels: pr: automerge

#11790 [cli] Add `vc target ls` command
  .changeset/red-badgers-pretend.md
  packages/cli/src/commands/index.ts
  packages/cli/src/commands/target/command.ts
  packages/cli/src/commands/target/index.ts
  packages/cli/src/commands/target/list.ts
  packages/cli/src/index.ts
  packages/cli/src/util/output/create-output.ts
  packages/cli/src/util/target/types.ts
  packages/cli/test/mocks/project.ts
  packages/cli/test/unit/commands/target.test.ts
Labels: pr: automerge

#11838 [tests] trying to fix the bot force push issue
  .changeset/real-falcons-leave.md
  .github/workflows/release.yml
  .github/workflows/test-18.yml
  .github/workflows/test-lint.yml
  .github/workflows/test.yml
Labels: pr: automerge

#11843 [tests] remove pr target workflow
  .github/workflows/test-18.yml
  .github/workflows/test-lint.yml
  .github/workflows/test.yml
Labels: pr: automerge

#11846 [tests] remove failing deno test
  .changeset/lazy-news-help.md
  packages/cli/test/dev/fixtures/custom-runtime/.gitignore
  packages/cli/test/dev/fixtures/custom-runtime/api/user.ts
  packages/cli/test/dev/fixtures/custom-runtime/vercel.json
  packages/cli/test/dev/integration-2.test.ts
Labels: pr: automerge

#11840 [cli] Various improvements to `vc target ls`
  .changeset/clean-comics-lick.md
  packages/cli/src/commands/index.ts
  packages/cli/src/commands/target/command.ts
  packages/cli/src/commands/target/list.ts
Labels: pr: automerge

#11789 [cli][client] Add support for `vc deploy --target`
  .changeset/lovely-geese-attend.md
  packages/cli/src/commands/deploy/command.ts
  packages/cli/src/util/deploy/parse-target.ts
  packages/cli/test/unit/commands/__snapshots__/help.test.ts.snap
  packages/cli/test/unit/util/deploy/parse-target.test.ts
  packages/client/src/deploy.ts
  packages/client/src/types.ts
Labels: pr: automerge

#11821 [cli] Add `target` to `vc inspect` output
  .changeset/hungry-coats-yawn.md
  internals/types/index.d.ts
  packages/cli/src/commands/inspect/index.ts
  packages/cli/test/mocks/project.ts
  packages/cli/test/unit/commands/inspect.test.ts
Labels: pr: automerge

#11857 Add discussion auto close notice
  .changeset/slow-kings-enjoy.md
  .github/DISCUSSION_TEMPLATE/general.yml
  .github/DISCUSSION_TEMPLATE/help.yml
  .github/DISCUSSION_TEMPLATE/ideas.yml
  .github/DISCUSSION_TEMPLATE/show-and-tell.yml
Labels: pr: automerge

#11841 Upgrade to @vercel/nft 0.27.3 with a bug fix for browser mapping support
  .changeset/smooth-glasses-obey.md
  packages/next/package.json
  packages/node/package.json
  packages/redwood/package.json
  packages/remix/package.json
  pnpm-lock.yaml
Labels: pr: automerge

#11859 [cli] Readd diagnostics download operation
  .changeset/old-kids-perform.md
  .changeset/witty-readers-tie.md
  packages/cli/src/commands/build/index.ts
  packages/next/src/index.ts
Labels: area: cli, area: next, pr: automerge

#11811 Fix corepack `packageManager` detection on monorepos
  .changeset/weak-gifts-leave.md
  packages/build-utils/src/fs/run-user-scripts.ts
  packages/build-utils/test/fixtures/41-npm-workspaces-corepack/a/package.json
  packages/build-utils/test/fixtures/41-npm-workspaces-corepack/b/package.json
  packages/build-utils/test/fixtures/41-npm-workspaces-corepack/package.json
  packages/build-utils/test/fixtures/42-pnpm-workspaces-corepack/c/package.json
  packages/build-utils/test/fixtures/42-pnpm-workspaces-corepack/d/package.json
  packages/build-utils/test/fixtures/42-pnpm-workspaces-corepack/package.json
  packages/build-utils/test/fixtures/42-pnpm-workspaces-corepack/pnpm-workspace.yaml
  packages/build-utils/test/unit.test.ts
  packages/hydrogen/src/build.ts
  packages/next/src/index.ts
  packages/redwood/src/index.ts
  packages/remix/src/build-legacy.ts
  packages/remix/src/build-vite.ts
  packages/static-build/src/index.ts
Labels: pr: automerge

#11862 [next] Fix missing app route with mixed SSR/SSG dynamic route
  .changeset/sharp-onions-retire.md
  packages/next/src/server-build.ts
  packages/next/test/fixtures/00-app-dir-no-ppr/app/dynamic-mixed/[slug]/page.js
  packages/next/test/fixtures/00-app-dir-no-ppr/vercel.json
  packages/next/test/integration/integration-1.test.js
Labels: pr: automerge

#11844 [remix] Use `nativeFetch` mode when `unstable_singleFetch` is enabled
  .changeset/slow-meals-perform.md
  packages/remix/defaults/server-node.mjs
Labels: pr: automerge

#11863 [next] Make app route prerender filter dynamic route specific
  .changeset/warm-carrots-scream.md
  packages/next/src/server-build.ts
  packages/next/test/integration/integration-1.test.js
Labels: pr: automerge

#11865 Revert "Fix corepack `packageManager` detection on monorepos"
  .changeset/fluffy-countries-collect.md
  packages/build-utils/src/fs/run-user-scripts.ts
  packages/build-utils/test/fixtures/41-npm-workspaces-corepack/a/package.json
  packages/build-utils/test/fixtures/41-npm-workspaces-corepack/b/package.json
  packages/build-utils/test/fixtures/41-npm-workspaces-corepack/package.json
  packages/build-utils/test/fixtures/42-pnpm-workspaces-corepack/c/package.json
  packages/build-utils/test/fixtures/42-pnpm-workspaces-corepack/d/package.json
  packages/build-utils/test/fixtures/42-pnpm-workspaces-corepack/package.json
  packages/build-utils/test/fixtures/42-pnpm-workspaces-corepack/pnpm-workspace.yaml
  packages/build-utils/test/unit.test.ts
  packages/hydrogen/src/build.ts
  packages/next/src/index.ts
  packages/redwood/src/index.ts
  packages/remix/src/build-legacy.ts
  packages/remix/src/build-vite.ts
  packages/static-build/src/index.ts
Labels: pr: automerge

#11858 [cli] Add target flag to vc build
  .changeset/curvy-dragons-cheat.md
  packages/cli/src/commands/build/command.ts
  packages/cli/src/commands/build/index.ts
  packages/cli/test/unit/commands/build/index.test.ts
Labels: pr: automerge

#11879 Revert "warn on mismatched corepack and detected package managers"
  .changeset/polite-lobsters-complain.md
  packages/build-utils/src/fs/run-user-scripts.ts
  packages/build-utils/test/unit.detect-package-manager.test.ts
  packages/build-utils/test/unit.get-env-for-package-manager.test.ts
  packages/build-utils/test/unit.get-path-for-package-manager.test.ts
  packages/build-utils/test/unit.get-path-override-for-package-manager.test.ts
  packages/build-utils/test/unit.run-npm-install.test.ts
Labels: pr: automerge, build-container priority merge

#11890 [cli] Standardize target parsing
  .changeset/nervous-bulldogs-kick.md
  packages/cli/src/commands/build/index.ts
  packages/cli/src/commands/deploy/index.ts
  packages/cli/src/commands/env/index.ts
  packages/cli/src/commands/list/index.ts
  packages/cli/src/util/deploy/parse-target.ts
  packages/cli/src/util/parse-target.ts
  packages/cli/test/integration-3.test.ts
  packages/cli/test/unit/util/deploy/parse-target.test.ts
  packages/cli/test/unit/util/parse-target.test.ts
Labels: pr: automerge

#11889 [frameworks] Add FastHTML framework preset
  .changeset/chilled-emus-arrive.md
  .changeset/hip-poets-carry.md
  examples/__tests__/integration/fasthtml.test.ts
  examples/fasthtml/.gitignore
  examples/fasthtml/README.md
  examples/fasthtml/api/index.py
  examples/fasthtml/generate-sesskey.bash
  examples/fasthtml/main.py
  examples/fasthtml/package.json
  examples/fasthtml/public/favicon.ico
  examples/fasthtml/requirements.txt
  examples/fasthtml/vercel.json
  packages/cli/src/commands/build/index.ts
  packages/cli/src/util/build/sort-builders.ts
  packages/cli/test/unit/util/build/sort-builders.test.ts
  packages/frameworks/logos/fasthtml.svg
  packages/frameworks/src/frameworks.ts
Labels: pr: automerge

#11897 [cli] Remove validation on --environment for `vc pull`
  .changeset/five-needles-promise.md
  packages/cli/src/commands/env/index.ts
  packages/cli/src/commands/env/pull.ts
  packages/cli/src/commands/pull/index.ts
  packages/cli/test/unit/commands/env.test.ts
Labels: pr: automerge

#11895 [cli] Add support for linking an unlinked project
  .changeset/serious-penguins-notice.md
  packages/cli/src/commands/target/command.ts
  packages/cli/src/commands/target/index.ts
Labels: pr: automerge

#11900 [frameworks] "fasthtml" preset improvements
  .changeset/strong-teachers-pay.md
  examples/fasthtml/api/index.py
  examples/fasthtml/generate-sesskey.bash
  examples/fasthtml/package.json
  examples/fasthtml/vercel.json
  packages/frameworks/logos/fasthtml-dark.png
  packages/frameworks/logos/fasthtml.png
  packages/frameworks/logos/fasthtml.svg
  packages/frameworks/src/frameworks.ts
  packages/python/src/index.ts
Labels: pr: automerge

#11882 [tests] add vitest custom reporter
  .changeset/clean-rabbits-beam.md
  package.json
  packages/cli/package.json
  packages/node/package.json
  packages/node/vitest.config.mts
  packages/remix/package.json
  pnpm-lock.yaml
  test/lib/vitest-reporter.ts
  vercel.json
  vitest.config.mts
Labels: pr: automerge

#11906 [examples] Simplify FastHTML template
  .changeset/three-parents-allow.md
  examples/fasthtml/.gitignore
  examples/fasthtml/README.md
  examples/fasthtml/main.py
  examples/fasthtml/requirements.txt
Labels: area: examples, pr: automerge

#11908 [examples] Update FastHTML README and demo
  .changeset/young-kiwis-jog.md
  examples/fasthtml/README.md
  examples/fasthtml/main.py
Labels: area: examples

#11907 Fix issue where builder output was treating an api endpoint as a frontend route
  .changeset/dull-scissors-count.md
  packages/cli/src/commands/build/index.ts
  packages/cli/test/fixtures/unit/commands/build/build-output-api-with-api-dir/.gitiignore
  packages/cli/test/fixtures/unit/commands/build/build-output-api-with-api-dir/.vercel/project.json
  packages/cli/test/fixtures/unit/commands/build/build-output-api-with-api-dir/api/index.js
  packages/cli/test/fixtures/unit/commands/build/build-output-api-with-api-dir/build.mjs
  packages/cli/test/fixtures/unit/commands/build/build-output-api-with-api-dir/package.json
  packages/cli/test/unit/commands/build/index.test.ts
Labels: pr: automerge
