Repository vercel/vercel, pull requests merged in 2024-04, with the labels that each got.

#11306 [tests] Add Preact@10 to static build fixtures dependabot
  .changeset/twelve-sloths-matter.md
  .github/dependabot.yml
Labels: pr: automerge

#11321 [cli] Replace `inquirer` with `@inquirer/prompts`
  .changeset/silent-books-decide.md
  packages/cli/package.json
  packages/cli/src/commands/bisect/index.ts
  packages/cli/src/commands/certs/rm.ts
  packages/cli/src/commands/dns/rm.ts
  packages/cli/src/commands/env/add.ts
  packages/cli/src/commands/env/rm.ts
  packages/cli/src/commands/remove/index.ts
  packages/cli/src/util/client.ts
  packages/cli/src/util/input/confirm.ts
  packages/cli/src/util/input/edit-project-settings.ts
  packages/cli/src/util/input/input-project.ts
  packages/cli/src/util/input/input-root-directory.ts
  packages/cli/src/util/input/list.ts
  packages/cli/src/util/input/patch-inquirer.ts
  packages/cli/src/util/input/select-org.ts
  packages/cli/src/util/link/repo.ts
  packages/cli/src/util/login/prompt.ts
  packages/cli/src/util/projects/link.ts
  packages/cli/test/helpers/wait-for-prompt.ts
  packages/cli/test/integration-3.test.ts
  packages/cli/test/mocks/client.ts
  packages/cli/test/mocks/matchers/to-output.ts
  packages/cli/test/unit/commands/git.test.ts
  packages/cli/test/unit/commands/project.test.ts
  packages/cli/test/unit/util/confirm.test.ts
  pnpm-lock.yaml
Labels: pr: automerge

#11371 [node] Add import and require ts-node files for TypeScript in `vc dev`
  .changeset/silly-ladybugs-design.md
  packages/cli/test/dev/fixtures/vercel-ts-test/api/test.ts
  packages/cli/test/dev/fixtures/vercel-ts-test/backend/app.ts
  packages/cli/test/dev/fixtures/vercel-ts-test/package.json
  packages/cli/test/dev/fixtures/vercel-ts-test/yarn.lock
  packages/cli/test/dev/integration-5.test.ts
  packages/node/src/fork-dev-server.ts
Labels: pr: automerge

#11317 [cli] Change condition to be clearer positive framing
  .changeset/dirty-mails-rescue.md
  packages/cli/src/commands/deploy/index.ts
Labels: pr: automerge

#11373 Move CONTRIBUTING into README and improve docs on running integration tests locally
  .changeset/sour-countries-heal.md
  .github/CONTRIBUTING.md
  README.md
Labels: pr: automerge

#11156 [go] Added support for `1.22` and updated Go minor versions of `1.19`, `1.20` and `1.21`
  .changeset/early-bears-sip.md
  packages/cli/test/dev/integration-2.test.ts
  packages/go/src/go-helpers.ts
  packages/go/test/fixtures/01-cowsay/vercel.json
  packages/go/test/fixtures/10-go-mod-newer/vercel.json
  packages/go/test/fixtures/26-go-work-with-shared/probes.json
Labels: pr: automerge

#11283 [cli] Fix how we determine the GIT_CONFIG_PATH to support git worktrees and git submodules
  .changeset/gold-cats-smile.md
  packages/cli/src/util/git-helpers.ts
  packages/cli/src/util/link/repo.ts
Labels: area: cli, semver: patch, pr: automerge

#11279 [cli] Replace `promptBool` with `confirm` prompts
  .changeset/popular-foxes-camp.md
  packages/cli/src/commands/domains/buy.ts
  packages/cli/src/commands/domains/move.ts
  packages/cli/src/commands/domains/rm.ts
  packages/cli/src/commands/domains/transfer-in.ts
  packages/cli/src/commands/init/init.ts
  packages/cli/src/util/dns/get-dns-data.ts
  packages/cli/src/util/domains/purchase-domain-if-available.ts
  packages/cli/src/util/input/prompt-bool.ts
  packages/cli/test/integration-3.test.ts
  packages/cli/test/mocks/example-list-tars/astro.tar.gz
  packages/cli/test/mocks/example-list-tars/readme.md
  packages/cli/test/unit/commands/init.test.ts
Labels: pr: automerge

#11376 [cli] Deprecate promoting preview deployments to production
  .changeset/stupid-actors-judge.md
  packages/cli/src/commands/promote/request-promote.ts
Labels: pr: automerge

#11377 [cli] Avoid printing error when user does ctrl+c
  .changeset/honest-rockets-applaud.md
  packages/cli/src/util/handle-error.ts
Labels: pr: automerge

#11381 [tests] Revert "fetch vercel.com cert before builds and after tests"
  .changeset/strong-peas-fly.md
  .github/workflows/test.yml
Labels: pr: automerge

#11388 [cli] Improve UX for text input validation
  .changeset/orange-houses-rest.md
  packages/cli/src/commands/bisect/index.ts
  packages/cli/src/commands/env/add.ts
  packages/cli/src/commands/env/rm.ts
  packages/cli/src/util/input/input-project.ts
Labels: pr: automerge

#11393 Fix name for integration test
  .changeset/tidy-eagles-drum.md
  packages/cli/test/integration-1.test.ts
Labels: pr: automerge

#11392 [cli] Fix flickering during UI re-rendering
  .changeset/curvy-garlics-design.md
  packages/cli/package.json
  pnpm-lock.yaml
Labels: pr: automerge

#11380 [tests] Remove `disableSSO()` function
  .changeset/metal-rabbits-move.md
  packages/cli/test/dev/utils.js
  packages/cli/test/integration-1.test.ts
  packages/cli/test/integration-2.test.ts
  packages/cli/test/integration-3.test.ts
  packages/client/tests/create-deployment.test.ts
  test/lib/deployment/now-deploy.js
Labels: pr: automerge

#11387 [cli] Unify table formatting output
  .changeset/blue-kangaroos-sparkle.md
  packages/cli/package.json
  packages/cli/src/commands/alias/ls.ts
  packages/cli/src/commands/alias/rm.ts
  packages/cli/src/commands/certs/ls.ts
  packages/cli/src/commands/certs/rm.ts
  packages/cli/src/commands/dns/rm.ts
  packages/cli/src/commands/help.ts
  packages/cli/src/commands/list/index.ts
  packages/cli/src/commands/project/list.ts
  packages/cli/src/commands/remove/index.ts
  packages/cli/src/commands/secrets/index.js
  packages/cli/src/commands/teams/list.ts
  packages/cli/src/util/format-dns-table.ts
  packages/cli/src/util/format-ns-table.ts
  packages/cli/src/util/format-table.ts
  packages/cli/src/util/output/table.ts
  packages/cli/test/integration-3.test.ts
  packages/cli/test/unit/commands/teams.test.ts
  pnpm-lock.yaml
Labels: pr: automerge

#11403 [tests] Fix tarball URL from deleted project
  .changeset/real-tomatoes-kick.md
  packages/cli/test/unit/util/build/import-builders.test.ts
Labels: pr: automerge

#11397 chore: fix some typos
  errors/invalid-route-source.md
Labels: pr: automerge

#11363 [cli] Disallow promoting preview deployments to production
  .changeset/nine-countries-beg.md
  packages/cli/src/commands/promote/request-promote.ts
  packages/cli/test/unit/commands/promote.test.ts
Labels: semver: major, pr: automerge

#11400 [cli] Fix command recommendation
  .changeset/ten-yaks-deny.md
  packages/cli/src/commands/remove/index.ts
Labels: pr: automerge

#11410 [cli] Revert "Disallow promoting preview deployments to production (#11363)"
  .changeset/curly-cars-shop.md
  .changeset/nine-countries-beg.md
  packages/cli/src/commands/promote/request-promote.ts
  packages/cli/test/unit/commands/promote.test.ts
Labels: pr: automerge

#11390 [next] use middleware manifest worker environments
  .changeset/wicked-pillows-notice.md
  packages/next/src/utils.ts
Labels: pr: automerge

#11348 [cli] optional override of existing environment variables
  .changeset/healthy-ducks-try.md
  packages/cli/src/commands/env/add.ts
  packages/cli/src/commands/env/command.ts
  packages/cli/src/commands/env/index.ts
  packages/cli/src/util/env/add-env-record.ts
  packages/cli/src/util/env/get-env-records.ts
  packages/cli/src/util/env/known-error.ts
  packages/cli/src/util/env/remove-env-record.ts
  packages/cli/test/helpers/prepare.js
  packages/cli/test/integration-2.test.ts
  packages/cli/test/mocks/project.ts
Labels: pr: automerge

#11411 Revert "[cli] Revert "Disallow promoting preview deployments to production (#11363)""
  .changeset/nine-countries-beg.md
  packages/cli/src/commands/promote/request-promote.ts
  packages/cli/test/unit/commands/promote.test.ts
Labels: pr: automerge

#11408 [remix] Add custom `entry.server` for Vite test
  .changeset/clean-lobsters-travel.md
  packages/remix/test/fixtures-vite/05-custom-entry-server/.gitignore
  packages/remix/test/fixtures-vite/05-custom-entry-server/README.md
  packages/remix/test/fixtures-vite/05-custom-entry-server/app/entry.server.ts
  packages/remix/test/fixtures-vite/05-custom-entry-server/app/root.tsx
  packages/remix/test/fixtures-vite/05-custom-entry-server/app/routes/_index.tsx
  packages/remix/test/fixtures-vite/05-custom-entry-server/package-lock.json
  packages/remix/test/fixtures-vite/05-custom-entry-server/package.json
  packages/remix/test/fixtures-vite/05-custom-entry-server/probes.json
  packages/remix/test/fixtures-vite/05-custom-entry-server/tsconfig.json
  packages/remix/test/fixtures-vite/05-custom-entry-server/vite.config.ts
Labels: pr: automerge

#11409 Specify npm script to run during Find Changes step
  .changeset/fresh-pans-vanish.md
  .github/workflows/test.yml
  packages/cli/package.json
  turbo.json
  utils/chunk-tests.js
Labels: pr: automerge

#11405 [tests] Use `vercel-deno` for "custom-runtime" dev fixture
  .changeset/tame-fans-tickle.md
  packages/cli/test/dev/fixtures/custom-runtime/api/user.sh
  packages/cli/test/dev/fixtures/custom-runtime/api/user.ts
  packages/cli/test/dev/fixtures/custom-runtime/package.json
  packages/cli/test/dev/fixtures/custom-runtime/vercel.json
  packages/cli/test/dev/integration-2.test.ts
Labels: pr: automerge

#11133 [ci] Speed up CI with `macos-14`
  .changeset/kind-penguins-add.md
  .github/workflows/test.yml
  utils/chunk-tests.js
Labels: area: tests, pr: automerge

#11375 Introduce snapshot testing utilities
  .changeset/twelve-buses-bow.md
  packages/cli/test/helpers/is-windows.ts
  packages/cli/test/mocks/client.ts
  packages/cli/test/unit/commands/login.test.ts
  packages/cli/test/unit/util/build/import-builders.test.ts
  packages/cli/test/unit/util/input/playground.test.ts
Labels: pr: automerge

#11353 [cli] replace console.log that communicates to user with output.log
  .changeset/brave-dogs-reflect.md
  packages/cli/src/commands/alias/rm.ts
  packages/cli/src/commands/alias/set.ts
  packages/cli/src/commands/build/index.ts
  packages/cli/src/commands/dns/add.ts
  packages/cli/src/commands/dns/import.ts
  packages/cli/src/commands/dns/rm.ts
  packages/cli/src/commands/domains/add.ts
  packages/cli/src/commands/domains/buy.ts
  packages/cli/src/commands/domains/transfer-in.ts
  packages/cli/src/commands/remove/index.ts
  packages/cli/src/commands/secrets/index.js
  packages/cli/src/commands/teams/add.ts
  packages/cli/src/index.ts
  packages/cli/src/util/build/corepack.ts
  packages/cli/src/util/handle-error.ts
  packages/cli/src/util/link/setup-and-link.ts
  packages/cli/src/util/login/prompt.ts
  packages/cli/src/util/output/create-output.ts
  packages/cli/src/util/output/note.ts
  packages/cli/test/integration-3.test.ts
Labels: pr: automerge

#11308 [examples] Update to latest SolidStart
  .changeset/yellow-ties-grin.md
  examples/__tests__/integration/solidstart-1.test.ts
  examples/solidstart-1/.gitignore
  examples/solidstart-1/README.md
  examples/solidstart-1/app.config.ts
  examples/solidstart-1/package.json
  examples/solidstart-1/pnpm-lock.yaml
  examples/solidstart-1/public/favicon.ico
  examples/solidstart-1/src/app.css
  examples/solidstart-1/src/app.tsx
  examples/solidstart-1/src/components/Counter.css
  examples/solidstart-1/src/components/Counter.tsx
  examples/solidstart-1/src/entry-client.tsx
  examples/solidstart-1/src/entry-server.tsx
  examples/solidstart-1/src/global.d.ts
  examples/solidstart-1/src/routes/[...404].tsx
  examples/solidstart-1/src/routes/index.tsx
  examples/solidstart-1/tsconfig.json
  packages/frameworks/src/frameworks.ts
Labels: pr: automerge

#11430 [cli] Fix type error
  .changeset/gorgeous-tips-drop.md
  packages/cli/src/commands/env/command.ts
Labels: pr: automerge

#11396 [cli] Create argument parsing utility with clearer semantics
  .changeset/strange-beans-share.md
  packages/cli/src/commands/deploy/index.ts
  packages/cli/src/util/get-args.ts
  packages/cli/test/unit/util/parse-arguments.test.ts
Labels: pr: automerge

#11420 [tests] Remove old changelog tests
  .changeset/early-spoons-add.md
  test/utils/changelog/filter.test.js
  test/utils/changelog/group.test.js
  test/utils/changelog/parse.test.js
Labels: pr: automerge

#11432 Bump Github Actions to Node 20
  .changeset/olive-shirts-matter.md
  .github/workflows/cron-update-gatsby-fixtures.yml
  .github/workflows/cron-update-next.yml
  .github/workflows/cron-update-turbo.yml
  .github/workflows/release.yml
  .github/workflows/test-lint.yml
  .github/workflows/test.yml
  .github/workflows/update-remix-run-dev.yml
  examples/ember/.github/workflows/ci.yml
  packages/static-build/test/fixtures/ember-v5/.github/workflows/ci.yml
Labels: pr: automerge

#11433 Get flags specification
  .changeset/gentle-oranges-study.md
  packages/cli/src/commands/deploy/index.ts
  packages/cli/src/util/get-flags-specification.ts
  packages/cli/test/unit/util/get-flags-specification.test.ts
Labels: pr: automerge

#11415 Update packages causing vulnerability messages
  .changeset/shiny-pugs-tickle.md
  api/package.json
  package.json
  packages/node/package.json
  pnpm-lock.yaml
Labels: pr: automerge

#11442 [next] Remove un-necessary compressed function size calc/constraint
  .changeset/sweet-peas-sort.md
  packages/next/src/constants.ts
  packages/next/src/index.ts
  packages/next/src/server-build.ts
  packages/next/src/utils.ts
  packages/next/test/integration/integration-2.test.js
  packages/next/test/integration/legacy/integration-legacy.test.js
  packages/next/test/integration/test-limit-exceeded-404-static-files/next.config.js
  packages/next/test/integration/test-limit-exceeded-internal-files-server-build/next.config.js
  packages/next/test/integration/test-limit-exceeded-server-build/next.config.js
  packages/next/test/integration/test-limit-exceeded-shared-lambdas/next.config.js
Labels: pr: automerge

#11441 [next] Ensure _not-found is included properly in app router functions
  .changeset/calm-camels-complain.md
  packages/next/src/constants.ts
  packages/next/src/server-build.ts
  packages/next/test/fixtures/00-app-dir-not-found/app/[...page]/page.tsx
  packages/next/test/fixtures/00-app-dir-not-found/app/layout.tsx
  packages/next/test/fixtures/00-app-dir-not-found/app/not-found.tsx
  packages/next/test/fixtures/00-app-dir-not-found/app/page.tsx
  packages/next/test/fixtures/00-app-dir-not-found/index.test.js
  packages/next/test/fixtures/00-app-dir-not-found/middleware.ts
  packages/next/test/fixtures/00-app-dir-not-found/next.config.js
  packages/next/test/fixtures/00-app-dir-not-found/package.json
  packages/next/test/fixtures/00-app-dir-not-found/vercel.json
Labels: pr: automerge

#11439 Add snapshot tests for help
  .changeset/short-flies-clean.md
  packages/cli/test/unit/commands/__snapshots__/help.test.ts.snap
  packages/cli/test/unit/commands/help.test.ts
Labels: pr: automerge

#11450 [cli] Don't log error when running vc dev in a directory without a .git directory
  .changeset/cold-foxes-fry.md
  packages/cli/src/util/git-helpers.ts
Labels: pr: automerge

#11451 [cli] Sort default team to the top of the team selector
  .changeset/warm-shoes-beam.md
  packages/cli/src/util/input/select-org.ts
  packages/cli/test/mocks/team.ts
  packages/cli/test/unit/util/input/select-org.test.ts
Labels: pr: automerge

#11454 [next] add streaming prerender group for actions
  .changeset/big-dingos-jump.md
  packages/next/src/server-build.ts
  packages/next/src/utils.ts
  packages/next/test/fixtures/00-app-dir-actions/app/actions.js
  packages/next/test/fixtures/00-app-dir-actions/app/layout.js
  packages/next/test/fixtures/00-app-dir-actions/app/other/page.js
  packages/next/test/fixtures/00-app-dir-actions/app/page.js
  packages/next/test/fixtures/00-app-dir-actions/index.test.js
  packages/next/test/fixtures/00-app-dir-actions/next.config.js
  packages/next/test/fixtures/00-app-dir-actions/package.json
  packages/next/test/fixtures/00-app-dir-actions/public/.keep
  packages/next/test/fixtures/00-app-dir-actions/vercel.json
  packages/next/test/integration/integration-2.test.js
Labels: pr: automerge

#11452 Add eslint rule for no-console within the cli package
  .changeset/ten-dogs-exercise.md
  package.json
  packages/cli/src/commands/env/ls.ts
  packages/cli/src/commands/logs/index.ts
  packages/cli/src/commands/secrets/index.js
  packages/cli/src/commands/teams/index.ts
  packages/cli/src/index.ts
  packages/cli/src/util/config/files.ts
  packages/cli/src/util/dev/builder-worker.js
  packages/cli/src/util/dev/server.ts
  packages/cli/src/util/get-latest-version/get-latest-worker.js
  packages/cli/src/util/handle-error.ts
  packages/cli/src/util/secrets.js
  packages/cli/test/dev/integration-1.test.ts
  packages/cli/test/dev/integration-3.test.ts
  packages/cli/test/dev/integration-5.test.ts
  packages/cli/test/dev/utils.js
  packages/cli/test/helpers/exec.ts
  packages/cli/test/helpers/get-global-dir.ts
  packages/cli/test/helpers/wait-for-prompt.ts
  packages/cli/test/integration-1.test.ts
  packages/cli/test/integration-2.test.ts
  packages/cli/test/integration-3.test.ts
  packages/cli/test/mocks/client.ts
  packages/cli/test/unit/commands/build/index.test.ts
  packages/cli/test/unit/util/dev/parse-listen.test.ts
  packages/cli/test/unit/util/input/playground.test.ts
Labels: pr: automerge

#11461 [next] add .action handling for dynamic routes
  .changeset/cold-pianos-check.md
  packages/next/src/utils.ts
  packages/next/test/fixtures/00-app-dir-actions/app/[dynamic-static]/page.js
  packages/next/test/fixtures/00-app-dir-actions/index.test.js
Labels: pr: automerge

#11455 [static-build] Don't rely on `hugo` binary existing in build-container
  .changeset/odd-rivers-jog.md
  .github/workflows/test.yml
  packages/cli/test/dev/integration-3.test.ts
  packages/static-build/package.json
  packages/static-build/src/index.ts
  packages/static-build/src/utils/hugo.ts
  packages/static-build/test/hugo.test.ts
Labels: pr: automerge

#11170 [tests] Add Vite@5 fixture to dependabot
  .changeset/ninety-icons-suffer.md
  .github/dependabot.yml
Labels: pr: automerge

#11473 Add retry logic for when a probe finds the Vercel preview page
  .changeset/lovely-meals-mix.md
  test/lib/deployment/test-deployment.js
Labels: pr: automerge

#11478 [python] Add `python3.12`
  .changeset/smooth-frogs-sort.md
  packages/python/src/version.ts
  packages/python/test/fixtures/00-request-path/package.json
  packages/python/test/fixtures/11-asgi/package.json
  packages/python/test/fixtures/12-asgi-function/package.json
  packages/python/test/fixtures/20-multivalue-header/package.json
  packages/python/test/fixtures/28-pydantic/package.json
  packages/python/test/fixtures/32-fail-duplicate-header/package.json
  packages/python/test/integration-setup.js
Labels: pr: automerge

#11481 [remix] Don't build the "example" template in legacy e2e tests
  .changeset/thick-pugs-share.md
  packages/remix/test/integration-legacy.test.ts
Labels: pr: automerge

#11487 [next] Reland add .action handling for dynamic routes
  .changeset/eleven-dodos-call.md
  packages/next/src/index.ts
  packages/next/src/server-build.ts
  packages/next/src/utils.ts
  packages/next/test/fixtures/00-app-dir-actions/app/layout.js
  packages/next/test/fixtures/00-app-dir-actions/index.test.js
  packages/next/test/fixtures/00-app-dir-actions/next.config.js
  packages/next/test/integration/integration-2.test.js
Labels: pr: automerge

#11467 [cli] Migrate alias command to use parseArguments and getFlagsSpecification
  .changeset/strong-spoons-sniff.md
  packages/cli/src/commands/alias/command.ts
  packages/cli/src/commands/alias/index.ts
  packages/cli/test/unit/commands/__snapshots__/help.test.ts.snap
Labels: pr: automerge

#11485 Erikarowland/zero 1891 update ionic angular package in fixtures
  .changeset/hungry-terms-refuse.md
  .github/dependabot.yml
  packages/static-build/test/fixtures/ionic-angular-v8/.gitignore
  packages/static-build/test/fixtures/ionic-angular-v8/angular.json
  packages/static-build/test/fixtures/ionic-angular-v8/ionic.config.json
  packages/static-build/test/fixtures/ionic-angular-v8/package-lock.json
  packages/static-build/test/fixtures/ionic-angular-v8/package.json
  packages/static-build/test/fixtures/ionic-angular-v8/src/app/app.component.html
  packages/static-build/test/fixtures/ionic-angular-v8/src/app/app.component.ts
  packages/static-build/test/fixtures/ionic-angular-v8/src/app/app.module.ts
  packages/static-build/test/fixtures/ionic-angular-v8/src/environments/environment.prod.ts
  packages/static-build/test/fixtures/ionic-angular-v8/src/environments/environment.ts
  packages/static-build/test/fixtures/ionic-angular-v8/src/index.html
  packages/static-build/test/fixtures/ionic-angular-v8/src/main.ts
  packages/static-build/test/fixtures/ionic-angular-v8/src/polyfills.ts
  packages/static-build/test/fixtures/ionic-angular-v8/src/zone-flags.ts
  packages/static-build/test/fixtures/ionic-angular-v8/tsconfig.app.json
  packages/static-build/test/fixtures/ionic-angular-v8/tsconfig.json
  packages/static-build/test/fixtures/ionic-angular-v8/tsconfig.spec.json
  packages/static-build/test/fixtures/ionic-angular-v8/vercel.json
Labels: pr: automerge

#11509 Revert "[next] Reland add .action handling for dynamic routes"
  .changeset/neat-plants-fix.md
  packages/next/src/index.ts
  packages/next/src/server-build.ts
  packages/next/src/utils.ts
  packages/next/test/fixtures/00-app-dir-actions/app/layout.js
  packages/next/test/fixtures/00-app-dir-actions/index.test.js
  packages/next/test/fixtures/00-app-dir-actions/next.config.js
  packages/next/test/integration/integration-2.test.js
Labels: pr: automerge

#11506 [build-utils] Fix `getPrefixedEnvVars()` to handle `VERCEL_PROJECT_PRODUCTION_URL`
  .changeset/short-bears-sit.md
  packages/build-utils/src/get-prefixed-env-vars.ts
  packages/build-utils/test/unit.get-prefixed-env-vars.test.ts
Labels: area: build-utils, pr: automerge

#11501 [static-build] Add ParcelJS to dependabot
  .changeset/short-roses-obey.md
  .github/dependabot.yml
Labels: pr: automerge

#11518 [static-build] Fix running of e2e tests
  .changeset/lovely-apricots-repeat.md
  packages/static-build/src/index.ts
  packages/static-build/test/integration-setup.js
Labels: pr: automerge

#11514 [next] Update test fixture version
  .changeset/gentle-sloths-rescue.md
  packages/next/test/fixtures/00-app-dir-base-path/vercel.json
  packages/next/test/fixtures/00-app-dir-no-ppr/package.json
  packages/next/test/fixtures/00-app-dir-no-ppr/vercel.json
Labels: pr: automerge

#11503 Fix missing .rsc outputs for pages prerenders
  .changeset/clean-buttons-hunt.md
  packages/next/src/utils.ts
  packages/next/test/fixtures/00-app-dir-no-ppr/app/nested/[...rest]/page.js
  packages/next/test/fixtures/00-app-dir-no-ppr/pages/nested/blog-fallback-false/[slug].js
  packages/next/test/fixtures/00-app-dir-no-ppr/vercel.json
Labels: pr: automerge

#11492 Migrate build argument parsing
  .changeset/strange-zoos-sit.md
  packages/cli/src/commands/build/command.ts
  packages/cli/src/commands/build/index.ts
Labels: pr: automerge
