Repository vercel/vercel, pull requests merged in 2024-01, with the labels that each got.

#11005 [next] Ensure rewrites handle RSC requests
  .changeset/empty-socks-change.md
  packages/next/src/server-build.ts
  packages/next/test/fixtures/00-app-dir-no-ppr/next.config.js
  packages/next/test/fixtures/00-app-dir-no-ppr/vercel.json
  packages/next/test/fixtures/00-app-dir-ppr/next.config.js
  packages/next/test/fixtures/00-app-dir-ppr/vercel.json
Labels: pr: automerge

#11009 [next][node][redwood][remix] Bump `@vercel/nft@0.26.2`
  .changeset/olive-books-fold.md
  packages/next/package.json
  packages/node/package.json
  packages/redwood/package.json
  packages/remix/package.json
  pnpm-lock.yaml
Labels: pr: automerge

#10990 [static-build] Update stencil fixture to latest 4.x
  .changeset/silent-rocks-wash.md
  packages/static-build/test/fixtures/stencil-v4/package-lock.json
  packages/static-build/test/fixtures/stencil-v4/package.json
Labels: area: tests, area: static-build, pr: automerge

#11013 [cli] handle rate limit respones when fetching /teams endpoint
  .changeset/stale-cougars-nail.md
  packages/cli/src/index.ts
Labels: area: cli, pr: automerge

#11028 [docs] fix edge IP_HEADER_NAME header typedoc typo
  packages/edge/docs/README.md
  packages/edge/src/edge-headers.ts
Labels: pr: automerge

#11025 [cli] Display actual deployment's 'target'
  .changeset/unlucky-wasps-ring.md
  packages/cli/src/util/deploy/process-deployment.ts
  packages/cli/test/integration-2.test.ts
Labels: area: cli, pr: automerge

#11010 [build-utils] Deprecate `EdgeFunction#name` property
  .changeset/seven-carrots-begin.md
  packages/build-utils/src/edge-function.ts
  packages/hydrogen/src/build.ts
  packages/node/src/index.ts
  packages/remix/src/build.ts
  packages/static-build/src/utils/build-output-v2.ts
Labels: pr: automerge

#11027 [cli] Serialize duplicate `EdgeFunction` references as symlinks in `vc build`
  .changeset/large-baboons-train.md
  packages/cli/src/util/build/write-build-result.ts
  packages/cli/test/fixtures/unit/commands/build/functions-symlink/.vercel/builders/.gitignore
  packages/cli/test/fixtures/unit/commands/build/functions-symlink/.vercel/builders/node_modules/functions-symlink/main.js
  packages/cli/test/fixtures/unit/commands/build/functions-symlink/.vercel/builders/node_modules/functions-symlink/package.json
  packages/cli/test/fixtures/unit/commands/build/functions-symlink/.vercel/project.json
  packages/cli/test/fixtures/unit/commands/build/functions-symlink/package.json
  packages/cli/test/fixtures/unit/commands/build/functions-symlink/vercel.json
  packages/cli/test/unit/commands/build/index.test.ts
Labels: pr: automerge

#10958 [python] update fastapi to 0.105.0
  .changeset/good-crabs-share.md
  packages/python/test/fixtures/28-pydantic/requirements.txt
Labels: area: tests, pr: automerge, semver: none

#11050 Use `worker.name` instead of edge function name to fix type error in `@vercel/next`
  .changeset/rich-lemons-matter.md
  packages/next/src/utils.ts
Labels: semver: patch, area: next, pr: automerge

#11038 [remix] Fix functions without a output path edge case
  .changeset/long-hats-argue.md
  packages/remix/src/utils.ts
  packages/remix/test/unit.get-path-from-route.test.ts
Labels: pr: automerge

#11039 Remove `@cb1kenobi` from CODEOWNERS
  .changeset/angry-chairs-occur.md
  .github/CODEOWNERS
Labels: pr: automerge

#11053 [tests] update FastAPI fixture to latest
  .changeset/twelve-trains-check.md
  packages/python/test/fixtures/28-pydantic/requirements.txt
Labels: pr: automerge

#11051 [cli] Add documentation string for `skip-domain` option
  .changeset/sharp-teachers-greet.md
  packages/cli/src/commands/deploy/command.ts
  packages/cli/test/unit/commands/__snapshots__/help.test.ts.snap
Labels: pr: automerge

#11061 Add retry handling when hitting SSO
  test/lib/deployment/fetch-retry.js
  test/lib/deployment/now-deploy.js
Labels: area: tests, pr: automerge

#11059 Add experimental field to Lambda and size to FileFsRef output
  .changeset/honest-bobcats-agree.md
  packages/build-utils/src/file-fs-ref.ts
  packages/build-utils/src/lambda.ts
Labels: pr: automerge

#11067 fix support link
  .github/ISSUE_TEMPLATE/config.yml
Labels: pr: automerge

#11048 [cli, static-builds] deprecation notice for speed insights injection
  .changeset/brave-dots-deny.md
  packages/cli/src/commands/build/index.ts
  packages/cli/test/unit/commands/build/index.test.ts
  packages/static-build/src/utils/gatsby.ts
  packages/static-build/src/utils/nuxt.ts
  packages/static-build/test/builds.test.js
Labels: pr: automerge

#11077 [client] Upload files referenced by "filePathMap" during `vc deploy --prebuilt`
  .changeset/violet-laws-run.md
  packages/client/src/utils/index.ts
  packages/client/tests/fixtures/file-system-api/.gitignore
  packages/client/tests/fixtures/file-system-api/.vercel/output/functions/api/another.func/.vc-config.json
  packages/client/tests/fixtures/file-system-api/.vercel/output/functions/api/example.func/.vc-config.json
  packages/client/tests/unit.utils.test.ts
Labels: pr: automerge

#11080 [python][ruby][cli] Remove deprecated `createLambda()` usage
  .changeset/heavy-bananas-battle.md
  .changeset/khaki-items-juggle.md
  packages/cli/src/util/dev/builder-worker.js
  packages/cli/src/util/dev/builder.ts
  packages/python/src/index.ts
  packages/ruby/src/index.ts
Labels: pr: automerge

#11060 [cli] Emit "filePathMap" in `vc-config.json` for `FileFsRef` instances
  .changeset/unlucky-shirts-fail.md
  packages/cli/src/commands/build/index.ts
  packages/cli/src/util/build/write-build-result.ts
Labels: pr: automerge

#11087 [static-build] Update parcel@2 fixture to latest minor
  .changeset/chatty-trees-yawn.md
  packages/static-build/test/fixtures/parcel-v2/package-lock.json
  packages/static-build/test/fixtures/parcel-v2/package.json
Labels: pr: automerge

#11089 [static-build] update umijs@4 fixture to latest
  .changeset/shiny-swans-relax.md
  packages/static-build/test/fixtures/umi-v4/package-lock.json
  packages/static-build/test/fixtures/umi-v4/package.json
Labels: pr: automerge

#11104 Default ruby to only currently supported version (3.2.0)
  .changeset/tricky-rats-jog.md
  packages/build-utils/test/integration.test.ts
  packages/static-build/src/index.ts
  packages/static-build/test/integration-setup.js
Labels: pr: automerge

#11107 Fix rewrite RSC handling with trailingSlash
  .changeset/thirty-pears-whisper.md
  packages/next/src/server-build.ts
  packages/next/test/fixtures/00-app-dir-trailing-slash/next.config.js
  packages/next/test/fixtures/00-app-dir-trailing-slash/vercel.json
Labels: pr: automerge

#11099 Fix index normalizing for app outputs
  .changeset/nasty-teachers-wave.md
  packages/next/src/server-build.ts
  packages/next/src/utils.ts
  packages/next/test/fixtures/00-app-dir-no-ppr/app/dynamic-index/[slug]/index/page.js
  packages/next/test/fixtures/00-app-dir-no-ppr/vercel.json
  packages/next/test/fixtures/00-app-dir-ppr/app/dynamic-index/[slug]/index/page.js
  packages/next/test/fixtures/00-app-dir-ppr/vercel.json
Labels: pr: automerge
